In [1]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re
from collections import defaultdict

In [2]:
df_csv = pd.read_excel('data_new/2025_06_03_Liste der Entschädigungsämter mit Adressen, Varianten, Normalisierungen und Archiven.xlsx')
df_csv.head()

,Layout class,Filename,Bundesland,Transkription Compensation Office,Normalisierung Compensation Office1,Normalisierung Compensation Office2,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 8
0,ABC-Karten,1907_12_31_115_0,Niedersachsen,Goslar,Goslar,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
1,ABC-Karten,1909_01_06_66_0,Niedersachsen,Goslar. Stadt,Goslar,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
2,ABC-Karten,1904_01_08_54_0,Niedersachsen,Göttingen-Stadt,Göttingen,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
3,ABC-Karten,1909_01_04_67_0,Niedersachsen,Hannover,Hannover,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN
4,ABC-Karten,1907_09_13_66_0,Niedersachsen,Hannover - Stadt,Hannover,NaN,Niedersächsisches Landesarchiv,6510041-4,NaN

In [3]:
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.head()

,CompensationOffice1,BZKNr,filename
0,Regierungsbezirksamt für Wiedergutmachung und ...,65477,1875_00_00_101_0.jpg
1,Landesamt für die Wiedergutmachung Karlsruhe,EK 20093 A,1875_04_05_16_0.jpg
2,Niedersachsen,1 27574 c,1875_06_15_14_0.jpg
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg
4,Entschädigungsamt Berlin,70 002,1875_07_12_9_0.jpg

In [4]:
print(len(df_csv))
print(len(df_json))

n = df_json['CompensationOffice1'].isin(df_csv['Transkription Compensation Office ']).sum()
print(f'Number of matches: {n}')

432
1901284
Number of matches: 1121989

In [5]:
print(len(df_csv))
print(len(df_json))

n = df_json['CompensationOffice1'].isin(df_csv['Normalisierung Compensation Office1']).sum()
print(f'Number of matches: {n}')

432
1901284
Number of matches: 1271792

# Matching based on Lvenshtein Distance

In [6]:
compensation_offices = list(df_csv['Transkription Compensation Office '])

# remove linebreaks and sequences of whitespaces
def remove_linebreak(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

# return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = remove_linebreak(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'].apply(remove_linebreak),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})


df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
3,bezirksamt für wiedergutmachung neustadt a.d.w.,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,2.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
6,köln,Köln,0.0
7,amt für wiedergutmachung des selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,9.0
8,landesentschädigungsamt schleswig-holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,0.0
9,hessen kassel,Hessen Kassel,0.0
10,nordrhein-westfalen,Nordrhein-Westfalen,0.0
11,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
12,bezirksamt für wiedergutmachung köln,Bezirksamt\nfür Wiedergutmachung\nMainz,4.0
13,der regierungspräsidium düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,köln,Köln,0.0
15,bezirksamt für wiedergutmachung trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,"hansestadt hamburg, sozialbehörde, amt für wie...","Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,freiburg,Freiburg,0.0
18,hessen,HESSEN,0.0
19,regierungsbezirk für wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,4.0

In [7]:
print(f"Max MatchDistance: {df_matches['MatchDistance'].max()}")

Max MatchDistance: 67.0

In [8]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1422553 (74.82%)
MatchDistance = 1: 64181 (3.38%)
MatchDistance = 2: 24338 (1.28%)
MatchDistance = 3: 22174 (1.17%)
MatchDistance = 4: 43427 (2.28%)
MatchDistance = 5: 10556 (0.56%)
MatchDistance = 6: 24863 (1.31%)
MatchDistance = 7: 6000 (0.32%)
MatchDistance = 8: 5527 (0.29%)
MatchDistance = 9: 21281 (1.12%)
MatchDistance = 10: 4723 (0.25%)
MatchDistance = 11: 4948 (0.26%)
MatchDistance = 12: 10445 (0.55%)
MatchDistance = 13: 3799 (0.20%)
MatchDistance = 14: 2865 (0.15%)
MatchDistance = 15: 2546 (0.13%)
MatchDistance = 16: 2157 (0.11%)
MatchDistance = 17: 2515 (0.13%)
MatchDistance = 18: 2200 (0.12%)
MatchDistance = 19: 5012 (0.26%)
MatchDistance = 20: 1370 (0.07%)
MatchDistance = 21: 1184 (0.06%)
MatchDistance = 22: 13140 (0.69%)
MatchDistance = 23: 1557 (0.08%)
MatchDistance = 24: 17755 (0.93%)
MatchDistance = 25: 808 (0.04%)
MatchDistance = 26: 2887 (0.15%)
MatchDistance = 27: 408 (0.02%)
MatchDistance = 28: 279 (0.01%)
MatchDistance = 29: 705 (0.04%)
MatchDistance = 30: 199 (0.01%)
MatchDistance = 31: 1249 (0.07%)
MatchDistance = 32: 251 (0.01%)
MatchDistance = 33: 874 (0.05%)
MatchDistance = 34: 345 (0.02%)
MatchDistance = 35: 144 (0.01%)
MatchDistance = 36: 646 (0.03%)
MatchDistance = 37: 43 (0.00%)
MatchDistance = 38: 33 (0.00%)
MatchDistance = 39: 43 (0.00%)
MatchDistance = 40: 19 (0.00%)
MatchDistance = 41: 37 (0.00%)
MatchDistance = 42: 10 (0.00%)
MatchDistance = 43: 15 (0.00%)
MatchDistance = 44: 17 (0.00%)
MatchDistance = 45: 7 (0.00%)
MatchDistance = 46: 5 (0.00%)
MatchDistance = 47: 8 (0.00%)
MatchDistance = 48: 8 (0.00%)
MatchDistance = 49: 2 (0.00%)
MatchDistance = 50: 4 (0.00%)
MatchDistance = 51: 4 (0.00%)
MatchDistance = 52: 2 (0.00%)
MatchDistance = 53: 3 (0.00%)
MatchDistance = 54: 2 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 9 (0.00%)
MatchDistance = 60: 2 (0.00%)
MatchDistance = 61: 14 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)

In [9]:
df_nomatches = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('data_new/compensation_office_nomatches.xlsx', index=False)

KeyboardInterrupt:

In [10]:
df_exact_matches_or_nan = df_matches[(df_matches['MatchDistance'] == 0) | (df_matches['CompensationOffice1'].isna()) | (df_matches['CompensationOffice1'] == 'nan')]

df_exact_matches_or_nan

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
...,...,...,...
1901279,bayerisches landesentschädigungsamt,Bayerisches Landesentschädigungsamt,0.0
1901280,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
1901281,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
1901282,bezirksamt für wiedergutmachung koblenz,Bezirksamt für Wiedergutmachung Koblenz,0.0
1901283,bezirksamt für wiedergutmachung mainz,Bezirksamt\nfür Wiedergutmachung\nMainz,0.0

In [11]:
df_json["norm_office"] = df_json["CompensationOffice1"].apply(remove_linebreak)

exact_norm = set(df_exact_matches_or_nan["CompensationOffice1"].dropna())

df_json_filtered = df_json[~df_json["norm_office"].isin(exact_norm)].copy()

print(len(df_json), len(df_json_filtered))
df_json_filtered.head()

1901284 403393

,CompensationOffice1,BZKNr,filename,norm_office
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg,bezirksamt für wiedergutmachung neustadt a.d.w.
7,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
12,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
13,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
16,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,"hansestadt hamburg, sozialbehörde, amt für wie..."

In [12]:
df_json_filtered.to_json('data_new/compoff_extracted_filtered.jsonl', orient='records', lines=True)

# Continuing with Partial Dataset

In [26]:
df_json_filtered = pd.read_json('data_new/compoff_extracted_filtered.jsonl', lines=True)

df_json_filtered

,CompensationOffice1,BZKNr,filename,norm_office
0,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg,bezirksamt für wiedergutmachung neustadt a.d.w.
1,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
2,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
3,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
4,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,"hansestadt hamburg, sozialbehörde, amt für wie..."
...,...,...,...,...
403388,Aachen,41 952,1917_03_27_67_0.jpg,aachen
403389,Bayrisches Landesamt für Verfolgtenwesen,123312/VIII/55,1917_06_05_91_0.jpg,bayrisches landesamt für verfolgtenwesen
403390,Reg.-Präsident / Präsident des Verw.Bezirks,1 32601 a,1917_05_24_21_0.jpg,reg.-präsident / präsident des verw.bezirks
403391,Bezirksamt für Wiedergutmachung,111 427,1917_03_27_4_0.jpg,bezirksamt für wiedergutmachung
403392,Regierungsbezirksamt für Wiedergutmachung und ...,114 948,1917_07_04_61_0.jpg,regierungsbezirksamt für wiedergutmachung und ...

# Matching without Punctuation

In [27]:
def remove_linebreak(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

# remove linebreaks, punctuation and sequences of whitespaces
def remove_punctuation(s):
    p = ['?', '!', '.', ',', ';', ':', '-', '_', '(', ')', '[', ']', '{', '}', '"', "'", '/']
    for char in p:
        s = s.replace(char, ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

compensation_offices = list(df_csv['Transkription Compensation Office '])

print(compensation_offices[:10])

compensation_offices = [remove_linebreak(remove_punctuation(str(office))) for office in compensation_offices]

print(compensation_offices[:10])

['Goslar', 'Goslar. Stadt', 'Göttingen-Stadt', 'Hannover', 'Hannover - Stadt', 'Helmstedt', 'Hildesheim-Stadt', 'Kreissonderhilfsausschuß \nDelmenhorst', 'Kreissonderhilfsausschuß \ndes Landkreises Grafsch. Schaumburg', 'Kreissonderhilfsausschuß\nLeer/Ostfrld.']
['goslar', 'goslar stadt', 'göttingen stadt', 'hannover', 'hannover stadt', 'helmstedt', 'hildesheim stadt', 'kreissonderhilfsausschuß delmenhorst', 'kreissonderhilfsausschuß des landkreises grafsch schaumburg', 'kreissonderhilfsausschuß leer ostfrld']

In [28]:

#updated version of get_min_distance_dynamic_normalized that also removes punctuation
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak(remove_punctuation(name))
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        d = distance(name_clean, office)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json_filtered['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['CompensationOffice1'].apply(remove_punctuation),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,7.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,4.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,2.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
11,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,NaN,NaN
16,bundeskartei,NaN,NaN
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,3.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,NaN,NaN

In [29]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 52695 (13.06%)
MatchDistance = 1: 33758 (8.37%)
MatchDistance = 2: 10533 (2.61%)
MatchDistance = 3: 19465 (4.83%)
MatchDistance = 4: 43230 (10.72%)
MatchDistance = 5: 9382 (2.33%)
MatchDistance = 6: 23238 (5.76%)
MatchDistance = 7: 5665 (1.40%)
MatchDistance = 8: 5928 (1.47%)
MatchDistance = 9: 22167 (5.50%)
MatchDistance = 10: 3739 (0.93%)
MatchDistance = 11: 3571 (0.89%)
MatchDistance = 12: 10493 (2.60%)
MatchDistance = 13: 3929 (0.97%)
MatchDistance = 14: 3367 (0.83%)
MatchDistance = 15: 2666 (0.66%)
MatchDistance = 16: 2449 (0.61%)
MatchDistance = 17: 2543 (0.63%)
MatchDistance = 18: 2401 (0.60%)
MatchDistance = 19: 15760 (3.91%)
MatchDistance = 20: 2480 (0.61%)
MatchDistance = 21: 1545 (0.38%)
MatchDistance = 22: 1307 (0.32%)
MatchDistance = 23: 20327 (5.04%)
MatchDistance = 24: 1531 (0.38%)
MatchDistance = 25: 543 (0.13%)
MatchDistance = 26: 244 (0.06%)
MatchDistance = 27: 601 (0.15%)
MatchDistance = 28: 925 (0.23%)
MatchDistance = 29: 1739 (0.43%)
MatchDistance = 30: 392 (0.10%)
MatchDistance = 31: 498 (0.12%)
MatchDistance = 32: 250 (0.06%)
MatchDistance = 33: 793 (0.20%)
MatchDistance = 34: 72 (0.02%)
MatchDistance = 35: 74 (0.02%)
MatchDistance = 36: 31 (0.01%)
MatchDistance = 37: 42 (0.01%)
MatchDistance = 38: 26 (0.01%)
MatchDistance = 39: 39 (0.01%)
MatchDistance = 40: 28 (0.01%)
MatchDistance = 41: 13 (0.00%)
MatchDistance = 42: 16 (0.00%)
MatchDistance = 43: 8 (0.00%)
MatchDistance = 44: 10 (0.00%)
MatchDistance = 45: 9 (0.00%)
MatchDistance = 46: 6 (0.00%)
MatchDistance = 47: 10 (0.00%)
MatchDistance = 48: 7 (0.00%)
MatchDistance = 49: 0 (0.00%)
MatchDistance = 50: 3 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 3 (0.00%)
MatchDistance = 53: 1 (0.00%)
MatchDistance = 54: 4 (0.00%)
MatchDistance = 55: 13 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 3 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 8 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 0 (0.00%)
MatchDistance = 64: 1 (0.00%)

In [30]:
df_exact_matches = df_matches[df_matches['MatchDistance'] == 0]

df_exact_matches

,CompensationOffice1,MatchedOffice,MatchDistance
0,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
11,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
25,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
37,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
39,landesamt für die wiedergutmachung tübingen,landesamt für die wiedergutmachung tübingen,0.0
...,...,...,...
403358,oberfinanzdirektion köln,oberfinanzdirektion köln,0.0
403359,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
403366,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
403376,oberfinanzdirektion köln,oberfinanzdirektion köln,0.0
403392,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0

In [ ]:
df_json_filtered["norm_office"] = df_json_filtered["norm_office"].apply(remove_punctuation)

exact_norm = set(df_exact_matches["CompensationOffice1"].dropna())

df_json_filtered = df_json_filtered[~df_json_filtered["norm_office"].isin(exact_norm)].copy()

df_json_filtered

,CompensationOffice1,BZKNr,filename,norm_office
1,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
2,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
3,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
4,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,hansestadt hamburg sozialbehörde amt für wiede...
5,Regierungsbezirk für Wiedergutmachung und verw...,47 691,1875_04_05_13_0.jpg,regierungsbezirk für wiedergutmachung und verw...
...,...,...,...,...
403387,Reg.-Präsident /Präsident des Vereinsbezirks H...,1 27101 a,1917_06_23_32_0.jpg,reg präsident präsident des vereinsbezirks han...
403388,Aachen,41 952,1917_03_27_67_0.jpg,aachen
403389,Bayrisches Landesamt für Verfolgtenwesen,123312/VIII/55,1917_06_05_91_0.jpg,bayrisches landesamt für verfolgtenwesen
403390,Reg.-Präsident / Präsident des Verw.Bezirks,1 32601 a,1917_05_24_21_0.jpg,reg präsident präsident des verw bezirks
403391,Bezirksamt für Wiedergutmachung,111 427,1917_03_27_4_0.jpg,bezirksamt für wiedergutmachung

In [32]:
df_no_matches_no_punctuation = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]
df_no_matches_no_punctuation = df_no_matches_no_punctuation.sort_values('MatchDistance', ascending=False)
df_no_matches_no_punctuation.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
89799,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,64.0
10300,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,61.0
244488,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,60.0
388722,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,60.0
62861,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,60.0
245394,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,60.0
399515,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,60.0
242288,der regierungspräsident – dezernat für wiederg...,der regierungspräsident dezernat für wiedergut...,60.0
345444,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,60.0
48966,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,60.0
280796,der herr regierungspräsident dezernat für wied...,a der regierungspräsident dezernat für wiederg...,59.0
341058,a der regierungspräsident dezernat f wiedergut...,a der regierungspräsident dezernat für wiederg...,59.0
107952,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,58.0
294296,freie und hansestadt hamburg behörde für arbei...,behörde für arbeit gesunheit und soziales amt ...,58.0
267343,regierungspräsident dezernat für wiedergutmach...,b der oberkreisdirektor amt für wiedergutmachu...,58.0
83582,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,57.0
402562,der regierungspräsident dezernat 14 in detmold...,der regierungspräsident dezernat für wiedergut...,57.0
14315,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,57.0
128112,entschädigungsbehörde des landes rheinland pfa...,regierungsbezirksamt für wiedergutmachung und ...,56.0
154545,der regierungspräsident dezernat für wiedergut...,der regierungspräsident dezernat für wiedergut...,56.0

In [ ]:
df_no_matches_no_punctuation.to_excel('data_new/compensation_office_nomatches_no_punctuation.xlsx', index=False)

# No Matches

In [33]:
no_matched_office_df = df_nomatches[df_nomatches['MatchDistance'].isna()]

no_matched_office_df

,CompensationOffice1,MatchedOffice,MatchDistance
21,hess. staatsministerium,NaN,NaN
30,nan,NaN,NaN
32,freie und hansestadt hamburg,NaN,NaN
34,hess. staatsministerium,NaN,NaN
40,nan,NaN,NaN
...,...,...,...
1901202,hng,NaN,NaN
1901238,hng,NaN,NaN
1901254,reg.-präsident /präsident des vereinsbezirks h...,NaN,NaN
1901262,bayrisches landesamt für verfolgtenwesen,NaN,NaN
1901263,reg.-präsident / präsident des verw.bezirks,NaN,NaN

In [34]:
no_matched_office_df_set = set(no_matched_office_df['CompensationOffice1'])

len(no_matched_office_df_set)
for office in no_matched_office_df_set:
    print(office)

ksha lütt
reg.-präsident / präsident des v. bezirks hannover
bayrisches amt
niedersachsen / reg.-präsident / präsident des verw.-bezirks - hannover
ra adlerstein, d-dorf
bhf-nb3-01481
bay. landesamt für die opfer des nationalsozialismus
reg.-präsident / präsidentiales verwaltungsbeamt
kreissozialamt wattenstedt-salzgitter
st. h. 1665/1966 h
rheinisch-westfälische
niedersachsen-präsidium / präsidenten des merkwaertes
reparatur prüfungsamt (wiesbaden)
rostock
bundeszentrale für die opfer des nationalsozialismus
st.h. 602 s
erlanger
freib
kreissozialamt schauemburg-lippe
regierungsbezirk münz
köln, riehler pl.2, 5090 köln
kreisverwaltung arnswald (mf.)
x8lm
united restitution office, frankfurt (m)
ksh bameln-parmont
d1 380 e 2081 c 380
saarburg bezirksamt
united restitution office frankfurt/m. grünburgweg 119
st. h. 2018/1290 m
haftsschuld
landeszentrale - registrazentrale
amt für wiedergutmachung des bundesministeriums für vertriebene, flüchtlinge und kriegsbeschädigte in berlin
bah
regierungsbezirk von berlin
reg.-präsident / präsident des yerwo-bezirks hannover
regional office for compensation for victims of national socialism and their assets
tröber we 1054 trier
tr. name des verfolgten
loin
kreissozonderhilfsausschuss
niedersachsen-präsident/präsident des verw.-bezirks oldenburg
wiener landes-reg
ozerow-azar
niedersachsen / regierungspräsidium des verwaltungsbezirks braunschweig
255m
st.h. 2751
bayer. pl. berlin
81in
kreissozialamt hammeln-jeypm
zentrale für die opfer des nationalsozialismus
regierungsbezirksamt eifel-wald, verwaltungs-versicherungsamt trier
st. h. 640
sondervermögens- u. raubverwaltung
wehrmacht
reg.-präsident / präsident der verw.-bezirks behörde
bayerisches landesamt für verfolgte des nationalsozialismus
schreinsamt
aurich i. ostrfild.
kloppenburger kreis
reparierungsamt ankershagen (meißen)
kreissozialamt stadt colle
st. h. 5557 - 0
landes justizverwaltung, münchen
xslm
k81r
k.b.i.
ksha f.d. reg.bez. hildesh.
landesbezirksstelle münchen
polizeipräsidium a. d.
regional office for compensation and restitution
niedersachsen-reg.-präsident / präsident des verw.-bezirks hannover
niedersachsen reg.-präsident / präsident des vorw.-bezirks hannover
landesamt köln
niedersachsen - präsident /präsidialrat des merwbereichs hannover
regionalverwaltungsbehörde für wien und niederösterreich, neustadt a.d. weinstraße
doppelvermögens- und baufondsverwaltung
doppelmeldung tübingen
ksha mappen
görlitz
sondervermögens-uk b l e n z
chr. bayerisches landesvermögensamt münchen
kreissonderhilfsschule watenstedt-salzgitter
wuppertal
wolfenbüttel
theresienstadt
deutsche bundesrepublik
th. bayerisches verfolgungsamt
hemmerden, landstr. 4
varläger
regierungsbezirk neuss
wiener bundesgericht
heinrich und
amt für wiedergutmachung, hamburg 1, alstädter straße 8 (sprenkenhof)
höherer kommissar der vereinigung der flüchtlinge
regierung bremen (3-24)
ausw. amt bonn
hauptkasse
tr. bayerisches verwaltungsamt
landesamt für vomwentschädigung main übernommen, tageb. nr. 2315/54/ii/6
der reichsminister
hellmann
regierungsbezirk neustadt a. d. weinstr.
wirtschafts
k6 g
berlin/352 284
regionalverwaltungsbehörde für wien und niederösterreich, wien
dudelfeld
d2 6441 e 8846
kreissozialamt hammelburg
st. h. 3116 g.
kreissonderhilfsschüle peine
st. h. 3018
entsch.-behörde: reg.-präsident / präsident des verw.bezirks hannover
bayersches verfolgtenamt
kreis
bay. verwaltungsamt münchen 2, abt. 11
kreissonderhilfsschüle springe
karlsruhe/baden aussenstelle freiburg/br.
niedersachsen - reg.-präsident
st.h. 962
hess. staatsministerium wiesbaden
niedersachsen-präsident / präsident des volksgerichtshofs
reg.-präsident / präsident des verw.-bezirks in stade
fakrbow
hofn aray
niedersachsen / reg.-präsident / präsident des verwaltungsgerichts lüneburg
dm 150
k 3 10
regierungsbezirk aachen (10.11.)
vorläufige kommission
halbteild
zentrale stelle (münchen)
bayerische zentralstelle
rabierungsbehörde für wien-rutschmarkt und vorort
reg.-präsident / präsident des verw.-bezirksxoz hannover
frankfurt-m.
nestleift
abend
an bundeskartel
reg.-präsident / präsident-des-verw.-bezirks-hannover
schreiberding
agi.amt bremen
kreissonderhilfsschübe aurich
bayerisches verfolgtenbehörde
ksha heilbronn
ausssenstelle freiburg i.br.
reg.-präsident / präsident des verw.-bezirks oldenburg hannover
ksha salzgitter
vorgang an 13 4 fl
st.h.2510 v
bundesamt für verwaltungsgerichtshof
kreissozialamt düsseldorf-stadt
ausgleichsamt bremen
kreisonderschutzbehörde holzminden
ausgl. a. bremen
ksha soltau
anlage am 13.7.1963 v. kölner institut für wirtschaftsforschung
tr. landesnachrichtenamt münchen ii, aktenzeichen 11
bayerisches landesamt für versäumnis- und schadensersatz
st.h. 483 d
köln, richter, pl.2, 5000 köln 1
hächer
regierungsamt münchen (mf.)
rhein.pf.berlin
hunc. verw. amt
kreisondeserhlfsschutz
niedersachsen-präsident / präsident des mernw-bezirks
bezirksamt münchen 54904
tr. münchen 2, abt. 11
höherer kommissar der flüchtlinge
bundesverwaltungsamt
sonderhilfsschutz für den regierungsbezirk hannover
doppelimeldung
doppel meldung hannover
sachverständigenstelle für b-reg.
freiburg - karlsruhe
sozialamt hamburg
bezirksamt von koblenz trier
i.d. malicki
moskowicz
reg.-präsident / präsident des verw.bezirks hannover
sondervermögens-u. bautverwaltung
kreissozialhilfsschübe
statistisches landesamt nordrhein-westfalen, düsseldorf 1, postgeschäftsstelle 1105
mt für wiade aus achung des l. in berlin und-platz
entschädigungsbehörde: landesentschädigungsbehörde für die bundesrepublik deutschland
magistrat der stadt bremervörde
bmf-ub4
bundesarchiv ludwigsburg
ra kestenberg
niedersachsen-präsident / präsidentenamt
feststellungsbeschv. stuttgart erhalten
st.h. 1006 f
bayerische verwaltungsbehörde
ausglamt bremen
barbarus
tr. haschall
schauumburg-lippe
regierungsbezirk a
erfurt, ansbach, chamnitz
kreissozialamt celle-land
brd
st.h.2948 w
kreissozialamt aschendorf/ems
sozialgericht dortmund
darmstadt stuttgart
kreissozialamt stadt hannover
landesaussschuss hannover
reg.-präsident / präsident des verw.bezirks koblenz
kdj
doppelvermögens-u. bauverwaltung
aurich i, ostholt
hamburg, drehbahn 37 iv
an bundesk...
bay. kartei
staatsanwaltschaft münchen i
o.e.d. berlin
doppelvermögensabteilung köln
kreissozialamt fallingbostel
th. bayerische kartei
e 3873
ereis linlan
aurich über bundeskartellei
regional office for compensation and administration of assets, koblenz
regierung bonn (bzk)
reg.-träger münster
reg.-präsident / präsident des verw.-bezirks a
bay. staatsministerium
amt für wiedergutmachung, freie und hansestadt hamburg, arbeit- und sozialbehörde
kreissozialamt landkreis osterholz
h&im
bza zellendorf
doppelhelling
st.h.716 w
anstalt bünde
kölnstrubskommission
krefeld-linn
antragsdeskantei
landesentschädigungskommission für die bundesrepublik deutschland
st.h. 1409
bay. reparationspräsidium, bez. 14 in detmold
regierungsbezirk arnswalde (1945-47)
1601
regierungsbezirkskommission
niedersachsen-präsident / präsident des mernwertbezirks hannover
st.h. 1620 a
bayerisches landeszentrum für politische verfolgte des nationalsozialismus
tr. tr.
honer kommissar der vereinigten nationen für flüchlinge
heinrich-bayerisches landesamt für die opfer des nationalsozialismus
bmf/ivbf
kreissozialamt hannover-langenhagen
tr. landesstelle münchen
niedersachsen-präsident / präsident des merkx-bezirks
nds. minister des innern
rheinland-pfalz und verwaltete vermögen, mainz
tr. verfolgtenamt
st.h. 1797 k
h81n
victoria 9.3.06
kreissozialhilfsschübe goslar-stadt
wartensleben-salzgitter
regionalverwaltungsgericht für wiesbaden und verwaltbare kreise
sondervermögens-mainz
saarburg bezirksamt von koblenz 54445 für wiedergutmachung
entscheidungsbekannt
finanz
wiedergutmachungsstelle münchen
kreissozialamt lüneburg
der koerperausseit
kreissonderhilfesauschuss
dp camp lager lechfeld
cuxhaven-duven
reg.-präsident / präsident des vewobezirks hannover
bundesamt für verwaltungsvermögen, mainz
kreissozialamt hannover uelzen
niedersachsen-präsidium / präsident des verw.-bezirks
königstein
braunau
regierungsbezirk mainz
ausßenstelle freiburg
vereinigung mit
tr. bayerisches landesamt für verfolgungsgeschädigte
baytisches landesarchiv münchen
bav
nds.minister des innern
kalis
landsesamt münchen
landesbeiratssstelle stuttgart
kreisonderschutzbehörde ganderkesheim
könig/polen
staatsarchiv stuttgart
honer kommissar der vereinten nationen für flüchlinge
th. am
landesbeiratstelle stuttgart
verdienst
kreissozialamt neustadt a. rbg.
münchen 2, meiserstraße 11
bayerische kassationsbehörde
rheinische kassenstelle berlin
reg.-präsident / präsident des yerivo bezirks
14 9 24
yonemisministerium
an bundeskartellei
rechtsanwaltskanzlei landeck & mühlen
kreissozialhilfsschutz braunschweig-stadt
polizei/kriminalamt heilbronn
ra wolf
kreissonderhilfsausschüß
k 5 d
kreissonderhilfsschul
hessen staatsministerium
kreissozialhilfeausschübe
o. f.d.k. kälm
united restitution office, frankfurt/m. grüneburgweg 119
sachkartei für ber. reg.
niedersachsen-präsident / präsident des x. w. bezirks
landkreis co.eiholz
landesamt für die vermögensverwaltung der bundesrepublik deutschland
st. h. 3340 g
civi düsseldorf 17.7.02
landesamt für verfolgtenfragen münchen
kreissozialhilfsschule braunschweig-stadt
düsseldorf jetzt köln
ksha f.d. reg. bez. lüneburg
an referat 10 zi. 413
vbst-0h88
landeszentrale für politische opferfürsorge
61
hessen, staatsministerium
reg.-präsident / präsident des verw.-bezirksx lüneburg
c 2441
bayerisches landesamt für schäden des krieges und des fremdherrschaftszeitraums
d1 2602 d2 6354 e 8733
rosenberg, schule - geb. 48.99
kreissozialamt leer/ostfriesl.
h811
reg.-präsident / präsident der vereinigung
bmt - vb3
ns-härtefonds
reg.-präsident / präsidentmod. verw. bezirksverwaltung hannover
höherer kommissar der vereinten nationen für flüchtlinge köln
stuttgart-s, neue weinsteig 21
ksha watenstedt-salzg.
l.g. heimburg
generali-verwaltung, service-center köln
deutsche kartei
kreisonderhlfsschüle wolffenbüttel
bayerisches steigerwald
regional office for compensation of losses and restitution of property, trier
hess-niedermöller
kreissozialamt hann
o.staatsanw.kln
bauverwaltungsamt
reg.-präsident / präsident des landesbezirks hannover
k81g
niedersachsen - reg.-präsident / präsident des verw. bezirks osnabrück
7602
sozialamt münchen ii
landeszentrale für die vergütung der opfer des nationalsozialismus
regierungsbezirk arnach (münchen)
e 303 f 1034
st. h. 1459
niedersachsen reg.-präsident / präsident des verwaltungsgerichts hannover
bayern. landesarchiv. münchen
kreissozialhilfsschüssel peine
niedersachsen / reg.-präsident
landau, pf.
niedersachsen - präsident / präsident des landes
regierungsbezirk rheinhessen, vermögensverwaltung, mainz
reg.-präsident / präsident des verw.-bezirks, stadthaus
doppelfinanzierung münchen
kreissozialamt nordern
niedersachsen - reg.-präsident / präsident des verw.-bezirks - osnabrück
nienburg/weser
kreissozialamt harburg land
regierung arnsberg zur weiterleitung an die stadtverwaltung wattenscheid
münster, fritz koblentz
baytches
vorläufige abteilung koblenz
hjgsamt
kz gusen
bayerisches versäumnisamt
doppelmelded
reichsland-praesidium uebernagel am 2
1116
lohr / main
sachverständigenstelle für befristete
generaldirektion: service-center köln; versorgung
landesbeirat stuttgart
recha fischer geb.horwitz isidor horwitz leop.horwitz richard erlon, robert marshall 13.6.14, ernest watson 19.1.08 elsa engel geb.eichenbaum fritz eichenbaum 25.8.1890 alfred sonder 30.10.95 dr,erich sonder 11.11.1896 sidonie wagner geb.sonder ruth sohn geb,w. hanne holesowski geb.w. selma holz geb.w
581m
bvamt 8.1.70
niedersachsen-präsidium / präsident des verw.-bezirks lüneburg
hamerau landpolizeiposten bes. insp. kreis laufen
st. h. 1272 / 561 h
a) der regierungspräsident -dezernat f.wiedergutmachung- detmold b) landkreis höxter. amt für wiedergutmachung- höxter/weser
bayhössam
träger des bayerischen kompensationsamtes
sachverständigenstelle für b-reg
kreissozialamt fürth
schalow
niedersachsen-präsident / präsident des vexvo bezirks hannover
st.h. 2957
st. h. 2976
kreisvilsbofen, ndbv.
wiedergutmachungsbehörde
reg.-präsident /räsident des vero-bezirks hannover
regionalamt arnswald (wf.)
kreisonderhlfasschuf
rheinland-pfalz, landesentschädigungsbehörde, koblenz
4 10 1939
hess: staatsministerium
adiva, bureau de restitution, paris, 19. rue de téhéran
niedersachsen reg.-präsident /präsident des verw.-bezirks hannover
wiedergutmachung kassel
regionalamt münchen (west)
bayerische staatskanzlei
kass. bayerische kartei
landeszentrale für politische opferentschädigung
regierungsamt aachen (mfr.)
schöft bonn
d3 1691 f 838
ksha köln/land.
landschaftsverwaltungsamt bayern
kreissondertafilsausschuss
wiedergutmachung und vermögensverwaltung koblenz
landesdenkmalstelle bayern
beg.-träg.-amt münster
sondervermögens-u. raubvermögensbehörde
niedersachsen - reg.-präsident / präsident des verwaltungsgerichts hannover
niedersachsen reg.-präsident / präsident des verw. bezirks
ksha berensenbrück
hauptbetreuungsstelle
landschaftsverband bayern
r.a. mittelbach
düsseldorfer beauftragter
regionalverwaltungsbehörde für verwaltungsrecht und verbraucherschutz münchen
st. h. 2088
wd. mondelbaum
h.a. 4304
landeskommission für heimatvertriebene
niedersachsen - präsident / braunschweig
st.h. 735 g
kroio lindau
kreibsonderhilfsausschub
aurich / oostfriese
bayer. reg.
reg.-präs. - arnsberg
lva jüdorff
k4m
ksha wolfsenbuttel
ksha wesermarsch kr. nordenham
niedersachsen - präsident / präsident/des verw.-bezirks osnabrück
bay. landesstelle
k 81 n
regierungsbezirk landau
kroß linder
landesbeihilfe-abt. stuttgart
regionalverwaltungsbehörde trier
st. h. 2050
posen kz
landeshericht stuttgart
e61
nürnberger amtsgruppe
an der bundeskanzlei
hauptzuschied
ksha nordden
bundesverwaltungsamt in köln
bayrisches landesamt für religionsangelegenheiten
solm
st. h. 2202 f
bundesfinanzdirektorat - west, wörthstr. 1-3, oberfinanzdirektion köln: röntgenplatz 2, 50668 köln
k.61a
sondervermögens-u. bovverwaltung
25.07.1969 köln
st. h. 1270 f
regionalverwaltungsgericht frankfurt am main
r.a. coenen
augsburg (mf.)
käl
landesarchiv münster
köln, riehler pl.2, 50935 köln
ksha veckta
ksha schauburg-lippe
sondervermögensamt köln
bundeskartei
neuwied
statistisches landesamt nordrhein-westfalen, düsseldorf 1, postfach 1105
ansbet. bundeskartei
bezirksamt von neustadt 118696
1223
niedersachsen-präsident / präsident des nervw. bezirks
regionalstelle köln für westdeutschland
regionalamt fürstenberg (meckl.)
landesamt für karlsruher zentrale für norddeutschland
vestmuhtlich dolly
st. h. 2847 e
v. reichsgericht köln
units restitution office, london
st.h. 940 h
kreissozialhilfsausschuss blankenburg (brit. zone)
ksha syke
niedersachsen-präsident / präsidentenamt / vermögensverwaltung
stiftung lebenshilfe
st. h. 203 w
st, h. 2980 st.
bayerisches staatsministerium für wiedergutmachung und verfolgtenhilfe
st. h. 1400 sch
e 4334
an bundeskartei
rheinland-pfalz und vereinigten nachkommenschaften
united restitution office, frankfurt (m), grünburgweg 119
bundeskär
st. h. 202 a
komo
münchen, pr. müller
ansbetretten des bundesarchivs
annen
yv
f.w. becker, amburg
aegypten (welt)
südwestdeutsches zentrum für ns-opferhilfe
bhf-vb4
b 541 c 179
niedersachsen - reg.-präsident / präsidenten der merkmale
kölner büro
b 1609 d2 1438 d1 440 e 8547 f 1797
kreissozialhilfeausschub
berlin-halensee
st. h. 3091 m
lva
frankfurt-/m.
büttel
kreissozialamt colle/lend
bmf bonn
kreissonderhilfiausschuss
sammelstelle ab
adlershtein & blaschke, düsseldorf, beethovenstr. 12
nenstadt/weinstr.
dudorf
s. schreiben bfa - berlin / rp - darmstadt
st. h. 6818
reichsverwaltungsgericht berlin
kreissozialamt hild. marb.
sachbearbeitung für bez. reg.
generallizenzdirektion; service-center köln
niedersachsen-präsident / präsident der landesregierung
sozialbehörde - hamburg
lambersdorf
sondervermögens- und bauernwaltung
sondervermögens-u. bevollmächtigung
bielefeld
regionalverwaltungsgericht münchen und versicherungsverwaltungen
köln / am rudolfshaus
landeszentrale für die vergütung
der reg.prsä.detmöl dez.56
bayrisches verwaltungsamt
bhf, vb3
niedersachsenpräsident präsident des verw.-bezirks oldenburg/old.
kreisverwaltung schleiden wiedergutmachungssamt
tr. bayerisches tr. 11
kreissozialhilfsschüle gifhorn
kreissozialamt minden
jva
st. h. 1733 t
regierungsbezirk neustadt a.d. wein
bundesk.
rheinland-pfälzische landesstelle für die wiedergutmachung
regierungsbezirksamt r.pfalz-berlin
bayrisches haftbescheid
königreich-preußische behörde berlin
landesjustizverwaltung, stuttgart
legal aid department
schw münchen 2, arcisstraße 11
deutscher kulturbund
5124
neustadt neustadt
juden.nat.ponds, bln.
nolm
a 543 c 2287 d3 541 e 4381 f 737
reg.-präsident / präsident der verw.-bezirksstelle göttingen
kreisaußerhilfsausschuss
bundesskelle
united rest.office frfm.
o. staatsanwalt köln
tr. bayerisches verfolgungsausschuss
kreissozialhilfesausschuss watenstedt-salzgitter
niedersachsen - reg.-präsident / präsident des verw.-bezirks aurich
tr. 1
landesamt für vertriebene 75 karlsruhe bahnhoofplatz 14
bayrisches gau
berlin / stiftung
niedersachsen-präsident / präsident des verwaltungsgerichtshofs aurich
kreissozialamt syke
elsa pappenheim, walter joachimsthal u.a.
landsederamt münchen ii
reg.-präsident / präsident des niedersachsen
regierungsbezirk neustadt a.d. weinstr.
ua
düsseldorfer versicherungsanstalt
st.h. 265 k
kreissozialamt brak/wesermarsch
bu. verw. amt
r81m
d1 3687 d2 7997 d3 460
der restitutionspresident
köln, riehler pl. 2, 5000 köln 1
pävorisches landes-registratur
düsseldorfer entschädigungspräsident
deutsche rechtsiverts, naumburg
neustadt ludwigshafen a. rh.
kreisonderrhilfsausschuss
w.g.eb.berlin
niedersachsen / reg.-präsident / präsident des verw.-bezirks oldenburg (oldb)
kreissonderhilfesausschübe
bezirksamt von neustadt a. d. weinstr. für wiedergutmachung
roßn
wiedergutmachungsaamt koblenz
ansgl. amt frankfurt/m
reg.-präsident / präsident des mernw-bezirks
c 1159 d1 524 d2 1695 d3 619 e 2764 f 468
united restitution office, frankfurt/m
tr. isch. landesverwaltungsamt münchen ii
st. h. 6681 b
regierungsbezirk neustadt a. w.
schmidth
landesherikammer
b.f.a. berlin
bayer. schreibst.
ght
gdański
waisenstädter-salzgitter
reg.-präsident / präsident des verw.-bezirksamt hannover
doppelmedung
wesel, tickingstr.14
oran
w. landesreg. wien
regierungsbezirk potsdam
weinstock
ansbach (welf.)
landesamt für verbraucherschutz und lebensmittelsicherheit
a.d.i.v.a. bureau de restitution, paris 8
bmf - vt4
landgericht münchen
röm
st. h. 2944 sch
rheinland-pfalz und verwalteter verwaltungsbezirk für wiedergutmachung berlin
reichs-pfandkammer berlin
st. h. 2124
entschädigungsbehörde für wiedergutmachung und verfolgte verwaltungs- und wirtschaftskörperschaften
nabers verfolgten
dannenberg(elbe)
sondervermögens-u. bäuerewartung
tra nw brd
ksha linge
regionalverwaltungsbezirk wien
a 691 läuft in karlsruhe gesondert als originaler antrag – schaden am leben nach landesamt für die wiedergutmachung karlsruhe
bva, köln
königskamp
doppelmeldung hannover koblenz
baum
niedersachsen - präsident / präsident des verw.-bezirks osnabrück
ireis lindau
sondervermögens- und baufondsverwaltung
sozial-gericht berlin
regierung düsseldorf (1951)
regierung amberg
d2 967 e 7124
karlsruhe aussenstelle freiburg/brsg.
hohen kommissar der vereinten nationen für flüchtlinge
regionalverwaltungsgericht münchen und verwalteter vormögen
landkreis goslar
ag eschwege
landkreis grafschaft gooya
stuttgart feststellungsbescheid
reg.-präsident / präsident des vewc-bezirks hannover
bundesokartei
stadtscn. dortmund
tr. deutsches reichsarchiv
landesamt für vertriebene kulturarbeit
bayrisches tr.-amt
st.h.1992 w
bayisches landesamt
bayrische kultusministerium
bayerisches sozialministerium
tr. landesverwaltungsamt münchen ii, abt. 11
haltestelle
spräsident
niedersachsen / reg.-präsident / passau
ksha celle (hamororer)
ksha eimbek
sondervermögens- und bauförderungsbehörde
behörde für wien und vertriebene

# Swapping out single Tokens with a match distance of 1

In [35]:
def office_token_set(series):
    tokens = set()
    cleaned = (
        series.fillna("")
        .astype(str)
        .str.lower()
        .str.replace(r"\n", " ", regex=True)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )
    for name in cleaned:
        tokens.update(token for token in re.findall(r"\b\w+\b", name, flags=re.UNICODE)
            if not token.isdigit())
    return tokens

csv_tokens = office_token_set(df_csv["Transkription Compensation Office "].dropna().apply(remove_punctuation).apply(remove_linebreak))
json_tokens = office_token_set(df_json_filtered["norm_office"])

print(f"csv_tokens: {len(csv_tokens)}")
print(f"json_tokens: {len(json_tokens)}")

csv_tokens: 359
json_tokens: 10692

In [36]:
for t in csv_tokens:
    if len(t) == 3:
        print(t)

dez
ist
ems
und
amt
ofd
reg
süd
etc
das
lrb
hdt
vb4
str
der
fin
des
min
die
für
abt
neu
bad

In [37]:
csv_tokens_by_len = defaultdict(list)
for token in csv_tokens:
    if len(token) >= 3:
        csv_tokens_by_len[len(token)].append(token)

json_to_csv_distance1_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue

    candidate_tokens = (
        csv_tokens_by_len[len(json_token) - 1]
        + csv_tokens_by_len[len(json_token)]
        + csv_tokens_by_len[len(json_token) + 1]
    )

    matches_dist1 = [csv_token for csv_token in candidate_tokens if distance(json_token, csv_token) == 1]
    if matches_dist1:
        json_to_csv_distance1_map[json_token] = sorted(set(matches_dist1))

single_token_matches_dist1_len3 =sorted(
    [item for item in json_to_csv_distance1_map.items() if len(item[1]) == 1],
    key=lambda item: len(item[0])
)

print(len(single_token_matches_dist1_len3))
single_token_matches_dist1_len3

1004

[('re', ['reg']),
 ('eg', ['reg']),
 ('lr', ['lrb']),
 ('b4', ['vb4']),
 ('dr', ['der']),
 ('fr', ['für']),
 ('tr', ['str']),
 ('da', ['das']),
 ('di', ['die']),
 ('er', ['der']),
 ('ad', ['bad']),
 ('dt', ['hdt']),
 ('vb', ['vb4']),
 ('ba', ['bad']),
 ('of', ['ofd']),
 ('bd', ['bad']),
 ('ht', ['hdt']),
 ('hd', ['hdt']),
 ('dz', ['dez']),
 ('as', ['das']),
 ('mt', ['amt']),
 ('mi', ['min']),
 ('sr', ['str']),
 ('rg', ['reg']),
 ('rb', ['lrb']),
 ('nu', ['neu']),
 ('bah', ['bad']),
 ('rad', ['bad']),
 ('brd', ['bad']),
 ('stg', ['str']),
 ('ddr', ['der']),
 ('bav', ['bad']),
 ('lab', ['lrb']),
 ('bes', ['des']),
 ('old', ['ofd']),
 ('bay', ['bad']),
 ('lüd', ['süd']),
 ('ojd', ['ofd']),
 ('rbg', ['reg']),
 ('hss', ['hess']),
 ('xes', ['des']),
 ('vc4', ['vb4']),
 ('per', ['der']),
 ('her', ['der']),
 ('lre', ['lrb']),
 ('lro', ['lrb']),
 ('erb', ['lrb']),
 ('ref', ['reg']),
 ('oed', ['ofd']),
 ('rog', ['reg']),
 ('ung', ['und']),
 ('opd', ['ofd']),
 ('diö', ['die']),
 ('dat', ['das']),
 ('v84', ['vb4']),
 ('bod', ['bad']),
 ('wie', ['die']),
 ('db4', ['vb4']),
 ('crb', ['lrb']),
 ('sta', ['str']),
 ('rep', ['reg']),
 ('ber', ['der']),
 ('vbh', ['vb4']),
 ('lüb', ['lrb']),
 ('bie', ['die']),
 ('ub4', ['vb4']),
 ('läb', ['lrb']),
 ('and', ['und']),
 ('sod', ['süd']),
 ('kst', ['ist']),
 ('dcr', ['der']),
 ('bez', ['dez']),
 ('vba', ['vb4']),
 ('rig', ['reg']),
 ('öst', ['ist']),
 ('wür', ['für']),
 ('bar', ['bad']),
 ('ier', ['der']),
 ('amf', ['amt']),
 ('kln', ['köln']),
 ('eb4', ['vb4']),
 ('stm', ['str']),
 ('köl', ['köln']),
 ('rug', ['reg']),
 ('wst', ['ist']),
 ('bam', ['bad']),
 ('bau', ['bad']),
 ('feg', ['reg']),
 ('abh', ['abt']),
 ('lkb', ['lrb']),
 ('tür', ['für']),
 ('uni', ['und']),
 ('erw', ['verw']),
 ('prs', ['präs']),
 ('for', ['für']),
 ('dme', ['die']),
 ('beg', ['reg']),
 ('stl', ['str']),
 ('keg', ['reg']),
 ('ami', ['amt']),
 ('end', ['und']),
 ('dhe', ['die']),
 ('stv', ['str']),
 ('fun', ['fin']),
 ('kad', ['bad']),
 ('v34', ['vb4']),
 ('peg', ['reg']),
 ('vrw', ['verw']),
 ('har', ['harz']),
 ('lfd', ['ofd']),
 ('lra', ['lrb']),
 ('wes', ['des']),
 ('hdi', ['hdt']),
 ('abg', ['abt']),
 ('hdm', ['hdt']),
 ('baf', ['bad']),
 ('stf', ['str']),
 ('ovd', ['ofd']),
 ('mit', ['min']),
 ('mii', ['min']),
 ('efd', ['ofd']),
 ('rea', ['reg']),
 ('wtr', ['str']),
 ('hdn', ['hdt']),
 ('ger', ['der']),
 ('ofo', ['ofd']),
 ('rey', ['reg']),
 ('mün', ['min']),
 ('bak', ['bad']),
 ('cas', ['das']),
 ('ofg', ['ofd']),
 ('ord', ['ofd']),
 ('ofr', ['ofd']),
 ('ost', ['ist']),
 ('fln', ['fin']),
 ('vt4', ['vb4']),
 ('off', ['ofd']),
 ('vd4', ['vb4']),
 ('vby', ['vb4']),
 ('okd', ['ofd']),
 ('oft', ['ofd']),
 ('bmt', ['amt']),
 ('mad', ['bad']),
 ('ges', ['des']),
 ('kön', ['köln']),
 ('weg', ['reg']),
 ('lr8', ['lrb']),
 ('vr4', ['vb4']),
 ('lbb', ['lrb']),
 ('ofs', ['ofd']),
 ('vb3', ['vb4']),
 ('doz', ['dez']),
 ('lie', ['die']),
 ('ib4', ['vb4']),
 ('fur', ['für']),
 ('new', ['neu']),
 ('isr', ['ist']),
 ('dor', ['der']),
 ('nec', ['neu']),
 ('vew', ['verw']),
 ('ind', ['und']),
 ('krb', ['lrb']),
 ('qfd', ['ofd']),
 ('trb', ['lrb']),
 ('ubt', ['abt']),
 ('baw', ['bad']),
 ('lad', ['bad']),
 ('öln', ['köln']),
 ('verf', ['verw']),
 ('baud', ['bad']),
 ('aöln', ['köln']),
 ('jöln', ['köln']),
 ('vern', ['verw']),
 ('viel', ['kiel']),
 ('höln', ['köln']),
 ('pfaz', ['pfalz']),
 ('k8ln', ['köln']),
 ('keln', ['köln']),
 ('west', ['westf']),
 ('ivb4', ['vb4']),
 ('kölz', ['köln']),
 ('vorw', ['verw']),
 ('kölñ', ['köln']),
 ('bund', ['und']),
 ('kein', ['keine']),
 ('aemt', ['amt']),
 ('miel', ['kiel']),
 ('kess', ['hess']),
 ('vba4', ['vb4']),
 ('pras', ['präs']),
 ('präz', ['präs']),
 ('inst', ['ist']),
 ('mark', ['markt']),
 ('pris', ['präs']),
 ('ster', ['str']),
 ('neve', ['neue']),
 ('vers', ['verw']),
 ('amit', ['amt']),
 ('bona', ['bonn']),
 ('bohn', ['bonn']),
 ('halz', ['harz']),
 ('tier', ['trier']),
 ('uöln', ['köln']),
 ('eder', ['der']),
 ('k6ln', ['köln']),
 ('pres', ['präs']),
 ('stat', ['stadt']),
 ('hees', ['hess']),
 ('verm', ['verw']),
 ('hcss', ['hess']),
 ('palz', ['pfalz']),
 ('merw', ['verw']),
 ('361v', ['36iv']),
 ('wist', ['ist']),
 ('samt', ['amt']),
 ('vcrw', ['verw']),
 ('amth', ['amt']),
 ('mess', ['hess']),
 ('amnt', ['amt']),
 ('bayr', ['bayer']),
 ('k3ln', ['köln']),
 ('peer', ['leer']),
 ('bist', ['ist']),
 ('patz', ['platz']),
 ('m8in', ['min']),
 ('trer', ['trier']),
 ('bann', ['bonn']),
 ('wess', ['hess']),
 ('k5ln', ['köln']),
 ('kiln', ['köln']),
 ('vero', ['verw']),
 ('amts', ['amt']),
 ('hund', ['und']),
 ('lecr', ['leer']),
 ('seer', ['leer']),
 ('pflz', ['pfalz']),
 ('nöln', ['köln']),
 ('brak', ['brake']),
 ('falz', ['pfalz']),
 ('bönn', ['bonn']),
 ('vbs4', ['vb4']),
 ('verh', ['verw']),
 ('kaln', ['köln']),
 ('born', ['bonn']),
 ('böln', ['köln']),
 ('döln', ['köln']),
 ('moin', ['min']),
 ('lnrb', ['lrb']),
 ('präf', ['präs']),
 ('less', ['hess']),
 ('ampt', ['amt']),
 ('wstf', ['westf']),
 ('amat', ['amt']),
 ('mein', ['min']),
 ('möln', ['köln']),
 ('hamt', ['amt']),
 ('oftd', ['ofd']),
 ('ness', ['hess']),
 ('manz', ['mainz']),
 ('koln', ['köln']),
 ('yerw', ['verw']),
 ('herz', ['harz']),
 ('oder', ['der']),
 ('werw', ['verw']),
 ('maiz', ['mainz']),
 ('fund', ['und']),
 ('vtb4', ['vb4']),
 ('amft', ['amt']),
 ('höss', ['hess']),
 ('fink', ['fin']),
 ('vegw', ['verw']),
 ('varw', ['verw']),
 ('völn', ['köln']),
 ('wesf', ['westf']),
 ('371v', ['37iv']),
 ('verv', ['verw']),
 ('hest', ['hess']),
 ('trir', ['trier']),
 ('plaz', ['platz']),
 ('pltz', ['platz']),
 ('köla', ['köln']),
 ('wetf', ['westf']),
 ('röln', ['köln']),
 ('frei', ['freie']),
 ('marz', ['harz']),
 ('mink', ['min']),
 ('stdt', ['stadt']),
 ('trie', ['trier']),
 ('ostr', ['str']),
 ('pfals', ['pfalz']),
 ('freib', ['freie']),
 ('versw', ['verw']),
 ('ereis', ['kreis']),
 ('frier', ['trier']),
 ('kasse', ['kassel']),
 ('neuen', ['neue']),
 ('wesff', ['westf']),
 ('westp', ['westf']),
 ('westu', ['westf']),
 ('triel', ['trier']),
 ('trher', ['trier']),
 ('neuer', ['neue']),
 ('plätz', ['platz']),
 ('stödt', ['stadt']),
 ('weste', ['westf']),
 ('tröer', ['trier']),
 ('aaden', ['baden']),
 ('westl', ['westf']),
 ('rayer', ['bayer']),
 ('mahnz', ['mainz']),
 ('nainz', ['mainz']),
 ('krois', ['kreis']),
 ('pfölz', ['pfalz']),
 ('boann', ['bonn']),
 ('präsd', ['präs']),
 ('siadt', ['stadt']),
 ('mains', ['mainz']),
 ('mäinz', ['mainz']),
 ('gelle', ['celle']),
 ('blatz', ['platz']),
 ('maina', ['mainz']),
 ('piatz', ['platz']),
 ('bayem', ['bayer']),
 ('verwo', ['verw']),
 ('glatz', ['platz']),
 ('state', ['stade']),
 ('efurt', ['erfurt']),
 ('triar', ['trier']),
 ('neues', ['neue']),
 ('plaiz', ['platz']),
 ('westi', ['westf']),
 ('bayes', ['bayer']),
 ('karte', ['kartei']),
 ('kelle', ['celle']),
 ('maine', ['mainz']),
 ('westw', ['westf']),
 ('trler', ['trier']),
 ('tríer', ['trier']),
 ('colle', ['celle']),
 ('wcstf', ['westf']),
 ('pralz', ['pfalz']),
 ('westt', ['westf']),
 ('bayor', ['bayer']),
 ('trieß', ['trier']),
 ('neuss', ['heuss']),
 ('tries', ['trier']),
 ('payer', ['bayer']),
 ('ireis', ['kreis']),
 ('meinz', ['mainz']),
 ('staat', ['stadt']),
 ('pratz', ['platz']),
 ('plötz', ['platz']),
 ('lands', ['landes']),
 ('boyer', ['bayer']),
 ('pfalt', ['pfalz']),
 ('phalz', ['pfalz']),
 ('kölin', ['köln']),
 ('kreix', ['kreis']),
 ('remen', ['bremen']),
 ('städt', ['stadt']),
 ('pialz', ['pfalz']),
 ('plitz', ['platz']),
 ('westr', ['westf']),
 ('pfaiz', ['pfalz']),
 ('trien', ['trier']),
 ('fayer', ['bayer']),
 ('ptalz', ['pfalz']),
 ('marie', ['maria']),
 ('buyer', ['bayer']),
 ('mcinz', ['mainz']),
 ('mannz', ['mainz']),
 ('bunde', ['bundes']),
 ('mairz', ['mainz']),
 ('köln2', ['köln']),
 ('weltf', ['westf']),
 ('platt', ['platz']),
 ('pfälz', ['pfalz']),
 ('melle', ['celle']),
 ('maink', ['mainz']),
 ('essen', ['hessen']),
 ('yelle', ['celle']),
 ('mayer', ['bayer']),
 ('straß', ['straße']),
 ('trüer', ['trier']),
 ('hremen', ['bremen']),
 ('kassei', ['kassel']),
 ('maintz', ['mainz']),
 ('fragen', ['frauen']),
 ('innere', ['innern']),
 ('messen', ['hessen']),
 ('bumdes', ['bundes']),
 ('mainsz', ['mainz']),
 ('weinsr', ['weinstr']),
 ('bracke', ['brake']),
 ('aachan', ['aachen']),
 ('brakel', ['brake']),
 ('herlin', ['berlin']),
 ('triers', ['trier']),
 ('plaetz', ['platz']),
 ('dkreis', ['kreis']),
 ('aadhen', ['aachen']),
 ('trüier', ['trier']),
 ('tröier', ['trier']),
 ('linden', ['minden']),
 ('beirks', ['bezirks']),
 ('brauke', ['brake']),
 ('karten', ['kartei']),
 ('triver', ['trier']),
 ('neuied', ['neuwied']),
 ('landos', ['landes']),
 ('hessei', ['hessen']),
 ('minder', ['minden']),
 ('auvich', ['aurich']),
 ('münden', ['minden']),
 ('aremen', ['bremen']),
 ('borger', ['bürger']),
 ('kartel', ['kartei']),
 ('bürgbr', ['bürger']),
 ('sozial', ['soziale']),
 ('pfaltz', ['pfalz']),
 ('triber', ['trier']),
 ('oblenz', ['koblenz']),
 ('ländes', ['landes']),
 ('kirche', ['kirchen']),
 ('bremem', ['bremen']),
 ('beglin', ['berlin']),
 ('bremer', ['bremen']),
 ('triern', ['trier']),
 ('weinst', ['weinstr']),
 ('trieer', ['trier']),
 ('kasse1', ['kassel']),
 ('detmol', ['detmold']),
 ('munden', ['minden']),
 ('einstr', ['weinstr']),
 ('rheinl', ['rhein']),
 ('grafsh', ['grafsch']),
 ('hachen', ['aachen']),
 ('tremen', ['bremen']),
 ('ustadt', ['stadt']),
 ('etmold', ['detmold']),
 ('jenner', ['jenaer']),
 ('trirer', ['trier']),
 ('plaatz', ['platz']),
 ('berger', ['bürger']),
 ('trizer', ['trier']),
 ('göslar', ['goslar']),
 ('amburg', ['hamburg']),
 ('lindau', ['landau']),
 ('kassal', ['kassel']),
 ('gerlin', ['berlin']),
 ('menden', ['minden']),
 ('kärtei', ['kartei']),
 ('kreise', ['kreis']),
 ('kolenz', ['koblenz']),
 ('triier', ['trier']),
 ('arburg', ['warburg']),
 ('träier', ['trier']),
 ('bezirk', ['bezirks']),
 ('iplatz', ['platz']),
 ('nessen', ['hessen']),
 ('hanover', ['hannover']),
 ('dzernat', ['dezernat']),
 ('marburg', ['warburg']),
 ('munster', ['münster']),
 ('reiburg', ['freiburg']),
 ('dezerna', ['dezernat']),
 ('cattbus', ['cottbus']),
 ('jetmold', ['detmold']),
 ('nustadt', ['neustadt']),
 ('bekirks', ['bezirks']),
 ('goslari', ['goslar']),
 ('rishler', ['riehler']),
 ('werburg', ['warburg']),
 ('betmold', ['detmold']),
 ('koblens', ['koblenz']),
 ('hoblenz', ['koblenz']),
 ('neusadt', ['neustadt']),
 ('richler', ['riehler']),
 ('barburg', ['warburg']),
 ('homburg', ['hamburg']),
 ('berlins', ['berlin']),
 ('ansberg', ['arnsberg']),
 ('delmold', ['detmold']),
 ('bezirgs', ['bezirks']),
 ('hünster', ['münster']),
 ('annover', ['hannover']),
 ('kobleuz', ['koblenz']),
 ('frauend', ['frauen']),
 ('darburg', ['warburg']),
 ('weißstr', ['weinstr']),
 ('deimold', ['detmold']),
 ('auriach', ['aurich']),
 ('weimstr', ['weinstr']),
 ('defmold', ['detmold']),
 ('landesk', ['landes']),
 ('bamburg', ['hamburg']),
 ('weisstr', ['weinstr']),
 ('8arburg', ['warburg']),
 ('feiburg', ['freiburg']),
 ('detmola', ['detmold']),
 ('garburg', ['warburg']),
 ('hesssen', ['hessen']),
 ('koblanz', ['koblenz']),
 ('koblinz', ['koblenz']),
 ('bezirke', ['bezirks']),
 ('keblenz', ['koblenz']),
 ('kohlenz', ['koblenz']),
 ('benirks', ['bezirks']),
 ('arnberg', ['arnsberg']),
 ('monster', ['münster']),
 ('wazburg', ['warburg']),
 ('rnsberg', ['arnsberg']),
 ('neumark', ['neumarkt']),
 ('bundesk', ['bundes']),
 ('ko3lenz', ['koblenz']),
 ('bayerns', ['bayern']),
 ('goslars', ['goslar']),
 ('graisch', ['grafsch']),
 ('inneren', ['innern']),
 ('neuried', ['neuwied']),
 ('gratsch', ['grafsch']),
 ('kassell', ['kassel']),
 ('wernstr', ['weinstr']),
 ('dotmold', ['detmold']),
 ('weinsir', ['weinstr']),
 ('köblenz', ['koblenz']),
 ('kassels', ['kassel']),
 ('woblenz', ['koblenz']),
 ('weinsfr', ['weinstr']),
 ('koblenc', ['koblenz']),
 ('noblenz', ['koblenz']),
 ('koblonz', ['koblenz']),
 ('vermöge', ['vermögen']),
 ('sociale', ['soziale']),
 ('munchen', ['münchen']),
 ('roblenz', ['koblenz']),
 ('petmold', ['detmold']),
 ('bremens', ['bremen']),
 ('wetmold', ['detmold']),
 ('kalsruhe', ['karlsruhe']),
 ('finanzan', ['finanzen']),
 ('westfale', ['westfalen']),
 ('finanzer', ['finanzen']),
 ('landsamt', ['landesamt']),
 ('chamnitz', ['chemnitz']),
 ('bezirksx', ['bezirks']),
 ('meustadt', ['neustadt']),
 ('frnsberg', ['arnsberg']),
 ('weinsstr', ['weinstr']),
 ('arnsborg', ['arnsberg']),
 ('tobingen', ['tübingen']),
 ('kaarburg', ['saarburg']),
 ('finanzsn', ['finanzen']),
 ('desernat', ['dezernat']),
 ('neystadt', ['neustadt']),
 ('karlruhe', ['karlsruhe']),
 ('degernat', ['dezernat']),
 ('arnsoerg', ['arnsberg']),
 ('arbeitss', ['arbeits']),
 ('behördet', ['behörde']),
 ('newstadt', ['neustadt']),
 ('tübinger', ['tübingen']),
 ('hinsberg', ['heinsberg']),
 ('zentrale', ['zentral']),
 ('neussadt', ['neustadt']),
 ('präsidnt', ['präsident']),
 ('hrnsberg', ['arnsberg']),
 ('naustadt', ['neustadt']),
 ('armsberg', ['arnsberg']),
 ('heinland', ['rheinland']),
 ('prnsberg', ['arnsberg']),
 ('behörden', ['behörde']),
 ('bezirkes', ['bezirks']),
 ('karsruhe', ['karlsruhe']),
 ('wartburg', ['warburg']),
 ('kobllenz', ['koblenz']),
 ('amnsberg', ['arnsberg']),
 ('einsberg', ['heinsberg']),
 ('lezernat', ['dezernat']),
 ('freiberg', ['freiburg']),
 ('arnsperg', ['arnsberg']),
 ('ostfrsld', ['ostfrld']),
 ('aensberg', ['arnsberg']),
 ('bannover', ['hannover']),
 ('orehbahn', ['drehbahn']),
 ('paarburg', ['saarburg']),
 ('arosberg', ['arnsberg']),
 ('hensberg', ['heinsberg']),
 ('ainsberg', ['arnsberg']),
 ('töbingen', ['tübingen']),
 ('finanzon', ['finanzen']),
 ('koblentz', ['koblenz']),
 ('reinland', ['rheinland']),
 ('arnswerg', ['arnsberg']),
 ('drahbahn', ['drehbahn']),
 ('sharburg', ['saarburg']),
 ('räsident', ['präsident']),
 ('ukoblenz', ['koblenz']),
 ('göttigen', ['göttingen']),
 ('nenstadt', ['neustadt']),
 ('searburg', ['saarburg']),
 ('arnaberg', ['arnsberg']),
 ('darstadt', ['darmstadt']),
 ('bezirksy', ['bezirks']),
 ('grafisch', ['grafsch']),
 ('heustadt', ['neustadt']),
 ('stutgart', ['stuttgart']),
 ('arasberg', ['arnsberg']),
 ('helstedt', ['helmstedt']),
 ('oldeburg', ['oldenburg']),
 ('graftsch', ['grafsch']),
 ('bezirksk', ['bezirks']),
 ('beustadt', ['neustadt']),
 ('säarburg', ['saarburg']),
 ('präsidet', ['präsident']),
 ('riehlker', ['riehler']),
 ('arnßberg', ['arnsberg']),
 ('arneberg', ['arnsberg']),
 ('koblencz', ['koblenz']),
 ('koblensz', ['koblenz']),
 ('bezirksm', ['bezirks']),
 ('neustadi', ['neustadt']),
 ('soarburg', ['saarburg']),
 ('preiburg', ['freiburg']),
 ('bielfeld', ['bielefeld']),
 ('andesamt', ['landesamt']),
 ('riehlner', ['riehler']),
 ('neuwiedt', ['neuwied']),
 ('vormögen', ['vermögen']),
 ('arnsbera', ['arnsberg']),
 ('tubingen', ['tübingen']),
 ('vermöger', ['vermögen']),
 ('arnoberg', ['arnsberg']),
 ('mannover', ['hannover']),
 ('arnsherg', ['arnsberg']),
 ('sparburg', ['saarburg']),
 ('dmzernat', ['dezernat']),
 ('aunsberg', ['arnsberg']),
 ('xbezirks', ['bezirks']),
 ('baarburg', ['saarburg']),
 ('dexzernat', ['dezernat']),
 ('franzfurt', ['frankfurt']),
 ('bezirksam', ['bezirksamt']),
 ('rheinländ', ['rheinland']),
 ('arnstberg', ['arnsberg']),
 ('ministers', ['minister']),
 ('westfales', ['westfalen']),
 ('hildeheim', ['hildesheim']),
 ('bezirkamt', ['bezirksamt']),
 ('präsidenz', ['präsident']),
 ('ersorgung', ['versorgung']),
 ('aegierung', ['regierung']),
 ('finanzsen', ['finanzen']),
 ('kürlsruhe', ['karlsruhe']),
 ('verwaltet', ['verwaltete']),
 ('vermögens', ['vermögen']),
 ('landssamt', ['landesamt']),
 ('holmstedt', ['helmstedt']),
 ('bayrische', ['bayerische']),
 ('staarburg', ['saarburg']),
 ('harnsberg', ['arnsberg']),
 ('veraltete', ['verwaltete']),
 ('weinsberg', ['heinsberg']),
 ('wienbaden', ['wiesbaden']),
 ('aernsberg', ['arnsberg']),
 ('alstädter', ['altstädter']),
 ('drehrbahn', ['drehbahn']),
 ('stuttgard', ['stuttgart']),
 ('heineberg', ['heinsberg']),
 ('nordbuden', ['nordbaden']),
 ('maristrat', ['magistrat']),
 ('seaarburg', ['saarburg']),
 ('kärlsruhe', ['karlsruhe']),
 ('theinland', ['rheinland']),
 ('prasident', ['präsident']),
 ('ostereode', ['osterode']),
 ('manistrat', ['magistrat']),
 ('niesbaden', ['wiesbaden']),
 ('präsidenc', ['präsident']),
 ('schauburg', ['schaumburg']),
 ('hätefonds', ['härtefonds']),
 ('president', ['präsident']),
 ('finanzzen', ['finanzen']),
 ('karlscuhe', ['karlsruhe']),
 ('cldenburg', ['oldenburg']),
 ('beroldung', ['besoldung']),
 ('oltenburg', ['oldenburg']),
 ('regierang', ['regierung']),
 ('président', ['präsident']),
 ('arnnsberg', ['arnsberg']),
 ('osmabrück', ['osnabrück']),
 ('weinsteig', ['weinsteige']),
 ('uldenburg', ['oldenburg']),
 ('neuostadt', ['neustadt']),
 ('derzernat', ['dezernat']),
 ('hiesbaden', ['wiesbaden']),
 ('arnsoberg', ['arnsberg']),
 ('osnabruck', ['osnabrück']),
 ('kurlsruhe', ['karlsruhe']),
 ('härtfonds', ['härtefonds']),
 ('reyierung', ['regierung']),
 ('kheinland', ['rheinland']),
 ('uneustadt', ['neustadt']),
 ('nordboden', ['nordbaden']),
 ('ahrnsberg', ['arnsberg']),
 ('detzernat', ['dezernat']),
 ('karlshuhe', ['karlsruhe']),
 ('aarnsberg', ['arnsberg']),
 ('bayersche', ['bayerische']),
 ('ezirksamt', ['bezirksamt']),
 ('rogierung', ['regierung']),
 ('farnsberg', ['arnsberg']),
 ('osteroede', ['osterode']),
 ('ländesamt', ['landesamt']),
 ('freiburgi', ['freiburg']),
 ('arnswberg', ['arnsberg']),
 ('bazirksamt', ['bezirksamt']),
 ('osanabrück', ['osnabrück']),
 ('götttingen', ['göttingen']),
 ('lezirksamt', ['bezirksamt']),
 ('härtetonds', ['härtefonds']),
 ('landsesamt', ['landesamt']),
 ('bayedische', ['bayerische']),
 ('verwaltets', ['verwaltete']),
 ('bayrisches', ['bayerisches']),
 ('verwalteto', ['verwaltete']),
 ('spräsident', ['präsident']),
 ('helmsstedt', ['helmstedt']),
 ('bekirksamt', ['bezirksamt']),
 ('bosnabrück', ['osnabrück']),
 ('göttlingen', ['göttingen']),
 ('präsidenta', ['präsident']),
 ('karlshruhe', ['karlsruhe']),
 ('ayerisches', ['bayerisches']),
 ('müsseldorf', ['düsseldorf']),
 ('besirksamt', ['bezirksamt']),
 ('bayetische', ['bayerische']),
 ('weinsteine', ['weinsteige']),
 ('sarbrücken', ['saarbrücken']),
 ('bexirksamt', ['bezirksamt']),
 ('osnaubrück', ['osnabrück']),
 ('bäzirksamt', ['bezirksamt']),
 ('präsident7', ['präsident']),
 ('zuständige', ['zuständig']),
 ('sayerische', ['bayerische']),
 ('gildesheim', ['hildesheim']),
 ('mayerische', ['bayerische']),
 ('landessamt', ['landesamt']),
 ('verfolgten', ['verfolgte']),
 ('bayesische', ['bayerische']),
 ('weilstraße', ['weinstraße']),
 ('karlsruhes', ['karlsruhe']),
 ('registatur', ['registratur']),
 ('rheinsberg', ['heinsberg']),
 ('schäumburg', ['schaumburg']),
 ('verfolgtes', ['verfolgte']),
 ('desseldorf', ['düsseldorf']),
 ('präsidenat', ['präsident']),
 ('regierungs', ['regierung']),
 ('düsseldort', ['düsseldorf']),
 ('jüsseldorf', ['düsseldorf']),
 ('payerische', ['bayerische']),
 ('nördlicher', ['nördliche']),
 ('bayersches', ['bayerisches']),
 ('auerstraße', ['auestraße']),
 ('spinkenhof', ['sprinkenhof']),
 ('landesamts', ['landesamt']),
 ('arcistraße', ['arcisstraße']),
 ('dezirksamt', ['bezirksamt']),
 ('schaußburg', ['schaumburg']),
 ('xpräsident', ['präsident']),
 ('vorwaltete', ['verwaltete']),
 ('weimsteige', ['weinsteige']),
 ('rheinlande', ['rheinland']),
 ('woinsteige', ['weinsteige']),
 ('präsidient', ['präsident']),
 ('dusseldorf', ['düsseldorf']),
 ('landeesamt', ['landesamt']),
 ('sildesheim', ['hildesheim']),
 ('büsseldorf', ['düsseldorf']),
 ('verfolgter', ['verfolgte']),
 ('weinsteire', ['weinsteige']),
 ('bildesheim', ['hildesheim']),
 ('bézirksamt', ['bezirksamt']),
 ('weinsteigo', ['weinsteige']),
 ('ministerie', ['ministerin']),
 ('bozirksamt', ['bezirksamt']),
 ('hartefonds', ['härtefonds']),
 ('karlsruher', ['karlsruhe']),
 ('leinstraße', ['weinstraße']),
 ('hikdesheim', ['hildesheim']),
 ('verwalteta', ['verwaltete']),
 ('präsidentk', ['präsident']),
 ('weinstrabe', ['weinstraße']),
 ('bayernische', ['bayerische']),
 ('meisestraße', ['meiserstraße']),
 ('springenhof', ['sprinkenhof']),
 ('bayetisches', ['bayerisches']),
 ('düsseldorft', ['düsseldorf']),
 ('verwaltgete', ['verwaltete']),
 ('weinsstraße', ['weinstraße']),

In [38]:
unique_distance1_token_map = {
    json_token: csv_candidates[0]
    for json_token, csv_candidates in json_to_csv_distance1_map.items()
    if len(csv_candidates) == 1
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_json_filtered['CompensationOffice_token_swap'] = df_json_filtered['norm_office'].apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_json_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['norm_office'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 1004

,CompensationOffice1,MatchedOffice,MatchDistance
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,7.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,3.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,2.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,NaN,NaN
16,bundeskartei,NaN,NaN
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,3.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,NaN,NaN
20,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,6.0
21,hess staatsministerium,NaN,NaN

In [39]:
total = len(df_matches_token_swap)
max_dist = int(df_matches_token_swap['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches_token_swap['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 12773 (3.64%)
MatchDistance = 1: 21254 (6.06%)
MatchDistance = 2: 11019 (3.14%)
MatchDistance = 3: 20811 (5.93%)
MatchDistance = 4: 41667 (11.88%)
MatchDistance = 5: 9178 (2.62%)
MatchDistance = 6: 23891 (6.81%)
MatchDistance = 7: 4713 (1.34%)
MatchDistance = 8: 6043 (1.72%)
MatchDistance = 9: 22343 (6.37%)
MatchDistance = 10: 3564 (1.02%)
MatchDistance = 11: 3458 (0.99%)
MatchDistance = 12: 10973 (3.13%)
MatchDistance = 13: 3680 (1.05%)
MatchDistance = 14: 3331 (0.95%)
MatchDistance = 15: 2789 (0.80%)
MatchDistance = 16: 2635 (0.75%)
MatchDistance = 17: 2330 (0.66%)
MatchDistance = 18: 2849 (0.81%)
MatchDistance = 19: 15756 (4.49%)
MatchDistance = 20: 3595 (1.03%)
MatchDistance = 21: 1544 (0.44%)
MatchDistance = 22: 1526 (0.44%)
MatchDistance = 23: 20328 (5.80%)
MatchDistance = 24: 1535 (0.44%)
MatchDistance = 25: 495 (0.14%)
MatchDistance = 26: 260 (0.07%)
MatchDistance = 27: 594 (0.17%)
MatchDistance = 28: 969 (0.28%)
MatchDistance = 29: 1715 (0.49%)
MatchDistance = 30: 388 (0.11%)
MatchDistance = 31: 504 (0.14%)
MatchDistance = 32: 234 (0.07%)
MatchDistance = 33: 808 (0.23%)
MatchDistance = 34: 70 (0.02%)
MatchDistance = 35: 69 (0.02%)
MatchDistance = 36: 33 (0.01%)
MatchDistance = 37: 43 (0.01%)
MatchDistance = 38: 22 (0.01%)
MatchDistance = 39: 37 (0.01%)
MatchDistance = 40: 36 (0.01%)
MatchDistance = 41: 9 (0.00%)
MatchDistance = 42: 15 (0.00%)
MatchDistance = 43: 7 (0.00%)
MatchDistance = 44: 11 (0.00%)
MatchDistance = 45: 8 (0.00%)
MatchDistance = 46: 8 (0.00%)
MatchDistance = 47: 9 (0.00%)
MatchDistance = 48: 6 (0.00%)
MatchDistance = 49: 1 (0.00%)
MatchDistance = 50: 2 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 3 (0.00%)
MatchDistance = 53: 1 (0.00%)
MatchDistance = 54: 4 (0.00%)
MatchDistance = 55: 13 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 3 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 8 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 0 (0.00%)
MatchDistance = 64: 1 (0.00%)

In [40]:
def token_count(s):
    return len(str(s).split())

extracted_longer = sorted(
    {
        (str(a), str(b))
        for a, b in zip(df_matches_token_swap['CompensationOffice1'], df_matches_token_swap['MatchedOffice'])
        if token_count(a) > token_count(b) and str(b) != 'nan'
    },
    key=lambda item: token_count(item[0])
)

extracted_longer

[('früher koblenz', 'koblenz'),
 ('uro berlin', 'berlin'),
 ('hamburg az', 'hamburg'),
 ('umw köln', 'köln'),
 ('karl wolke', 'karlsruhe'),
 ('münchner eg', 'münchen'),
 ('neu isenburg', 'oldenburg'),
 ('ilva darmstadt', 'darmstadt'),
 ('kreis osnabrück', 'osnabrück'),
 ('bayern münchen', 'münchen'),
 ('ojj münster', 'münster'),
 ('bva hamburg', 'hamburg'),
 ('lvh hamburg', 'hamburg'),
 ('münchen beg', 'münchen'),
 ('iva hamburg', 'hamburg'),
 ('ba oldenburg', 'oldenburg'),
 ('nrw münster', 'münster'),
 ('karlsruhe freiburg', 'karlsruhe'),
 ('münchen 2', 'münchen'),
 ('stadt oldenburg', 'oldenburg'),
 ('braunschweig ii', 'braunschweig'),
 ('os nabruck', 'osnabrück'),
 ('land hessen', 'hessen'),
 ('detmold köln', 'detmold'),
 ('niedersachsen oldenburg', 'niedersachsen'),
 ('köl n', 'köln'),
 ('nürnberg a', 'arnsberg'),
 ('bayer london', 'bayern'),
 ('va hamburg', 'hamburg'),
 ('ksha oldenburg', 'oldenburg'),
 ('ksha bremen', 'bremen'),
 ('oldenburg olb', 'oldenburg'),
 ('neustadt m', 'neustadt'),
 ('k sln', 'köln'),
 ('lvh hessen', 'hessen'),
 ('lka stuttgart', 'stuttgart'),
 ('uok köln', 'köln'),
 ('darmstadt dp', 'darmstadt'),
 ('kolle land', 'koblenz'),
 ('mok köln', 'köln'),
 ('kshb goslari', 'goslar'),
 ('ksha münchen', 'münchen'),
 ('ksha lüneburg', 'lüneburg'),
 ('münchen ii', 'münchen'),
 ('hfa berlin', 'berlin'),
 ('köln düsseldorf', 'düsseldorf'),
 ('ojd berlin', 'berlin'),
 ('ksha hamburg', 'hamburg'),
 ('barburg neustadt', 'neustadt'),
 ('an stade', 'stade'),
 ('stadt v', 'stade'),
 ('könig düsseldorf', 'düsseldorf'),
 ('köln hamburg', 'hamburg'),
 ('braunschweig i', 'braunschweig'),
 ('lg mainz', 'mainz'),
 ('darmstadt mainz', 'darmstadt'),
 ('lg koblenz', 'koblenz'),
 ('oed freiburg', 'freiburg'),
 ('neustadt 484945', 'neustadt'),
 ('lka mainz', 'mainz'),
 ('mainz wiesbaden', 'wiesbaden'),
 ('ksha händersheim', 'hildesheim'),
 ('ksha harburg', 'saarburg'),
 ('regierung braunschweig', 'braunschweig'),
 ('bfh berlin', 'berlin'),
 ('rp düsseldorf', 'düsseldorf'),
 ('j cuttigart', 'stuttgart'),
 ('lg darmstadt', 'darmstadt'),
 ('karlsruhe baden', 'karlsruhe'),
 ('ovd köln', 'köln'),
 ('münchen bürgbr', 'münchen'),
 ('hva hamburg', 'hamburg'),
 ('aurich oetfr', 'aurich'),
 ('münchen k81n', 'münchen'),
 ('düsseldorfer gericht', 'düsseldorf'),
 ('köln saarbrücken', 'saarbrücken'),
 ('bayern neustadt', 'neustadt'),
 ('oed berlin', 'berlin'),
 ('saarburger vogt', 'saarburg'),
 ('eb düsseldorf', 'düsseldorf'),
 ('ksha bremenhaven', 'bremerhaven'),
 ('opd berlin', 'berlin'),
 ('bfz berlin', 'berlin'),
 ('hva köln', 'köln'),
 ('jörns hessen', 'hessen'),
 ('stuttgart mainz', 'stuttgart'),
 ('regoldenburg oldb', 'oldenburg'),
 ('ksha stuttgart', 'stuttgart'),
 ('hessen neu', 'hessen'),
 ('s arburg', 'saarburg'),
 ('bezirksamt berlin', 'bezirksregierung'),
 ('oldenburg oldbg', 'oldenburg'),
 ('braunschweig hannover', 'braunschweig'),
 ('aurich niedersachsen', 'niedersachsen'),
 ('ig berlin', 'berlin'),
 ('köln a', 'köln'),
 ('lka darmstadt', 'darmstadt'),
 ('aurich ostf', 'aurich'),
 ('kreis limburg', 'freiburg'),
 ('oldenburg oldb', 'oldenburg'),
 ('stadt promerhaven', 'bremerhaven'),
 ('neustadt 484076', 'neustadt'),
 ('ag hannover', 'hannover'),
 ('neustadt w', 'neustadt'),
 ('rp köln', 'köln'),
 ('nds braunschweig', 'braunschweig'),
 ('münchen 91519', 'münchen'),
 ('sozialamt düsseldorf', 'düsseldorf'),
 ('stadt stuttgart', 'stuttgart'),
 ('oftd köln', 'köln'),
 ('ksha goslar', 'goslar'),
 ('an braunschweig', 'braunschweig'),
 ('mainz a', 'mainz'),
 ('mai nz', 'mainz'),
 ('berlin platz', 'berlin'),
 ('ofd düsseldorf', 'düsseldorf'),
 ('brauns hweig', 'braunschweig'),
 ('lvg hamburg', 'hamburg'),
 ('ansl amtdüsseldorf', 'düsseldorf'),
 ('schwab münchen', 'münchen'),
 ('stl desheim', 'hildesheim'),
 ('ofg hannover', 'hannover'),
 ('oft karlsruhe', 'karlsruhe'),
 ('wiener landesregierung', 'bezirksregierung'),
 ('braunschweig 19', 'braunschweig'),
 ('berlin köln', 'berlin'),
 ('bayer reg', 'bayern'),
 ('braunschweig stadt', 'braunschweig'),
 ('saarbrücken düsseldorf', 'saarbrücken'),
 ('braunschweig 1g', 'braunschweig'),
 ('oft köln', 'köln'),
 ('lva hamburg', 'hamburg'),
 ('tr neustadt', 'neustadt'),
 ('kshabraunschweig i', 'braunschweig'),
 ('niedersachsen braunschweig', 'niedersachsen'),
 ('niedersachsen hannover', 'niedersachsen'),
 ('bayern köln', 'bayern'),
 ('rhb berlin', 'berlin'),
 ('oed koblenz', 'koblenz'),
 ('saarburg trier', 'saarburg'),
 ('b münchen', 'münchen'),
 ('ofo berlin', 'berlin'),
 ('bayrisches regierung', 'bezirksregierung'),
 ('bza berlin', 'berlin'),
 ('hesse neu', 'hessen'),
 ('stadt bremerhaven', 'bremerhaven'),
 ('oft hannover', 'hannover'),
 ('sha hildesheim', 'hildesheim'),
 ('betrifft regierung', 'bezirksregierung'),
 ('träger koblentz', 'koblenz'),
 ('blka münchen', 'münchen'),
 ('bayern dt', 'bayern'),
 ('anstalt saarburg', 'saarburg'),
 ('köln detmold', 'detmold'),
 ('oldenburg stadt', 'oldenburg'),
 ('ksh hammover', 'hannover'),
 ('ksha münster', 'münster'),
 ('hannover köln', 'hannover'),
 ('darmstadt stadt', 'darmstadt'),
 ('wega berlin', 'berlin'),
 ('bfa berlin', 'berlin'),
 ('lg düsseldorf', 'düsseldorf'),
 ('lwa düsseldorf', 'düsseldorf'),
 ('neustadt neubist', 'neustadt'),
 ('agr münchen', 'münchen'),
 ('köln lv', 'köln'),
 ('lkamt düsseldorf', 'düsseldorf'),
 ('hessen alt', 'hessen'),
 ('münchen i', 'münchen'),
 ('okg münchen', 'münchen'),
 ('liva münster', 'münster'),
 ('oft berlin', 'berlin'),
 ('lka niesbaden', 'wiesbaden'),
 ('har nover', 'hannover'),
 ('tr münchen', 'münchen'),
 ('ksha wiesbaden', 'wiesbaden'),
 ('hess lka', 'hessen'),
 ('k6 n', 'köln'),
 ('berlin neustadt', 'neustadt'),
 ('mainz berlin', 'berlin'),
 ('niedersachsen osnabrück', 'niedersachsen'),
 ('ksa goslar', 'goslar'),
 ('k8m düsseldorf', 'düsseldorf'),
 ('ksh braunschweig', 'braunschweig'),
 ('lg würzburg', 'lüneburg'),
 ('ksha braunschweig', 'braunschweig'),
 ('landkreis braunschweig', 'braunschweig'),
 ('nba lüneburg', 'lüneburg'),
 ('ofd köln', 'köln'),
 ('ksha augsburg', 'saarburg'),
 ('darmstadt eg', 'darmstadt'),
 ('ba lüneburg', 'lüneburg'),
 ('bayerische staatsregierung', 'bezirksregierung'),
 ('hannover lt', 'hannover'),
 ('reg arnsberg', 'arnsberg'),
 ('lka düsseldorf', 'düsseldorf'),
 ('rp arnswerg', 'arnsberg'),
 ('köln münchen', 'münchen'),
 ('lg köln', 'köln'),
 ('bayer verw', 'bayern'),
 ('nva hamburg', 'hamburg'),
 ('gob berliner', 'berlin'),
 ('niedersachsenen präsident', 'niedersachsen'),
 ('saarburg mainz', 'saarburg'),
 ('saarburg düsseldorf', 'düsseldorf'),
 ('ofd berlin', 'berlin'),
 ('lya hamburg', 'hamburg'),
 ('bayer berlin', 'berlin'),
 ('oft köl', 'köln'),
 ('saarburg berlin', 'saarbrücken'),
 ('ksha nordern', 'hannover'),
 ('rp arnsberg', 'arnsberg'),
 ('hessen da', 'hessen'),
 ('w köln', 'köln'),
 ('lvf hamburg', 'hamburg'),
 ('düsseldorf köln', 'düsseldorf'),
 ('stuttgart s', 'stuttgart'),
 ('qfd köln', 'köln'),
 ('ra reppenhagen', 'bremerhaven'),
 ('an bremen', 'bremen'),
 ('hannover l', 'hannover'),
 ('dza zehlendorf', 'düsseldorf'),
 ('bayern düsseldorf', 'düsseldorf'),
 ('ofd münchen', 'münchen'),
 ('bonn stadt', 'neustadt'),
 ('rp hildesheim', 'hildesheim'),
 ('hessen nu', 'hessen'),
 ('bezirksamt mainz', 'bezirksregierung'),
 ('lva berlin', 'berlin'),
 ('bezirksamt würzburg', 'bezirksregierung'),
 ('ek karlsruhe', 'karlsruhe'),
 ('wiesbaden luhe', 'wiesbaden'),
 ('ig münchen', 'münchen'),
 ('lea berlin', 'berlin'),
 ('oldeburg oldb', 'oldenburg'),
 ('lüneburg land', 'lüneburg'),
 ('an niedersachsen', 'niedersachsen'),
 ('ag nürnberg', 'arnsberg'),
 ('ksha darmstadt', 'darmstadt'),
 ('münchen 14219', 'münchen'),
 ('bezirksregierung bmf', 'bezirksregierung'),
 ('amt köln', 'köln'),
 ('kiel t51', 'kiel'),
 ('st hannover', 'hannover'),
 ('ksha berlin', 'berlin'),
 ('düsseldorf westf', 'düsseldorf'),
 ('iva düsseldorf', 'düsseldorf'),
 ('an hildesheim', 'hildesheim'),
 ('kshb braunschweig', 'braunschweig'),
 ('oed köln', 'köln'),
 ('münchen eg', 'münchen'),
 ('k8 n', 'köln'),
 ('nds hannover', 'hannover'),
 ('oftd münchen', 'münchen'),
 ('arnsberg münster', 'arnsberg'),
 ('neustadt 483556', 'neustadt'),
 ('hamburger amt', 'hamburg'),
 ('kg berlin', 'berlin'),
 ('lvd hamburg', 'hamburg'),
 ('uoy köln', 'köln'),
 ('oed münchen', 'münchen'),
 ('k6 ln', 'köln'),
 ('neustadt pk', 'neustadt'),
 ('lüneburg straar', 'lüneburg'),
 ('olg münchen', 'münchen'),
 ('arnsberg köln', 'arnsberg'),
 ('nrw tüssleldorf', 'düsseldorf'),
 ('bfpa berlin', 'berlin'),
 ('ksha aurich', 'aurich'),
 ('bsha oldenburg', 'oldenburg'),
 ('ksha hildesheim', 'hildesheim'),
 ('hann lüb', 'hannover'),
 ('düsseldorf hamm', 'düsseldorf'),
 ('lva oldenburg', 'oldenburg'),
 ('köln münster', 'münster'),
 ('ofg köln', 'köln'),
 ('amt bremen', 'bremen'),
 ('oft koln', 'köln'),
 ('lva düsseldorf', 'düsseldorf'),
 ('awk köln', 'köln'),
 ('berlin niedersachsen', 'niedersachsen'),
 ('cva düsseldorf', 'düsseldorf'),
 ('olg köln', 'köln'),
 ('lg hamburg', 'hamburg'),
 ('hamburg 1', 'hamburg'),
 ('kreis lüneburg', 'lüneburg'),
 ('eb münchen', 'münchen'),
 ('stuttgart freiburg', 'stuttgart'),
 ('dwd berlin', 'berlin'),
 ('lg stuttgart', 'stuttgart'),
 ('maine niedersachsen', 'niedersachsen'),
 ('noblenz 225511', 'koblenz'),
 ('koblenz 395070', 'koblenz'),
 ('ovd berlin', 'berlin'),
 ('main z', 'mainz'),
 ('zentral registrierung', 'bezirksregierung'),
 ('hannover löd', 'hannover'),
 ('ham pr', 'hamburg'),
 ('lg salzburg', 'saarburg'),
 ('ksha peine', 'peine'),
 ('neu stadt', 'neustadt'),
 ('einst berlin', 'berlin'),
 ('düsseldorf münchen', 'düsseldorf'),
 ('olg stuttgart', 'stuttgart'),
 ('bfv berlin', 'berlin'),
 ('düsseldorfer schule', 'düsseldorf'),
 ('k5 n', 'köln'),
 ('lka wiesbaden', 'wiesbaden'),
 ('dva duesseldorf', 'düsseldorf'),
 ('braunschweig land', 'braunschweig'),
 ('bzk mainz', 'mainz'),
 ('köln arnsberg', 'arnsberg'),
 ('ksha osnabrück', 'osnabrück'),
 ('ksha düsseldorf', 'düsseldorf'),
 ('ofs berlin', 'berlin'),
 ('niedersachsen präsident', 'niedersachsen'),
 ('hamburg köln', 'hamburg'),
 ('ksha gandersheim', 'hildesheim'),
 ('lg münchen', 'münchen'),
 ('b köln', 'köln'),
 ('kiel niedersachsen', 'niedersachsen'),
 ('aha hamburg', 'hamburg'),
 ('braunschweig mascherode', 'braunschweig'),
 ('rb detmold', 'detmold'),
 ('land bayern', 'bayern'),
 ('bva köln', 'köln'),
 ('lva münchen', 'münchen'),
 ('karl wilhelm', 'karlsruhe'),
 ('hessen dp', 'hessen'),
 ('kshax niedersachsen', 'niedersachsen'),
 ('stadt desseldorf', 'düsseldorf'),
 ('lg hannover', 'hannover'),
 ('münchen ost', 'münchen'),
 ('ksha helmsstedt', 'helmstedt'),
 ('lüneburg stadt', 'lüneburg'),
 ('münster w', 'münster'),
 ('neustadt trier', 'neustadt'),
 ('lvva hamburg', 'hamburg'),
 ('nva düsseldorf', 'düsseldorf'),
 ('neu ischad', 'neustadt'),
 ('führer koblenz', 'koblenz'),
 ('rp darmstadt', 'darmstadt'),
 ('lvii hamburg', 'hamburg'),
 ('ksha niedersachsen', 'niedersachsen'),
 ('trier saarburg', 'saarburg'),
 ('afw köln', 'köln'),
 ('ovd düsseldorf', 'düsseldorf'),
 ('bla münchen', 'münchen'),
 ('ka hamburg', 'hamburg'),
 ('oft münster', 'münster'),
 ('tries neustadt', 'neustadt'),
 ('stadt hildesheim', 'hildesheim'),
 ('bayerische landesregierung', 'bezirksregierung'),
 ('k öln', 'köln'),
 ('lg berlin', 'berlin'),
 ('wga berlin', 'berlin'),
 ('reg braunschweig', 'braunschweig'),
 ('bfj berlin', 'berlin'),
 ('fidos münchen', 'münchen'),
 ('referat arnsberg', 'arnsberg'),
 ('barb burg', 'freiburg'),
 ('stuttgart bayern', 'stuttgart'),
 ('amt bery', 'arnsberg'),
 ('oldenburg old', 'oldenburg'),
 ('lka münchen', 'münchen'),
 ('niedersachsen präsidium', 'niedersachsen'),
 ('ofo köln', 'köln'),
 ('soza münchen', 'münchen'),
 ('hamburg i', 'hamburg'),
 ('dva hamburg', 'hamburg'),
 ('fried saarburg', 'saarburg'),
 ('boyer london', 'bayern'),
 ('afw essen', 'hessen'),
 ('land berlin', 'berlin'),
 ('der regierung', 'bezirksregierung'),
 ('koblenz saarburg', 'saarburg'),
 ('wiesbadener kreis', 'wiesbaden'),
 ('olg koblenz', 'koblenz'),
 ('haupt berlin', 'berlin'),
 ('ksh hannover', 'hannover'),
 ('stuttgart i', 'stuttgart'),
 ('braunschweig dep', 'braunschweig'),
 ('reg oldenburg', 'oldenburg'),
 ('la hannover', 'hannover'),
 ('uni marburg', 'saarburg'),
 ('hannover fund', 'hannover'),
 ('trier koblenz', 'koblenz'),
 ('ksh stade', 'stade'),
 ('der regierungso', 'bezirksregierung'),
 ('braun schweig', 'braunschweig'),
 ('öl n', 'köln'),
 ('aurich osnabrück', 'osnabrück'),
 ('trion neustadt', 'neustadt'),
 ('neu isaadt', 'neustadt'),
 ('aegyung aensberg', 'arnsberg'),
 ('düsseldorf saarbrücken', 'saarbrücken'),
 ('düsseldorfer kartei', 'düsseldorf'),
 ('bpa berlin', 'berlin'),
 ('lva münster', 'münster'),
 ('ksa hannover', 'hannover'),
 ('stuttgart et5770', 'stuttgart'),
 ('berlin hamburg', 'hamburg'),
 ('hamburg land', 'hamburg'),
 ('mainz neustadt', 'neustadt'),
 ('oftd berlin', 'berlin'),
 ('ksha würzburg', 'saarburg'),
 ('eb koblenz', 'koblenz'),
 ('neustadt 47825', 'neustadt'),
 ('neu neustadt', 'neustadt'),
 ('lka hannover', 'hannover'),
 ('neustadt rwkv', 'neustadt'),
 ('ra munster', 'münster'),
 ('in detmold', 'detmold'),
 ('5510 saarburg', 'saarburg'),
 ('köln lva', 'köln'),
 ('stadt düsseldorf', 'düsseldorf'),
 ('regierungspräsidium fürth württ', 'regierungspräsidium darmstadt'),
 ('kreisaußerhilfsausschuss hildesheim stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss göttlingen stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungspräsidium münchen mfv', 'regierungspräsident münster'),
 ('regierung posen meld', 'regierungspräsident köln'),
 ('stadt hamm westf', 'stadt hannover'),
 ('kreissozialhilfsausschuss hameln pyrmont',
  'kreissonderhilfsausschuß delmenhorst'),
 ('r p köln', 'köln'),
 ('freiburg br harzstr', 'freiburg br'),
 ('entschädigungsbehörde regierungspräsidium münster',
  'entschädigungsbehörde münster'),
 ('oberfinanzdirektion ofd chemnitz', 'oberfinanzdirektion freiburg'),
 ('kreisondertafsausschuss osterode harz',
  'kreissonderhilfsausschuß delmenhorst'),
 ('searburg rheinland pfalz', 'rheinland pfalz'),
 ('kreisondesonderhilfsausschuss stadt hameln',
  'kreissonderhilfsausschuß delmenhorst'),
 ('entschädigungsakten eb hannover', 'entschädigungsamt bremerhaven'),
 ('ksh hammover stadt', 'hannover stadt'),
 ('doppel meldung wiesbaden', 'hessen wiesbaden'),
 ('bayer landesentschädigungsamt münchen', 'bayer landesentschädigungsamt'),
 ('kreissonderhilfsausschuss schaub lippe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss osterode harz',
  'kreissonderhilfsausschuß delmenhorst'),
 ('neustadt d hdt', 'neustadt'),
 ('regierungspräsidium m ögl', 'regierungspräsident köln'),
 ('regional president detmold', 'regierungspräsident detmold'),
 ('kreissonderhilfsausschuss gelle land',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss hildesheim marienenburg',
  'kreissonderhilfsausschuß delmenhorst'),
 ('entscheidungsbehörde in koblenz', 'entschädigungsbehörde köln'),
 ('kreisonderrhilfsausschuss brauke wesermarsch',
  'kreissonderhilfsausschuß delmenhorst'),
 ('bayerisches namesdienst verfolgtenamt',
  'bayerisches landesentschädigungsamt'),
 ('bergedorfer gericht düsseldorf', 'bezirksregierung düsseldorf'),
 ('kreissozialhilfsausschuss nürnberg süd',
  'kreissonderhilfsausschuß delmenhorst'),
 ('bayerische kardinalrhein westfalen', 'nordrhein westfalen'),
 ('payer i landesentschädigungsamt', 'bayer landesentschädigungsamt'),
 ('ksha osterode h', 'osterode h'),
 ('stadt des heiligen', 'stadt celle'),
 ('kreissonderhilfsausschuss hammel oy',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss winsen luhe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungsamt aachen wv', 'regierungspräsident aachen'),
 ('kreissonderhilfsschübe hild marb', 'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfeausschuss winsen luhe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss hameln pyrmont',
  'kreissonderhilfsausschuß delmenhorst'),
 ('bayerisches landesarchiv münchen', 'bayerisches landesentschädigungsamt'),
 ('v koordinierung köln', 'bezirksregierung köln'),
 ('entscheidungsberechtigte behörde köln', 'entschädigungsbehörde köln'),
 ('freiburg br karlsruhe', 'freiburg br'),
 ('hildesheim im weinstr', 'hildesheim stadt'),
 ('kreissozialhilfsausschuss göttingen stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('entschädigungsbehörde k 81', 'entschädigungsbehörde köln'),
 ('d regierungspräsidium münster', 'regierungspräsident münster'),
 ('e amt berlin', 'berlin'),
 ('kreissonderhilfsausschuss rottenburg hann',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss celle land',
  'kreissonderhilfsausschuß delmenhorst'),
 ('oberfinanzdirektion des saarlandes', 'oberfinanzdirektion saarbrücken'),
 ('kreissonderhilfsausschübe winsen luhe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ksha hildesheim st', 'hildesheim stadt'),
 ('kreisondeserhifsausschuss brake wesermarsch',
  'kreissonderhilfsausschuß delmenhorst'),
 ('einst schadensbehörde köln', 'entschädigungsbehörde köln'),
 ('kreisssonderhilfssausschuss stadt celle',
  'kreissonderhilfsausschuß delmenhorst'),
 ('vorgang an wiesbaden', 'hessen wiesbaden'),
 ('regierungspräsidium potsdam meckl', 'regierungspräsidium darmstadt'),
 ('regierungspräsidium düsseldorf weltf', 'regierungspräsident düsseldorf'),
 ('regierungspräsidium münster wf', 'regierungspräsident münster'),
 ('entsch amt berlin', 'entschädigungsamt berlin'),
 ('regierung düsseldorf lh', 'bezirksregierung düsseldorf'),
 ('en tschädigungsamt berlin', 'entschädigungsamt berlin'),
 ('bezirksamt für wiesbaden', 'darmstadt wiesbaden'),
 ('v regierungsbezirksamt koblenz', 'regierungspräsident köln'),
 ('der landesentschädigungsbehörde düsseldorf',
  'landesrentenbehörde düsseldorf'),
 ('kreissozialhilfsausschuss brake wesermarsch',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss celle stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderbehilfsausschuss alfeld leine',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ksha hildesheim stadt', 'hildesheim stadt'),
 ('kreissonderhilfsausschuss münster westf',
  'kreissonderhilfsausschuß delmenhorst'),
 ('doppelmeldung rheinland pfalz', 'rheinland pfalz'),
 ('ksha darmbrück stadt', 'osnabrück stadt'),
 ('regierungsbezirk arnsberg mfh', 'regierungspräsident arnsberg'),
 ('rp düsseldorf köln', 'düsseldorf'),
 ('darmstadt wiesbaden hannover', 'darmstadt wiesbaden'),
 ('oberfinanzdirektion xxx köln', 'oberfinanzdirektion köln'),
 ('bayrisches landesarchiv münchen', 'bayerisches landesentschädigungsamt'),
 ('regierungspräsidium 20 21', 'regierungspräsident köln'),
 ('kreissozialhilfsausschuss watsenstein salzgitter',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierung rheinland münchen', 'regierungspräsident münster'),
 ('düsseldorf und köln', 'düsseldorf'),
 ('e behörde wiesbaden', 'hessen wiesbaden'),
 ('regierungsbezirk aachen welf', 'regierungspräsident aachen'),
 ('kreissonderhilfsausschüß braunschweig stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('bay landesentsch münchen', 'b landesentschädigungsamt'),
 ('weißes bayerisches landesentschädigungsamt',
  'bayerisches landesentschädigungsamt'),
 ('l g münchen', 'münchen'),
 ('hauptstelle des bundesentschädigungsgesetzes',
  'bayerisches landesentschädigungsamt'),
 ('kreisonderhilfsausschuss osterode harz',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss hild marb',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschüβ braunschweig stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungsbezirk aachen waff', 'regierungspräsident aachen'),
 ('amt für saarburg', 'saarburg'),
 ('bayerische landesentschädigungsamt münchen',
  'bayerisches landesentschädigungsamt'),
 ('kreisonderhelfsausschub hamm stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschub winsen luhe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsschüle hildesheim marienten',

# Swapping out single tokens with a match distance of up to half of the token's lenght

In [41]:
json_to_csv_closest_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue
    
    max_distance = len(json_token) // 2
    best_match = None
    best_dist = float('inf')
    
    for csv_token in csv_tokens:
        if len(csv_token) >= 3:
            if abs(len(csv_token) - len(json_token)) > max_distance:
                continue
            dist = distance(json_token, csv_token)
            if dist <= max_distance and dist < best_dist:
                best_dist = dist
                best_match = csv_token
    
    if best_match is not None:
        json_to_csv_closest_map[json_token] = [best_match]

single_token_matches_closest = sorted(
    json_to_csv_closest_map.items(),
    key=lambda item: len(item[0])
)
print(len(single_token_matches_closest))
single_token_matches_closest

7013

[('re', ['reg']),
 ('eg', ['reg']),
 ('lr', ['lrb']),
 ('b4', ['vb4']),
 ('dr', ['der']),
 ('fr', ['für']),
 ('tr', ['str']),
 ('da', ['das']),
 ('di', ['die']),
 ('er', ['der']),
 ('ad', ['bad']),
 ('dt', ['hdt']),
 ('st', ['ist']),
 ('vb', ['vb4']),
 ('ba', ['bad']),
 ('de', ['dez']),
 ('of', ['ofd']),
 ('bd', ['bad']),
 ('ht', ['hdt']),
 ('hd', ['hdt']),
 ('dz', ['dez']),
 ('as', ['das']),
 ('mt', ['amt']),
 ('mi', ['min']),
 ('sr', ['str']),
 ('es', ['ems']),
 ('rg', ['reg']),
 ('rb', ['lrb']),
 ('nu', ['neu']),
 ('bah', ['bad']),
 ('rad', ['bad']),
 ('brd', ['bad']),
 ('stg', ['str']),
 ('ddr', ['der']),
 ('bav', ['bad']),
 ('lab', ['lrb']),
 ('drs', ['das']),
 ('ast', ['ist']),
 ('ain', ['fin']),
 ('bes', ['des']),
 ('old', ['ofd']),
 ('bay', ['bad']),
 ('lüd', ['süd']),
 ('ojd', ['ofd']),
 ('rbg', ['reg']),
 ('del', ['dez']),
 ('hss', ['hess']),
 ('xes', ['des']),
 ('art', ['amt']),
 ('vc4', ['vb4']),
 ('per', ['der']),
 ('dad', ['das']),
 ('her', ['der']),
 ('lre', ['lrb']),
 ('lro', ['lrb']),
 ('erb', ['lrb']),
 ('ref', ['reg']),
 ('oed', ['ofd']),
 ('rog', ['reg']),
 ('ung', ['und']),
 ('opd', ['ofd']),
 ('diö', ['die']),
 ('dat', ['das']),
 ('pin', ['fin']),
 ('v84', ['vb4']),
 ('bod', ['bad']),
 ('kin', ['fin']),
 ('wie', ['die']),
 ('db4', ['vb4']),
 ('ver', ['der']),
 ('crb', ['lrb']),
 ('sta', ['str']),
 ('rep', ['reg']),
 ('ber', ['der']),
 ('vbh', ['vb4']),
 ('lüb', ['lrb']),
 ('den', ['dez']),
 ('vin', ['fin']),
 ('hin', ['fin']),
 ('bie', ['die']),
 ('ub4', ['vb4']),
 ('läb', ['lrb']),
 ('and', ['und']),
 ('sod', ['süd']),
 ('kst', ['ist']),
 ('rin', ['fin']),
 ('sin', ['fin']),
 ('dcr', ['der']),
 ('bez', ['dez']),
 ('vba', ['vb4']),
 ('rig', ['reg']),
 ('dem', ['dez']),
 ('neg', ['reg']),
 ('öst', ['ist']),
 ('wür', ['für']),
 ('deu', ['dez']),
 ('bar', ['bad']),
 ('ier', ['der']),
 ('amf', ['amt']),
 ('kln', ['köln']),
 ('eb4', ['vb4']),
 ('stm', ['str']),
 ('köl', ['köln']),
 ('hmt', ['amt']),
 ('rug', ['reg']),
 ('wst', ['ist']),
 ('bam', ['bad']),
 ('tin', ['fin']),
 ('bau', ['bad']),
 ('feg', ['reg']),
 ('abh', ['abt']),
 ('deg', ['dez']),
 ('hes', ['hess']),
 ('lkb', ['lrb']),
 ('ant', ['amt']),
 ('tür', ['für']),
 ('uni', ['und']),
 ('dei', ['dez']),
 ('erw', ['verw']),
 ('prs', ['präs']),
 ('for', ['für']),
 ('dme', ['die']),
 ('xin', ['fin']),
 ('beg', ['reg']),
 ('stl', ['str']),
 ('keg', ['reg']),
 ('cin', ['fin']),
 ('ami', ['amt']),
 ('end', ['und']),
 ('dhe', ['die']),
 ('stv', ['str']),
 ('fun', ['fin']),
 ('kad', ['bad']),
 ('v34', ['vb4']),
 ('peg', ['reg']),
 ('vrw', ['verw']),
 ('har', ['harz']),
 ('lfd', ['ofd']),
 ('lra', ['lrb']),
 ('wes', ['des']),
 ('hdi', ['hdt']),
 ('abg', ['abt']),
 ('hdm', ['hdt']),
 ('baf', ['bad']),
 ('stf', ['str']),
 ('ovd', ['ofd']),
 ('mit', ['min']),
 ('mii', ['min']),
 ('bfd', ['ofd']),
 ('efd', ['ofd']),
 ('rea', ['reg']),
 ('wtr', ['str']),
 ('hdn', ['hdt']),
 ('ger', ['der']),
 ('def', ['dez']),
 ('ofo', ['ofd']),
 ('rey', ['reg']),
 ('mün', ['min']),
 ('bak', ['bad']),
 ('cas', ['das']),
 ('ofg', ['ofd']),
 ('ein', ['fin']),
 ('ord', ['ofd']),
 ('ofr', ['ofd']),
 ('ost', ['ist']),
 ('fln', ['fin']),
 ('vt4', ['vb4']),
 ('off', ['ofd']),
 ('vd4', ['vb4']),
 ('dep', ['dez']),
 ('det', ['dez']),
 ('hst', ['ist']),
 ('vby', ['vb4']),
 ('okd', ['ofd']),
 ('oft', ['ofd']),
 ('bmt', ['amt']),
 ('mad', ['bad']),
 ('ges', ['des']),
 ('kön', ['köln']),
 ('weg', ['reg']),
 ('lr8', ['lrb']),
 ('dos', ['das']),
 ('vr4', ['vb4']),
 ('lbb', ['lrb']),
 ('ofs', ['ofd']),
 ('res', ['reg']),
 ('vb3', ['vb4']),
 ('alt', ['amt']),
 ('doz', ['dez']),
 ('lie', ['die']),
 ('ib4', ['vb4']),
 ('fur', ['für']),
 ('new', ['neu']),
 ('din', ['fin']),
 ('isr', ['ist']),
 ('dor', ['der']),
 ('nec', ['neu']),
 ('vew', ['verw']),
 ('ind', ['und']),
 ('krb', ['lrb']),
 ('dar', ['das']),
 ('qfd', ['ofd']),
 ('trb', ['lrb']),
 ('ubt', ['abt']),
 ('baw', ['bad']),
 ('lad', ['bad']),
 ('öln', ['köln']),
 ('verf', ['verw']),
 ('loin', ['bonn']),
 ('81in', ['fin']),
 ('lohr', ['leer']),
 ('bery', ['der']),
 ('karl', ['kiel']),
 ('herr', ['hess']),
 ('labo', ['lrb']),
 ('veb3', ['vb4']),
 ('baud', ['bad']),
 ('kolm', ['köln']),
 ('kela', ['kiel']),
 ('sohn', ['bonn']),
 ('aöln', ['köln']),
 ('kald', ['bad']),
 ('depl', ['dez']),
 ('kalm', ['köln']),
 ('kzin', ['keine']),
 ('kälm', ['köln']),
 ('k3lm', ['köln']),
 ('pegn', ['reg']),
 ('jöln', ['köln']),
 ('rafe', ['brake']),
 ('alma', ['amt']),
 ('waln', ['köln']),
 ('abge', ['abt']),
 ('mief', ['min']),
 ('minz', ['mainz']),
 ('woln', ['bonn']),
 ('prez', ['dez']),
 ('dell', ['dez']),
 ('berg', ['reg']),
 ('hayt', ['amt']),
 ('roßn', ['bonn']),
 ('weis', ['ems']),
 ('hung', ['und']),
 ('vorg', ['verw']),
 ('hauß', ['harz']),
 ('baum', ['bad']),
 ('vern', ['verw']),
 ('mann', ['bonn']),
 ('viel', ['kiel']),
 ('kblm', ['köln']),
 ('mies', ['des']),
 ('wflz', ['pfalz']),
 ('hand', ['und']),
 ('jews', ['ems']),
 ('syrm', ['str']),
 ('bamf', ['amt']),
 ('vt84', ['vb4']),
 ('nöll', ['köln']),
 ('b81n', ['bonn']),
 ('ismd', ['ist']),
 ('bein', ['bonn']),
 ('höln', ['köln']),
 ('würt', ['für']),
 ('irso', ['ist']),
 ('anat', ['amt']),
 ('pfaz', ['pfalz']),
 ('aisz', ['ist']),
 ('kglm', ['köln']),
 ('thei', ['rhein']),
 ('auln', ['köln']),
 ('k8ln', ['köln']),
 ('elsa', ['ems']),
 ('keln', ['köln']),
 ('kbin', ['keine']),
 ('rech', ['reg']),
 ('west', ['westf']),
 ('baik', ['bad']),
 ('ivb4', ['vb4']),
 ('vts4', ['vb4']),
 ('kölz', ['köln']),
 ('vorw', ['verw']),
 ('kölñ', ['köln']),
 ('dess', ['hess']),
 ('sand', ['und']),
 ('bund', ['und']),
 ('kein', ['keine']),
 ('aust', ['ist']),
 ('road', ['ofd']),
 ('hamm', ['amt']),
 ('merk', ['der']),
 ('insp', ['ist']),
 ('göll', ['köln']),
 ('hunc', ['und']),
 ('yerv', ['der']),
 ('henn', ['bonn']),
 ('aemt', ['amt']),
 ('ehrt', ['hdt']),
 ('xoin', ['bonn']),
 ('welt', ['westf']),
 ('miel', ['kiel']),
 ('kalu', ['köln']),
 ('aviv', ['36iv']),
 ('jürm', ['für']),
 ('isch', ['ist']),
 ('pätz', ['platz']),
 ('kess', ['hess']),
 ('helm', ['hess']),
 ('amon', ['amt']),
 ('main', ['mainz']),
 ('kref', ['kreis']),
 ('schr', ['str']),
 ('dorf', ['adolf']),
 ('wetl', ['etc']),
 ('lend', ['und']),
 ('xxln', ['köln']),
 ('prüm', ['präs']),
 ('dolz', ['adolf']),
 ('moff', ['ofd']),
 ('meck', ['ecke']),
 ('icin', ['fin']),
 ('vba4', ['vb4']),
 ('pras', ['präs']),
 ('präz', ['präs']),
 ('inst', ['ist']),
 ('dmef', ['dez']),
 ('negi', ['reg']),
 ('molf', ['adolf']),
 ('rüdt', ['süd']),
 ('k62n', ['köln']),
 ('mitz', ['mainz']),
 ('mark', ['markt']),
 ('kstu', ['ist']),
 ('thür', ['für']),
 ('lern', ['leer']),
 ('pris', ['präs']),
 ('ptcl', ['etc']),
 ('jeru', ['der']),
 ('bdst', ['ist']),
 ('betr', ['leer']),
 ('vrtr', ['str']),
 ('nauß', ['neue']),
 ('brsg', ['reg']),
 ('mels', ['ems']),
 ('ster', ['str']),
 ('dort', ['der']),
 ('kfar', ['für']),
 ('just', ['ist']),
 ('ilse', ['ist']),
 ('neve', ['neue']),
 ('basa', ['das']),
 ('höll', ['köln']),
 ('vers', ['verw']),
 ('baym', ['bayer']),
 ('dein', ['keine']),
 ('amit', ['amt']),
 ('emde', ['ems']),
 ('bona', ['bonn']),
 ('jöön', ['köln']),
 ('benr', ['bonn']),
 ('kxlm', ['köln']),
 ('vewo', ['verw']),
 ('bohn', ['bonn']),
 ('h8ln', ['köln']),
 ('3hft', ['hdt']),
 ('halz', ['harz']),
 ('tier', ['trier']),
 ('zeig', ['reg']),
 ('syke', ['ecke']),
 ('kuin', ['keine']),
 ('meif', ['min']),
 ('rich', ['aurich']),
 ('kglw', ['köln']),
 ('uöln', ['köln']),
 ('eder', ['der']),
 ('bell', ['celle']),
 ('m81n', ['min']),
 ('vis4', ['ist']),
 ('würf', ['für']),
 ('x8in', ['fin']),
 ('k6ln', ['köln']),
 ('rogf', ['reg']),
 ('barb', ['lrb']),
 ('zond', ['bonn']),
 ('wief', ['die']),
 ('pres', ['präs']),
 ('r8in', ['rhein']),
 ('stat', ['stadt']),
 ('kdst', ['ist']),
 ('hees', ['hess']),
 ('görz', ['harz']),
 ('verm', ['verw']),
 ('neua', ['neue']),
 ('hcss', ['hess']),
 ('hain', ['rhein']),
 ('wdtt', ['hdt']),
 ('dope', ['die']),
 ('palz', ['pfalz']),
 ('büro', ['für']),
 ('merw', ['verw']),
 ('löbn', ['lrb']),
 ('hödn', ['hdt']),
 ('361v', ['36iv']),
 ('völk', ['köln']),
 ('weaf', ['westf']),
 ('land', ['und']),
 ('wist', ['ist']),
 ('berl', ['berlin']),
 ('pelz', ['dez']),
 ('noln', ['bonn']),
 ('hann', ['bonn']),
 ('pröf', ['präs']),
 ('sara', ['str']),
 ('stin', ['str']),
 ('bmft', ['amt']),
 ('36s4', ['36iv']),
 ('polz', ['pfalz']),
 ('fölz', ['pfalz']),
 ('samt', ['amt']),
 ('sürm', ['süd']),
 ('dole', ['adolf']),
 ('memw', ['ems']),
 ('hicn', ['fin']),
 ('vewg', ['reg']),
 ('börn', ['bonn']),
 ('erfu', ['erfurt']),
 ('wels', ['ems']),
 ('kstn', ['ist']),
 ('kobl', ['kiel']),
 ('k8lm', ['köln']),
 ('holn', ['bonn']),
 ('welf', ['westf']),
 ('vcrw', ['verw']),
 ('amth', ['amt']),
 ('ostf', ['ist']),
 ('mess', ['hess']),
 ('k6in', ['keine']),
 ('hölm', ['köln']),
 ('linz', ['fin']),
 ('amnt', ['amt']),
 ('kala', ['köln']),
 ('k5in', ['keine']),
 ('bayr', ['bayer']),
 ('pfla', ['pfalz']),
 ('k3ln', ['köln']),
 ('fclz', ['pfalz']),
 ('roln', ['bonn']),
 ('ivbf', ['vb4']),
 ('wcst', ['ist']),
 ('name', ['amt']),
 ('kats', ['das']),
 ('heße', ['hess']),
 ('vier', ['leer']),
 ('leop', ['leer']),
 ('peer', ['leer']),
 ('paus', ['präs']),
 ('lüba', ['lrb']),
 ('bdln', ['baden']),
 ('länd', ['und']),
 ('bist', ['ist']),
 ('patz', ['platz']),
 ('kolu', ['köln']),
 ('m8in', ['min']),
 ('isar', ['ist']),
 ('k61n', ['köln']),
 ('vb15', ['vb4']),
 ('trer', ['trier']),
 ('bann', ['bonn']),
 ('hier', ['leer']),
 ('wenf', ['westf']),
 ('oldb', ['ofd']),
 ('norw', ['verw']),
 ('röhn', ['köln']),
 ('nöin', ['fin']),
 ('wess', ['hess']),
 ('k5ln', ['köln']),
 ('mdef', ['dez']),
 ('ches', ['hess']),
 ('sprl', ['str']),
 ('eros', ['ems']),
 ('etla', ['etc']),
 ('bayz', ['harz']),
 ('sohr', ['str']),
 ('kiln', ['köln']),
 ('b61n', ['bonn']),
 ('vewc', ['etc']),
 ('haus', ['hess']),
 ('münx', ['min']),
 ('vrwc', ['verw']),
 ('mitt', ['ist']),
 ('kstl', ['ist']),
 ('kart', ['amt']),
 ('bafh', ['bad']),
 ('nord', ['ofd']),
 ('träg', ['präs']),
 ('bauk', ['bad']),
 ('vero', ['verw']),
 ('krim', ['kreis']),
 ('fuer', ['leer']),
 ('unna', ['und']),
 ('stad', ['stadt']),
 ('gera', ['der']),
 ('amts', ['amt']),
 ('k8in', ['keine']),
 ('ofen', ['ofd']),
 ('dolm', ['adolf']),
 ('hund', ['und']),
 ('mich', ['min']),
 ('kclm', ['köln']),
 ('wolf', ['adolf']),
 ('lecr', ['leer']),
 ('h8in', ['rhein']),
 ('löin', ['fin']),
 ('leib', ['leer']),
 ('k5lm', ['köln']),
 ('trag', ['reg']),
 ('k6lm', ['köln']),
 ('kola', ['köln']),
 ('marb', ['lrb']),
 ('blin', ['bonn']),
 ('kall', ['kiel']),
 ('höhn', ['köln']),
 ('elbe', ['ecke']),
 ('pils', ['präs']),
 ('seer', ['leer']),
 ('pflz', ['pfalz']),
 ('hill', ['kiel']),
 ('merg', ['reg']),
 ('kond', ['bonn']),
 ('koll', ['kiel']),
 ('nöln', ['köln']),
 ('brak', ['brake']),
 ('kann', ['bonn']),
 ('hint', ['ist']),
 ('mgrb', ['lrb']),
 ('falz', ['pfalz']),
 ('mölt', ['köln']),
 ('klin', ['keine']),
 ('hamb', ['amt']),
 ('ukln', ['köln']),
 ('koin', ['bonn']),
 ('röge', ['reg']),
 ('wald', ['bad']),
 ('bönn', ['bonn']),
 ('vbs4', ['vb4']),
 ('east', ['ist']),
 ('wehr', ['leer']),
 ('cstf', ['ist']),
 ('hrin', ['rhein']),
 ('nerv', ['der']),
 ('verh', ['verw']),
 ('vorr', ['verw']),
 ('grls', ['präs']),
 ('k8lu', ['köln']),
 ('xerv', ['der']),
 ('merx', ['der']),
 ('kaln', ['köln']),
 ('ungb', ['und']),
 ('flaz', ['platz']),
 ('born', ['bonn']),
 ('trhr', ['trier']),
 ('antt', ['amt']),
 ('vewm', ['verw']),
 ('böln', ['köln']),
 ('xoln', ['bonn']),
 ('kell', ['celle']),
 ('r8ln', ['köln']),
 ('gill', ['kiel']),
 ('vexh', ['verw']),
 ('ienz', ['dez']),
 ('meln', ['min']),
 ('anst', ['ist']),
 ('koni', ['bonn']),
 ('mold', ['ofd']),
 ('ordn', ['ofd']),
 ('döln', ['köln']),
 ('camp', ['amt']),
 ('k6lu', ['köln']),
 ('vrwe', ['verw']),
 ('kohn', ['bonn']),
 ('moin', ['min']),
 ('ciss', ['ist']),
 ('pots', ['präs']),
 ('neuo', ['neue']),
 ('wfst', ['ist']),
 ('lnrb', ['lrb']),
 ('viec', ['die']),
 ('area', ['reg']),
 ('präf', ['präs']),
 ('less', ['hess']),
 ('ring', ['reg']),
 ('hade', ['baden']),
 ('einz', ['keine']),
 ('adam', ['das']),
 ('ampt', ['amt']),
 ('nauo', ['neue']),
 ('bass', ['hess']),
 ('rbln', ['köln']),
 ('wstf', ['westf']),
 ('höin', ['rhein']),
 ('saar', ['str']),
 ('buer', ['leer']),
 ('frau', ['frauen']),
 ('ratg', ['reg']),
 ('drit', ['die']),
 ('jena', ['jenaer']),
 ('k81n', ['köln']),
 ('lech', ['leer']),
 ('w8in', ['fin']),
 ('amat', ['amt']),
 ('mein', ['min']),
 ('mehr', ['leer']),
 ('korn', ['bonn']),
 ('blon', ['bonn']),
 ('gesb', ['hess']),
 ('möln', ['köln']),
 ('stnz', ['str']),
 ('rexx', ['reg']),
 ('lond', ['bonn']),
 ('hamt', ['amt']),
 ('wals', ['das']),
 ('uojn', ['bonn']),
 ('lkad', ['bad']),
 ('brem', ['bremen']),
 ('oftd', ['ofd']),
 ('bahn', ['baden']),
 ('ness', ['hess']),
 ('dung', ['und']),
 ('manz', ['mainz']),
 ('koln', ['köln']),
 ('kohl', ['kiel']),
 ('yerw', ['verw']),
 ('weßf', ['westf']),
 ('mfst', ['ist']),
 ('prag', ['präs']),
 ('malz', ['pfalz']),
 ('heim', ['rhein']),
 ('herz', ['harz']),
 ('kelm', ['kiel']),
 ('plak', ['platz']),
 ('oder', ['der']),
 ('kdin', ['keine']),
 ('neuw', ['neue']),
 ('werw', ['verw']),
 ('mahn', ['mainz']),
 ('maiz', ['mainz']),
 ('lenz', ['dez']),
 ('kass', ['hess']),
 ('hwdg', ['hdt']),
 ('jöhn', ['köln']),
 ('rale', ['brake']),
 ('deff', ['dez']),
 ('häin', ['rhein']),
 ('rest', ['ist']),
 ('fund', ['und']),
 ('akte', ['amt']),
 ('oste', ['ist']),
 ('vtb4', ['vb4']),
 ('hdin', ['rhein']),
 ('weff', ['westf']),
 ('bayg', ['bayer']),
 ('k31n', ['köln']),
 ('amft', ['amt']),
 ('stal', ['stadt']),
 ('baft', ['amt']),
 ('rabe', ['brake']),
 ('päiz', ['prinz']),
 ('john', ['bonn']),
 ('wigl', ['kiel']),
 ('dörf', ['der']),
 ('huss', ['hess']),
 ('wied', ['die']),
 ('sind', ['und']),
 ('kalt', ['amt']),
 ('lion', ['fin']),
 ('poin', ['bonn']),
 ('auch', ['aurich']),
 ('rölm', ['köln']),
 ('auss', ['hess']),
 ('k51n', ['köln']),
 ('merl', ['der']),
 ('bürg', ['bürger']),
 ('dith', ['die']),
 ('dept', ['dez']),
 ('weef', ['leer']),
 ('levy', ['leer']),
 ('höss', ['hess']),
 ('udln', ['köln']),
 ('over', ['leer']),
 ('korb', ['lrb']),
 ('fink', ['fin']),
 ('vegw', ['verw']),
 ('varw', ['verw']),
 ('zell', ['celle']),
 ('hans', ['hess']),
 ('völn', ['köln']),
 ('linn', ['bonn']),
 ('eusk', ['ems']),
 ('hölt', ['hdt']),
 ('wesf', ['westf']),
 ('stlh', ['str']),
 ('nolu', ['neu']),
 ('berm', ['der']),
 ('efrn', ['fin']),
 ('371v', ['37iv']),
 ('heil', ['rhein']),
 ('ruin', ['rhein']),
 ('vt54', ['vb4']),
 ('faiz', ['fin']),
 ('meta', ['etc']),
 ('baun', ['baden']),
 ('woff', ['ofd']),
 ('verv', ['verw']),
 ('fels', ['ems']),
 ('deft', ['dez']),
 ('hest', ['hess']),
 ('juni', ['und']),
 ('vweg', ['reg']),
 ('trir', ['trier']),
 ('chtr', ['str']),
 ('vbst', ['ist']),
 ('plaz', ['platz']),
 ('röin', ['rhein']),
 ('wepf', ['westf']),
 ('reta', ['reg']),
 ('möll', ['köln']),
 ('matn', ['mainz']),
 ('wesu', ['hess']),
 ('bafö', ['bad']),
 ('über', ['leer']),
 ('männ', ['bonn']),
 ('stau', ['stadt']),
 ('mell', ['celle']),
 ('pius', ['präs']),
 ('pltz', ['platz']),
 ('kshd', ['süd']),
 ('aach', ['aachen']),
 ('köla', ['köln']),
 ('holz', ['harz']),
 ('hadf', ['hdt']),
 ('wetf', ['westf']),
 ('zone', ['bonn']),
 ('ptlz', ['pfalz']),
 ('blen', ['baden']),
 ('röln', ['köln']),
 ('prof', ['präs']),
 ('pfiz', ['fin']),
 ('stml', ['str']),
 ('dürk', ['der']),
 ('bank', ['bonn']),
 ('sinz', ['fin']),
 ('moln', ['bonn']),
 ('frei', ['freie']),
 ('münz', ['mainz']),
 ('lutz', ['platz']),
 ('orde', ['ofd']),
 ('pflk', ['pfalz']),
 ('bern', ['bonn']),
 ('triv', ['36iv']),
 ('hald', ['harz']),
 ('nest', ['ist']),
 ('draf', ['das']),
 ('bish', ['ist']),
 ('jung', ['und']),
 ('marz', ['harz']),
 ('prsä', ['präs']),
 ('wein', ['keine']),
 ('mink', ['min']),
 ('k3in', ['keine']),
 ('vt34', ['vb4']),
 ('noin', ['bonn']),
 ('würm', ['für']),
 ('wega', ['reg']),
 ('jötn', ['köln']),
 ('delf', ['adolf']),
 ('lind', ['und']),
 ('neus', ['neue']),
 ('k6hn', ['köln']),
 ('stdt', ['stadt']),
 ('sitz', ['str']),
 ('hofn', ['bonn']),
 ('trie', ['trier']),
 ('leya', ['leer']),
 ('paiz', ['pfalz']),
 ('lieb', ['leer']),
 ('ostz', ['ist']),
 ('rbge', ['reg']),
 ('wölf', ['köln']),
 ('pala', ['pfalz']),
 ('ostr', ['str']),
 ('best', ['ist']),
 ('dent', ['dez']),
 ('koen', ['bonn']),
 ('wien', ['fin']),
 ('koín', ['bonn']),
 ('iren', ['reg']),
 ('afdr', ['ofd']),
 ('döin', ['fin']),
 ('koex', ['kiel']),
 ('pfals', ['pfalz']),
 ('freib', ['freie']),
 ('preiz', ['kreis']),
 ('knies', ['kiel']),
 ('versw', ['verw']),
 ('stift', ['stadt']),
 ('ereis', ['kreis']),
 ('rölin', ['rhein']),
 ('ostfr', ['ostfrld']),
 ('frier', ['trier']),
 ('kalis', ['kreis']),
 ('spyer', ['bayer']),
 ('mathz', ['mainz']),
 ('kasse', ['kassel']),
 ('aller', ['leer']),
 ('neuen', ['neue']),
 ('instr', ['ist']),
 ('holle', ['celle']),
 ('lamet', ['amt']),
 ('trüir', ['trier']),
 ('pfarr', ['pfalz']),
 ('wesff', ['westf']),
 ('ueber', ['leer']),
 ('annen', ['innern']),
 ('halbz', ['harz']),
 ('westp', ['westf']),
 ('ryder', ['der']),
 ('magin', ['maria']),
 ('triol', ['trier']),
 ('westu', ['westf']),
 ('ausch', ['aurich']),
 ('statz', ['stadt']),
 ('wrest', ['westf']),
 ('majer', ['bayer']),
 ('höamt', ['amt']),
 ('triel', ['trier']),
 ('trher', ['trier']),
 ('neuer', ['neue']),
 ('feyer', ['leer']),
 ('plätz', ['platz']),
 ('bayhj', ['bayer']),
 ('gring', ['prinz']),
 ('heins', ['keine']),
 ('wesel', ['westf']),
 ('fritz', ['prinz']),
 ('pidlz', ['pfalz']),
 ('eugen', ['jugend']),
 ('reche', ['ecke']),
 ('kremn', ['kreis']),
 ('herne', ['keine']),
 ('geier', ['leer']),
 ('stödt', ['stadt']),
 ('weste', ['westf']),
 ('urtei', ['kartei']),
 ('saale', ['stade']),
 ('plink', ['peine']),
 ('tröer', ['trier']),
 ('radem', ['baden']),
 ('eifel', ['kiel']),
 ('lower', ['leer']),
 ('bayhö', ['bayer']),
 ('aaden', ['baden']),
 ('erbin', ['berlin']),
 ('ostfd', ['ofd']),
 ('bayot', ['bayer']),
 ('koeln', ['kiel']),
 ('bezug', ['bezüge']),
 ('protz', ['prinz']),
 ('westl', ['westf']),
 ('maier', ['mainzer']),
 ('rengh', ['reg']),
 ('blenz', ['koblenz']),
 ('kirch', ['kirchen']),
 ('rayer', ['bayer']),
 ('völnd', ['köln']),
 ('mahnz', ['mainz']),
 ('nainz', ['mainz']),
 ('krois', ['kreis']),
 ('pfölz', ['pfalz']),
 ('tierr', ['trier']),
 ('wcstr', ['westf']),
 ('emden', ['baden']),
 ('heydt', ['hdt']),
 ('theil', ['rhein']),
 ('kroic', ['kreis']),
 ('boann', ['bonn']),
 ('präsd', ['präs']),
 ('traun', ['frauen']),
 ('ostpr', ['str']),
 ('siadi', ['stadt']),
 ('gräss', ['präs']),
 ('siadt', ['stadt']),
 ('mains', ['mainz']),
 ('heamt', ['amt']),
 ('hagen', ['baden']),
 ('mäinz', ['mainz']),
 ('brand', ['brake']),
 ('erich', ['aurich']),
 ('efrat', ['referat']),
 ('pfatz', ['pfalz']),
 ('gelle', ['celle']),
 ('heims', ['ems']),
 ('dölln', ['köln']),
 ('pielz', ['pfalz']),
 ('plalz', ['pfalz']),
 ('durch', ['aurich']),
 ('maizn', ['mainz']),
 ('arjie', ['freie']),
 ('parat', ['markt']),
 ('deren', ['der']),
 ('phälz', ['pfalz']),
 ('blatz', ['platz']),
 ('trift', ['trier']),
 ('maina', ['mainz']),
 ('palat', ['platz']),
 ('kroio', ['kreis']),
 ('nebau', ['neu']),
 ('lesem', ['leer']),
 ('fialz', ['pfalz']),
 ('kolle', ['celle']),
 ('kölle', ['celle']),
 ('piatz', ['platz']),
 ('siadr', ['stadt']),
 ('trlir', ['trier']),
 ('heime', ['keine']),
 ('peckz', ['ecke']),
 ('etmol', ['detmold']),
 ('kroin', ['kreis']),
 ('zölfn', ['köln']),
 ('regic', ['reg']),
 ('board', ['bad']),
 ('desam', ['des']),
 ('völin', ['köln']),
 ('wcctf', ['westf']),
 ('halle', ['celle']),
 ('pflaz', ['pfalz']),
 ('froim', ['freie']),
 ('yerwo', ['verw']),
 ('jever', ['leer']),
 ('fides', ['des']),
 ('bayem', ['bayer']),
 ('verwo', ['verw']),
 ('klein', ['keine']),
 ('buren', ['baden']),
 ('minsk', ['min']),
 ('haldt', ['hdt']),
 ('glatz', ['platz']),
 ('state', ['stade']),
 ('efurt', ['erfurt']),
 ('triar', ['trier']),
 ('leine', ['keine']),
 ('edorf', ['adolf']),
 ('yerwe', ['verw']),
 ('fürth', ['für']),
 ('eitel', ['kiel']),
 ('neues', ['neue']),
 ('hesse', ['hess']),
 ('plaiz', ['platz']),
 ('westi', ['westf']),
 ('nberg', ['ebert']),
 ('linau', ['landau']),
 ('weist', ['ist']),
 ('italz', ['pfalz']),
 ('bayes', ['bayer']),
 ('merkx', ['markt']),
 ('bvamt', ['amt']),
 ('bayam', ['bayer']),

In [42]:
unique_distance1_token_map = {
    json_token: csv_candidates[0]
    for json_token, csv_candidates in json_to_csv_closest_map.items()
    if len(csv_candidates) == 1
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_json_filtered['CompensationOffice_token_swap'] = df_json_filtered['norm_office'].apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_json_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['norm_office'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 7013

,CompensationOffice1,MatchedOffice,MatchDistance
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,10.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,3.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,kreissonderhilfsausschuß delmenhorst,12.0
16,bundeskartei,NaN,NaN
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,0.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,kreissonderhilfsausschuß delmenhorst,9.0
20,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,6.0
21,hess staatsministerium,NaN,NaN

In [43]:
total = len(df_matches_token_swap)
max_dist = int(df_matches_token_swap['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches_token_swap['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 26718 (7.62%)
MatchDistance = 1: 19486 (5.56%)
MatchDistance = 2: 6634 (1.89%)
MatchDistance = 3: 19193 (5.47%)
MatchDistance = 4: 41087 (11.72%)
MatchDistance = 5: 6784 (1.93%)
MatchDistance = 6: 23953 (6.83%)
MatchDistance = 7: 3818 (1.09%)
MatchDistance = 8: 6261 (1.79%)
MatchDistance = 9: 25207 (7.19%)
MatchDistance = 10: 3461 (0.99%)
MatchDistance = 11: 2775 (0.79%)
MatchDistance = 12: 13350 (3.81%)
MatchDistance = 13: 4640 (1.32%)
MatchDistance = 14: 2040 (0.58%)
MatchDistance = 15: 3274 (0.93%)
MatchDistance = 16: 3127 (0.89%)
MatchDistance = 17: 1801 (0.51%)
MatchDistance = 18: 1906 (0.54%)
MatchDistance = 19: 15997 (4.56%)
MatchDistance = 20: 2269 (0.65%)
MatchDistance = 21: 1140 (0.33%)
MatchDistance = 22: 797 (0.23%)
MatchDistance = 23: 19975 (5.70%)
MatchDistance = 24: 1462 (0.42%)
MatchDistance = 25: 350 (0.10%)
MatchDistance = 26: 202 (0.06%)
MatchDistance = 27: 700 (0.20%)
MatchDistance = 28: 1404 (0.40%)
MatchDistance = 29: 1775 (0.51%)
MatchDistance = 30: 325 (0.09%)
MatchDistance = 31: 478 (0.14%)
MatchDistance = 32: 157 (0.04%)
MatchDistance = 33: 811 (0.23%)
MatchDistance = 34: 44 (0.01%)
MatchDistance = 35: 52 (0.01%)
MatchDistance = 36: 39 (0.01%)
MatchDistance = 37: 33 (0.01%)
MatchDistance = 38: 19 (0.01%)
MatchDistance = 39: 29 (0.01%)
MatchDistance = 40: 25 (0.01%)
MatchDistance = 41: 4 (0.00%)
MatchDistance = 42: 9 (0.00%)
MatchDistance = 43: 12 (0.00%)
MatchDistance = 44: 12 (0.00%)
MatchDistance = 45: 5 (0.00%)
MatchDistance = 46: 7 (0.00%)
MatchDistance = 47: 5 (0.00%)
MatchDistance = 48: 4 (0.00%)
MatchDistance = 49: 1 (0.00%)
MatchDistance = 50: 1 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 1 (0.00%)
MatchDistance = 53: 0 (0.00%)
MatchDistance = 54: 3 (0.00%)
MatchDistance = 55: 14 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 3 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 9 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 1 (0.00%)

In [ ]:
df_leftovers = df_matches_token_swap[df_matches_token_swap['MatchDistance'] == 4]

df_leftovers

,CompensationOffice1,MatchedOffice,MatchDistance
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,10.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,3.0
...,...,...,...
403387,reg präsident präsident des vereinsbezirks han...,der präsident des verwaltungsbezirks in oldenburg,26.0
403388,aachen,münchen,3.0
403389,bayrisches landesamt für verfolgtenwesen,bayerisches landesentschädigungsamt,16.0
403390,reg präsident präsident des verw bezirks,reg präsident hildesheim,20.0
403391,bezirksamt für wiedergutmachung,bezirksamt für wiedergutmachung mainz,6.0

In [46]:
for t in csv_tokens:
    if t == 'regierungspräsidium':
        print(t)

regierungspräsidium

# Calling LLM via API using NaN values

In [ ]:
from groq import Groq
from huggingface_hub import InferenceClient
from huggingface_hub.utils import HfHubHTTPError

import time
import json
import os
from dotenv import load_dotenv
from tqdm import tqdm

In [ ]:
load_dotenv()

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "groq").strip().lower()
HF_MODEL = os.getenv("HF_MODEL", "Qwen/Qwen3-8B")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")

if LLM_PROVIDER == "huggingface":
    HF_API_TOKEN = os.getenv("HF_API_KEY")
    if not HF_API_TOKEN:
        raise ValueError("HF_API_KEY is required when LLM_PROVIDER='huggingface'")
    client = InferenceClient(
        model=HF_MODEL,
        token=HF_API_TOKEN
    )
    ACTIVE_MODEL = HF_MODEL
elif LLM_PROVIDER == "groq":
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")
    if not GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY is required when LLM_PROVIDER='groq'")
    client = Groq(api_key=GROQ_API_KEY)
    ACTIVE_MODEL = GROQ_MODEL
else:
    raise ValueError("LLM_PROVIDER must be either 'huggingface' or 'groq'")

print(f"Using LLM provider: {LLM_PROVIDER}, model: {ACTIVE_MODEL}")

offices_list = "\n".join([f"- {office}" for office in compensation_offices])

In [ ]:

def get_llm_match_batch(query_names, offices_list, max_retries=3):
    
    queries = "\n".join([f"{i+1}. \"{name}\"" for i, name in enumerate(query_names)])
    
    prompt = f"""You are an expert at matching German compensation office names (Entschädigungsämter).

Given these query names:
{queries}

Find the BEST match for EACH from this list:
{offices_list}

Rules:
1. Return ONLY a numbered list with the exact name from the list
2. Consider spelling variations and OCR errors
3. If no match exists, write \"NO_MATCH\"
4. Format: \"1. Matching Name\" or \"1. NO_MATCH\"

Answers:"""

    messages = [{"role": "user", "content": prompt}]
    
    for attempt in range(max_retries):
        try:
            if LLM_PROVIDER == "huggingface":
                response = client.chat_completion(
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            elif LLM_PROVIDER == "groq":
                response = client.chat.completions.create(
                    model=ACTIVE_MODEL,
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            else:
                raise ValueError(f"Unsupported LLM provider: {LLM_PROVIDER}")
            
            matches = []
            lines = text.split('\n')
            for line in lines:
                line = line.strip()
                if line and len(line) > 0 and line[0].isdigit():
                    parts = line.split('.', 1) if '.' in line else line.split(')', 1)
                    if len(parts) > 1:
                        match = parts[1].strip()
                        matches.append(match)
            
            while len(matches) < len(query_names):
                matches.append("PARSE_ERROR")
            
            return matches[:len(query_names)]
            
        except HfHubHTTPError as e:
            error_str = str(e).lower()
            if "429" in str(e) or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in str(e) or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  # Signal to stop processing
            elif "503" in str(e) or "loading" in error_str:
                print(f"Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"HTTP Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
        except Exception as e:
            error_str = str(e).lower()
            if "429" in error_str or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in error_str or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  
            elif "503" in error_str or "loading" in error_str:
                print("Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
    
    return ["ERROR"] * len(query_names)

if len(no_matched_office_df) >= 2:
    test_names = no_matched_office_df['CompensationOffice1'].iloc[:2].tolist()
    print(f"Testing with:")
    for i, name in enumerate(test_names):
        print(f"  {i+1}. {name}")
    print()
    results = get_llm_match_batch(test_names, offices_list)
    if results:
        print("LLM suggested matches:")
        for i, result in enumerate(results):
            print(f"  {i+1}. {result}")
    else:
        print("API limit reached during test!")

Testing with:
  1. hess staatsministerium
  2. nan

HTTP Error: (Request ID: Root=1-69b1eb80-71adc530557736b071097d90;d9f9dd39-1eb3-4ef0-ba3c-5262937b9357)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb80-71adc530557736b071097d90;d9f9dd39-1eb3-4ef0-ba3c-5262937b9357)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb8b-327d3b150fb21f54500eaa1b;53e79627-7379-4e6b-b427-8c7f26fab5c4)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb8b-327d3b150fb21f54500eaa1b;53e79627-7379-4e6b-b427-8c7f26fab5c4)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb96-03491cd562a1abed5f8cafe4;88b979cc-beaa-4cfd-bf6d-8c5d12e7cb32)

Bad request:
LLM suggested matches:
  1. ERROR
  2. ERROR
HTTP Error: (Request ID: Root=1-69b1eb96-03491cd562a1abed5f8cafe4;88b979cc-beaa-4cfd-bf6d-8c5d12e7cb32)

Bad request:
LLM suggested matches:
  1. ERROR
  2. ERROR

In [ ]:
BATCH_SIZE = 10
DELAY_BETWEEN_BATCHES = 5  

output_file = 'hf_llm_matches_progress.jsonl'

processed = set()
llm_matches = []
try:
    with open(output_file, 'r') as f:
        for line in f:
            entry = json.loads(line)
            llm_matches.append(entry)
            processed.add(entry['CompensationOffice1'])
    print(f"Resuming from {len(processed)} already processed entries")
except FileNotFoundError:
    print("Starting fresh")

df_remaining = no_matched_office_df[~no_matched_office_df['CompensationOffice1'].isin(processed)]
print(f"Remaining to process: {len(df_remaining)}")

total_batches = (len(df_remaining) + BATCH_SIZE - 1) // BATCH_SIZE
api_limit_reached = False

for batch_idx in tqdm(range(total_batches), desc="Processing batches"):
    if api_limit_reached:
        break
        
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(df_remaining))
    
    batch_df = df_remaining.iloc[start_idx:end_idx]
    batch_names = batch_df['CompensationOffice1'].tolist()
    
    batch_results = get_llm_match_batch(batch_names, offices_list)
    
    if batch_results is None:
        print("\nAPI limit reached! Saving progress and stopping.")
        api_limit_reached = True
        break
    
    for i, (idx, row) in enumerate(batch_df.iterrows()):
        entry = {
            'CompensationOffice1': row['CompensationOffice1'],
            'MatchedOffice': row['MatchedOffice'],
            'MatchDistance': float(row['MatchDistance']) if pd.notna(row['MatchDistance']) else None,
            'LLMMatch': batch_results[i] if i < len(batch_results) else "ERROR"
        }
        llm_matches.append(entry)
        
        with open(output_file, 'a') as f:
            f.write(json.dumps(entry) + '\n')
    
    if batch_idx < total_batches - 1 and not api_limit_reached:
        time.sleep(DELAY_BETWEEN_BATCHES)

df_hf_matches = pd.DataFrame(llm_matches)
print(f"\nProcessed: {len(df_hf_matches)} entries")
if api_limit_reached:
    print("Note: Processing stopped due to API limit. Run again later to continue.")
df_hf_matches.head(20)

In [ ]:
valid_matches = df_hf_matches[~df_hf_matches['LLMMatch'].isin(['NO_MATCH', 'ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]
no_matches = df_hf_matches[df_hf_matches['LLMMatch'] == 'NO_MATCH']
errors = df_hf_matches[df_hf_matches['LLMMatch'].isin(['ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]

print(f"Total processed: {len(df_hf_matches)}")
print(f"LLM found matches: {len(valid_matches)} ({len(valid_matches)/max(len(df_hf_matches),1)*100:.1f}%)")
print(f"No match found: {len(no_matches)}")
print(f"Errors: {len(errors)}")

df_hf_matches.to_excel('compensation_office_hf_llm_matches.xlsx', index=False)
print("\nSaved to compensation_office_hf_llm_matches.xlsx")