In [1]:
import pandas as pd

In [3]:
df_csv = pd.read_excel('2025_01_27_Liste der Entschädigungsämter mit Adressen, Varianten und Archiven.xlsx')
df_csv.head()

,Layout class,Filename,Bundesland,CompensationOffice,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 6
0,ABC-Karten,1930_12_13_41_0,Niedersachsen,Stadt Celle,Niedersächsisches Landesarchiv,6510041-4,NaN
1,ABC-Karten,1901_03_02_64_0,Niedersachsen,Kreissonderhilfsausschuß \nDelmenhorst,Niedersächsisches Landesarchiv,6510041-4,NaN
2,ABC-Karten,1907_12_31_115_0,Niedersachsen,Goslar,Niedersächsisches Landesarchiv,6510041-4,NaN
3,ABC-Karten,1909_01_06_66_0,Niedersachsen,Goslar. Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN
4,ABC-Karten,1904_01_08_54_0,Niedersachsen,Göttingen-Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN

In [4]:
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)

In [5]:
df_json.head()

,CompensationOffice1,BZKNr,filename
0,Regierungsbezirksamt für Wiedergutmachung und ...,65477,1875_00_00_101_0.jpg
1,Landesamt für die Wiedergutmachung Karlsruhe,EK 20093 A,1875_04_05_16_0.jpg
2,Niedersachsen,1 27574 c,1875_06_15_14_0.jpg
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg
4,Entschädigungsamt Berlin,70 002,1875_07_12_9_0.jpg

In [9]:
print(len(df_csv))
print(len(df_json))

424
1901284

In [33]:
n = df_json['CompensationOffice1'].isin(df_csv['CompensationOffice']).sum()
print(f'Number of matches: {n}')

Number of matches: 1121989

In [6]:
from Levenshtein import distance

In [30]:
compensation_offices = list(df_csv['CompensationOffice'])
total = len(df_json)

for threshold in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    n = 0
    for name in df_json['CompensationOffice1']:
        for office in compensation_offices:
            if distance(str(name), str(office)) <= threshold:
                n += 1
                break

    pct = n / total * 100    
    print(f'Levenshtein ≤ {threshold}: {n} ({pct:.2f}%)')

Levenshtein ≤ 1: 1191937 (62.69%)
Levenshtein ≤ 2: 1284267 (67.55%)
Levenshtein ≤ 2: 1284267 (67.55%)
Levenshtein ≤ 3: 1428108 (75.11%)
Levenshtein ≤ 3: 1428108 (75.11%)
Levenshtein ≤ 4: 1571555 (82.66%)
Levenshtein ≤ 4: 1571555 (82.66%)
Levenshtein ≤ 5: 1591968 (83.73%)
Levenshtein ≤ 5: 1591968 (83.73%)
Levenshtein ≤ 6: 1667271 (87.69%)
Levenshtein ≤ 6: 1667271 (87.69%)
Levenshtein ≤ 7: 1687671 (88.76%)
Levenshtein ≤ 7: 1687671 (88.76%)
Levenshtein ≤ 8: 1716380 (90.27%)
Levenshtein ≤ 8: 1716380 (90.27%)
Levenshtein ≤ 9: 1739241 (91.48%)
Levenshtein ≤ 9: 1739241 (91.48%)
Levenshtein ≤ 10: 1745945 (91.83%)
Levenshtein ≤ 10: 1745945 (91.83%)

In [31]:
compensation_offices = list(df_csv['CompensationOffice'])
total = len(df_json)

for threshold in [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]:
    n = 0
    for name in df_json['CompensationOffice1']:
        for office in compensation_offices:
            if distance(str(name), str(office)) <= threshold:
                n += 1
                break

    pct = n / total * 100    
    print(f'Levenshtein ≤ {threshold}: {n} ({pct:.2f}%)')

Levenshtein ≤ 11: 1762770 (92.71%)
Levenshtein ≤ 12: 1770049 (93.10%)
Levenshtein ≤ 12: 1770049 (93.10%)
Levenshtein ≤ 13: 1781375 (93.69%)
Levenshtein ≤ 13: 1781375 (93.69%)
Levenshtein ≤ 14: 1786183 (93.95%)
Levenshtein ≤ 14: 1786183 (93.95%)
Levenshtein ≤ 15: 1822611 (95.86%)
Levenshtein ≤ 15: 1822611 (95.86%)
Levenshtein ≤ 16: 1825609 (96.02%)
Levenshtein ≤ 16: 1825609 (96.02%)
Levenshtein ≤ 17: 1829800 (96.24%)
Levenshtein ≤ 17: 1829800 (96.24%)
Levenshtein ≤ 18: 1834363 (96.48%)
Levenshtein ≤ 18: 1834363 (96.48%)
Levenshtein ≤ 19: 1840870 (96.82%)
Levenshtein ≤ 19: 1840870 (96.82%)
Levenshtein ≤ 20: 1843609 (96.97%)
Levenshtein ≤ 20: 1843609 (96.97%)

In [32]:
compensation_offices = list(df_csv['CompensationOffice'])
total = len(df_json)

for threshold in [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]:
    n = 0
    for name in df_json['CompensationOffice1']:
        for office in compensation_offices:
            if distance(str(name), str(office)) <= threshold:
                n += 1
                break

    pct = n / total * 100    
    print(f'Levenshtein ≤ {threshold}: {n} ({pct:.2f}%)')

Levenshtein ≤ 21: 1846589 (97.12%)
Levenshtein ≤ 22: 1861024 (97.88%)
Levenshtein ≤ 22: 1861024 (97.88%)
Levenshtein ≤ 23: 1864001 (98.04%)
Levenshtein ≤ 23: 1864001 (98.04%)
Levenshtein ≤ 24: 1865850 (98.14%)
Levenshtein ≤ 24: 1865850 (98.14%)
Levenshtein ≤ 25: 1867226 (98.21%)
Levenshtein ≤ 25: 1867226 (98.21%)
Levenshtein ≤ 26: 1867815 (98.24%)
Levenshtein ≤ 26: 1867815 (98.24%)
Levenshtein ≤ 27: 1884914 (99.14%)
Levenshtein ≤ 27: 1884914 (99.14%)
Levenshtein ≤ 28: 1885473 (99.17%)
Levenshtein ≤ 28: 1885473 (99.17%)
Levenshtein ≤ 29: 1886914 (99.24%)
Levenshtein ≤ 29: 1886914 (99.24%)
Levenshtein ≤ 30: 1888048 (99.30%)
Levenshtein ≤ 30: 1888048 (99.30%)

In [34]:
import numpy as np

compensation_offices = list(df_csv['CompensationOffice'])

def get_min_distance(name, max_threshold=10):
    min_dist = float('inf')
    for office in compensation_offices:
        d = distance(str(name), str(office))
        if d == 0:
            return 0  
        if d < min_dist:
            min_dist = d
    return min_dist if min_dist <= max_threshold else np.nan

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'],
    'MatchDistance': df_json['CompensationOffice1'].apply(get_min_distance)
})

df_matches.head(20)

                                  CompensationOffice1  MatchDistance
0   Regierungsbezirksamt für Wiedergutmachung und ...            3.0
1        Landesamt für die Wiedergutmachung Karlsruhe            1.0
2                                       Niedersachsen            0.0
3     Bezirksamt für Wiedergutmachung Neustadt a.d.W.            4.0
4                            Entschädigungsamt Berlin            0.0
5                            Entschädigungsamt Berlin            0.0
6                                                Köln            0.0
7   Amt für Wiedergutmachung des Selbstkantkreises...            9.0
8   Landesentschädigungsamt Schleswig-Holstein in ...            1.0
9                                       Hessen Kassel            0.0
10                                Nordrhein-Westfalen            0.0
11                           Entschädigungsamt Berlin            0.0
12               Bezirksamt für Wiedergutmachung Köln            4.0
13                 Der Regierungspräsidium Düsseldorf            3.0
14                                               Köln            0.0
15              Bezirksamt für Wiedergutmachung Trier            0.0
16  Hansestadt Hamburg, Sozialbehörde, Amt für Wie...            1.0
17                                           Freiburg            0.0
18                                             Hessen            4.0
19  Regierungsbezirk für Wiedergutmachung und verw...            7.0

In [35]:
nan_count = df_matches['MatchDistance'].isna().sum()
print(f'MatchDistance = NaN: {nan_count}')

MatchDistance = NaN: 155339

In [ ]:
def get_min_distance(name, max_threshold=50):
    min_dist = float('inf')
    for office in compensation_offices:
        d = distance(str(name), str(office))
        if d == 0:
            return 0  
        if d < min_dist:
            min_dist = d
    return min_dist if min_dist <= max_threshold else np.nan

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'],
    'MatchDistance': df_json['CompensationOffice1'].apply(get_min_distance)
})

df_matches.head(20)

                                  CompensationOffice1  MatchDistance
0   Regierungsbezirksamt für Wiedergutmachung und ...            3.0
1        Landesamt für die Wiedergutmachung Karlsruhe            1.0
2                                       Niedersachsen            0.0
3     Bezirksamt für Wiedergutmachung Neustadt a.d.W.            4.0
4                            Entschädigungsamt Berlin            0.0
5                            Entschädigungsamt Berlin            0.0
6                                                Köln            0.0
7   Amt für Wiedergutmachung des Selbstkantkreises...            9.0
8   Landesentschädigungsamt Schleswig-Holstein in ...            1.0
9                                       Hessen Kassel            0.0
10                                Nordrhein-Westfalen            0.0
11                           Entschädigungsamt Berlin            0.0
12               Bezirksamt für Wiedergutmachung Köln            4.0
13                 Der Regierungspräsidium Düsseldorf            3.0
14                                               Köln            0.0
15              Bezirksamt für Wiedergutmachung Trier            0.0
16  Hansestadt Hamburg, Sozialbehörde, Amt für Wie...            1.0
17                                           Freiburg            0.0
18                                             Hessen            4.0
19  Regierungsbezirk für Wiedergutmachung und verw...            7.0

In [29]:
total = len(df_matches)
for i in range(51):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1121989 (59.01%)
MatchDistance = 1: 69948 (3.68%)
MatchDistance = 2: 92330 (4.86%)
MatchDistance = 3: 143841 (7.57%)
MatchDistance = 4: 143447 (7.54%)
MatchDistance = 5: 20413 (1.07%)
MatchDistance = 6: 75303 (3.96%)
MatchDistance = 7: 20400 (1.07%)
MatchDistance = 8: 28709 (1.51%)
MatchDistance = 9: 22861 (1.20%)
MatchDistance = 10: 6704 (0.35%)
MatchDistance = 11: 16825 (0.88%)
MatchDistance = 12: 7279 (0.38%)
MatchDistance = 13: 11326 (0.60%)
MatchDistance = 14: 4808 (0.25%)
MatchDistance = 15: 36428 (1.92%)
MatchDistance = 16: 2998 (0.16%)
MatchDistance = 17: 4191 (0.22%)
MatchDistance = 18: 4563 (0.24%)
MatchDistance = 19: 6507 (0.34%)
MatchDistance = 20: 2739 (0.14%)
MatchDistance = 21: 2980 (0.16%)
MatchDistance = 22: 14435 (0.76%)
MatchDistance = 23: 2977 (0.16%)
MatchDistance = 24: 1849 (0.10%)
MatchDistance = 25: 1376 (0.07%)
MatchDistance = 26: 589 (0.03%)
MatchDistance = 27: 17099 (0.90%)
MatchDistance = 28: 559 (0.03%)
MatchDistance = 29: 1441 (0.08%)
MatchDistance = 30: 1134 (0.06%)
MatchDistance = 31: 2675 (0.14%)
MatchDistance = 32: 672 (0.04%)
MatchDistance = 33: 1806 (0.09%)
MatchDistance = 34: 1609 (0.08%)
MatchDistance = 35: 1265 (0.07%)
MatchDistance = 36: 393 (0.02%)
MatchDistance = 37: 1009 (0.05%)
MatchDistance = 38: 667 (0.04%)
MatchDistance = 39: 497 (0.03%)
MatchDistance = 40: 577 (0.03%)
MatchDistance = 41: 638 (0.03%)
MatchDistance = 42: 375 (0.02%)
MatchDistance = 43: 146 (0.01%)
MatchDistance = 44: 119 (0.01%)
MatchDistance = 45: 90 (0.00%)
MatchDistance = 46: 166 (0.01%)
MatchDistance = 47: 56 (0.00%)
MatchDistance = 48: 44 (0.00%)
MatchDistance = 49: 67 (0.00%)
MatchDistance = 50: 28 (0.00%)

In [25]:
nan_count = df_matches['MatchDistance'].isna().sum()
print(f'MatchDistance = NaN: {nan_count}')

MatchDistance = NaN: 337

In [27]:
df_matches.to_csv('compensation_office_matches.csv', index=False)

In [ ]:
compensation_offices = list(df_csv['CompensationOffice'])

def get_min_distance_dynamic(name):
    name_clean = str(name).strip().lower()
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = str(office).strip().lower()
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,Regierungsbezirksamt für Wiedergutmachung und ...,Regierungsbezirksamt für Wiedergutmachung und ...,3.0
1,Landesamt für die Wiedergutmachung Karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,1.0
2,Niedersachsen,Niedersachsen,0.0
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,4.0
4,Entschädigungsamt Berlin,Entschädigungsamt Berlin,0.0
5,Entschädigungsamt Berlin,Entschädigungsamt Berlin,0.0
6,Köln,Köln,0.0
7,Amt für Wiedergutmachung des Selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,9.0
8,Landesentschädigungsamt Schleswig-Holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,1.0
9,Hessen Kassel,Hessen Kassel,0.0
10,Nordrhein-Westfalen,Nordrhein-Westfalen,0.0
11,Entschädigungsamt Berlin,Entschädigungsamt Berlin,0.0
12,Bezirksamt für Wiedergutmachung Köln,Bezirksamt für Wiedergutmachung Koblenz,4.0
13,Der Regierungspräsidium Düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,Köln,Köln,0.0
15,Bezirksamt für Wiedergutmachung Trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...","Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,Freiburg,Freiburg,0.0
18,Hessen,HESSEN,0.0
19,Regierungsbezirk für Wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,7.0

In [8]:
print(f"Max MatchDistance: {df_matches['MatchDistance'].max()}")

Max MatchDistance: 67.0

In [9]:
total = len(df_matches)
for i in range(68):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1301488 (68.45%)
MatchDistance = 1: 70533 (3.71%)
MatchDistance = 2: 75278 (3.96%)
MatchDistance = 3: 61396 (3.23%)
MatchDistance = 4: 56236 (2.96%)
MatchDistance = 5: 10499 (0.55%)
MatchDistance = 6: 15875 (0.83%)
MatchDistance = 7: 17415 (0.92%)
MatchDistance = 8: 11524 (0.61%)
MatchDistance = 9: 21476 (1.13%)
MatchDistance = 10: 4060 (0.21%)
MatchDistance = 11: 6060 (0.32%)
MatchDistance = 12: 5054 (0.27%)
MatchDistance = 13: 8704 (0.46%)
MatchDistance = 14: 2423 (0.13%)
MatchDistance = 15: 2443 (0.13%)
MatchDistance = 16: 2090 (0.11%)
MatchDistance = 17: 1860 (0.10%)
MatchDistance = 18: 2857 (0.15%)
MatchDistance = 19: 5675 (0.30%)
MatchDistance = 20: 1772 (0.09%)
MatchDistance = 21: 1489 (0.08%)
MatchDistance = 22: 13125 (0.69%)
MatchDistance = 23: 1655 (0.09%)
MatchDistance = 24: 1348 (0.07%)
MatchDistance = 25: 541 (0.03%)
MatchDistance = 26: 417 (0.02%)
MatchDistance = 27: 16724 (0.88%)
MatchDistance = 28: 419 (0.02%)
MatchDistance = 29: 1277 (0.07%)
MatchDistance = 30: 275 (0.01%)
MatchDistance = 31: 1145 (0.06%)
MatchDistance = 32: 225 (0.01%)
MatchDistance = 33: 863 (0.05%)
MatchDistance = 34: 289 (0.02%)
MatchDistance = 35: 323 (0.02%)
MatchDistance = 36: 640 (0.03%)
MatchDistance = 37: 56 (0.00%)
MatchDistance = 38: 48 (0.00%)
MatchDistance = 39: 37 (0.00%)
MatchDistance = 40: 32 (0.00%)
MatchDistance = 41: 21 (0.00%)
MatchDistance = 42: 23 (0.00%)
MatchDistance = 43: 19 (0.00%)
MatchDistance = 44: 17 (0.00%)
MatchDistance = 45: 7 (0.00%)
MatchDistance = 46: 5 (0.00%)
MatchDistance = 47: 7 (0.00%)
MatchDistance = 48: 9 (0.00%)
MatchDistance = 49: 7 (0.00%)
MatchDistance = 50: 1 (0.00%)
MatchDistance = 51: 5 (0.00%)
MatchDistance = 52: 4 (0.00%)
MatchDistance = 53: 6 (0.00%)
MatchDistance = 54: 1 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 2 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 0 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 2 (0.00%)
MatchDistance = 61: 2 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 13 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 1 (0.00%)
MatchDistance = 66: 5 (0.00%)
MatchDistance = 67: 1 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 2 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 0 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 2 (0.00%)
MatchDistance = 61: 2 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 13 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 1 (0.00%)
MatchDistance = 66: 5 (0.00%)
MatchDistance = 67: 1 (0.00%)

In [ ]:
import re

compensation_offices = list(df_csv['CompensationOffice'])

def normalize_whitespace(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

def get_min_distance_dynamic_normalized(name):
    name_clean = normalize_whitespace(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = normalize_whitespace(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'].apply(normalize_whitespace),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
3,bezirksamt für wiedergutmachung neustadt a.d.w.,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,2.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
6,köln,Köln,0.0
7,amt für wiedergutmachung des selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,9.0
8,landesentschädigungsamt schleswig-holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,0.0
9,hessen kassel,Hessen Kassel,0.0
10,nordrhein-westfalen,Nordrhein-Westfalen,0.0
11,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
12,bezirksamt für wiedergutmachung köln,Bezirksamt\nfür Wiedergutmachung\nMainz,4.0
13,der regierungspräsidium düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,köln,Köln,0.0
15,bezirksamt für wiedergutmachung trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,"hansestadt hamburg, sozialbehörde, amt für wie...","Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,freiburg,Freiburg,0.0
18,hessen,HESSEN,0.0
19,regierungsbezirk für wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,4.0

In [15]:
print(f"Max MatchDistance: {df_matches['MatchDistance'].max()}")

Max MatchDistance: 67.0

In [16]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1422538 (74.82%)
MatchDistance = 1: 64054 (3.37%)
MatchDistance = 2: 24334 (1.28%)
MatchDistance = 3: 22113 (1.16%)
MatchDistance = 4: 43303 (2.28%)
MatchDistance = 5: 10644 (0.56%)
MatchDistance = 6: 24848 (1.31%)
MatchDistance = 7: 6033 (0.32%)
MatchDistance = 8: 5534 (0.29%)
MatchDistance = 9: 21285 (1.12%)
MatchDistance = 10: 4700 (0.25%)
MatchDistance = 11: 4947 (0.26%)
MatchDistance = 12: 10438 (0.55%)
MatchDistance = 13: 3892 (0.20%)
MatchDistance = 14: 2818 (0.15%)
MatchDistance = 15: 2491 (0.13%)
MatchDistance = 16: 2054 (0.11%)
MatchDistance = 17: 2153 (0.11%)
MatchDistance = 18: 2218 (0.12%)
MatchDistance = 19: 5044 (0.27%)
MatchDistance = 20: 1473 (0.08%)
MatchDistance = 21: 1185 (0.06%)
MatchDistance = 22: 13153 (0.69%)
MatchDistance = 23: 1518 (0.08%)
MatchDistance = 24: 17725 (0.93%)
MatchDistance = 25: 582 (0.03%)
MatchDistance = 26: 1000 (0.05%)
MatchDistance = 27: 269 (0.01%)
MatchDistance = 28: 242 (0.01%)
MatchDistance = 29: 635 (0.03%)
MatchDistance = 30: 267 (0.01%)
MatchDistance = 31: 1225 (0.06%)
MatchDistance = 32: 256 (0.01%)
MatchDistance = 33: 843 (0.04%)
MatchDistance = 34: 349 (0.02%)
MatchDistance = 35: 146 (0.01%)
MatchDistance = 36: 649 (0.03%)
MatchDistance = 37: 44 (0.00%)
MatchDistance = 38: 31 (0.00%)
MatchDistance = 39: 45 (0.00%)
MatchDistance = 40: 19 (0.00%)
MatchDistance = 41: 36 (0.00%)
MatchDistance = 42: 11 (0.00%)
MatchDistance = 43: 15 (0.00%)
MatchDistance = 44: 17 (0.00%)
MatchDistance = 45: 7 (0.00%)
MatchDistance = 46: 5 (0.00%)
MatchDistance = 47: 8 (0.00%)
MatchDistance = 48: 8 (0.00%)
MatchDistance = 49: 2 (0.00%)
MatchDistance = 50: 4 (0.00%)
MatchDistance = 51: 4 (0.00%)
MatchDistance = 52: 2 (0.00%)
MatchDistance = 53: 3 (0.00%)
MatchDistance = 54: 2 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 1 (0.00%)
MatchDistance = 61: 20 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)
MatchDistance = 56: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 1 (0.00%)
MatchDistance = 61: 20 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)

In [18]:
df_nomatches = df_matches[df_matches['MatchDistance'] > 0]

In [21]:
df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)