In [1]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re

In [3]:
df_csv = pd.read_excel('2025_01_27_Liste der Entschädigungsämter mit Adressen, Varianten und Archiven.xlsx')
df_csv.head()

,Layout class,Filename,Bundesland,CompensationOffice,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 6
0,ABC-Karten,1930_12_13_41_0,Niedersachsen,Stadt Celle,Niedersächsisches Landesarchiv,6510041-4,NaN
1,ABC-Karten,1901_03_02_64_0,Niedersachsen,Kreissonderhilfsausschuß \nDelmenhorst,Niedersächsisches Landesarchiv,6510041-4,NaN
2,ABC-Karten,1907_12_31_115_0,Niedersachsen,Goslar,Niedersächsisches Landesarchiv,6510041-4,NaN
3,ABC-Karten,1909_01_06_66_0,Niedersachsen,Goslar. Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN
4,ABC-Karten,1904_01_08_54_0,Niedersachsen,Göttingen-Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN

In [15]:
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.head()

,CompensationOffice1,BZKNr,filename
0,Regierungsbezirksamt für Wiedergutmachung und ...,65477,1875_00_00_101_0.jpg
1,Landesamt für die Wiedergutmachung Karlsruhe,EK 20093 A,1875_04_05_16_0.jpg
2,Niedersachsen,1 27574 c,1875_06_15_14_0.jpg
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg
4,Entschädigungsamt Berlin,70 002,1875_07_12_9_0.jpg

In [16]:
print(len(df_csv))
print(len(df_json))

n = df_json['CompensationOffice1'].isin(df_csv['CompensationOffice']).sum()
print(f'Number of matches: {n}')

424
1901284
Number of matches: 1121989

# Matching based on Lvenshtein Distance

In [17]:
compensation_offices = list(df_csv['CompensationOffice'])

# remove linebreaks and sequences of whitespaces
def remove_linebreak(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

# return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = remove_linebreak(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'].apply(remove_linebreak),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})


df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
3,bezirksamt für wiedergutmachung neustadt a.d.w.,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,2.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
6,köln,Köln,0.0
7,amt für wiedergutmachung des selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,9.0
8,landesentschädigungsamt schleswig-holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,0.0
9,hessen kassel,Hessen Kassel,0.0
10,nordrhein-westfalen,Nordrhein-Westfalen,0.0
11,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
12,bezirksamt für wiedergutmachung köln,Bezirksamt\nfür Wiedergutmachung\nMainz,4.0
13,der regierungspräsidium düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,köln,Köln,0.0
15,bezirksamt für wiedergutmachung trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,"hansestadt hamburg, sozialbehörde, amt für wie...","Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,freiburg,Freiburg,0.0
18,hessen,HESSEN,0.0
19,regierungsbezirk für wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,4.0

In [6]:
print(f"Max MatchDistance: {df_matches['MatchDistance'].max()}")

Max MatchDistance: 67.0

In [7]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1422538 (74.82%)
MatchDistance = 1: 64054 (3.37%)
MatchDistance = 2: 24334 (1.28%)
MatchDistance = 3: 22113 (1.16%)
MatchDistance = 4: 43303 (2.28%)
MatchDistance = 5: 10644 (0.56%)
MatchDistance = 6: 24848 (1.31%)
MatchDistance = 7: 6033 (0.32%)
MatchDistance = 8: 5534 (0.29%)
MatchDistance = 9: 21285 (1.12%)
MatchDistance = 10: 4700 (0.25%)
MatchDistance = 11: 4947 (0.26%)
MatchDistance = 12: 10438 (0.55%)
MatchDistance = 13: 3892 (0.20%)
MatchDistance = 14: 2818 (0.15%)
MatchDistance = 15: 2491 (0.13%)
MatchDistance = 16: 2054 (0.11%)
MatchDistance = 17: 2153 (0.11%)
MatchDistance = 18: 2218 (0.12%)
MatchDistance = 19: 5044 (0.27%)
MatchDistance = 20: 1473 (0.08%)
MatchDistance = 21: 1185 (0.06%)
MatchDistance = 22: 13153 (0.69%)
MatchDistance = 23: 1518 (0.08%)
MatchDistance = 24: 17725 (0.93%)
MatchDistance = 25: 582 (0.03%)
MatchDistance = 26: 1000 (0.05%)
MatchDistance = 27: 269 (0.01%)
MatchDistance = 28: 242 (0.01%)
MatchDistance = 29: 635 (0.03%)
MatchDistance = 30: 267 (0.01%)
MatchDistance = 31: 1225 (0.06%)
MatchDistance = 32: 256 (0.01%)
MatchDistance = 33: 843 (0.04%)
MatchDistance = 34: 349 (0.02%)
MatchDistance = 35: 146 (0.01%)
MatchDistance = 36: 649 (0.03%)
MatchDistance = 37: 44 (0.00%)
MatchDistance = 38: 31 (0.00%)
MatchDistance = 39: 45 (0.00%)
MatchDistance = 40: 19 (0.00%)
MatchDistance = 41: 36 (0.00%)
MatchDistance = 42: 11 (0.00%)
MatchDistance = 43: 15 (0.00%)
MatchDistance = 44: 17 (0.00%)
MatchDistance = 45: 7 (0.00%)
MatchDistance = 46: 5 (0.00%)
MatchDistance = 47: 8 (0.00%)
MatchDistance = 48: 8 (0.00%)
MatchDistance = 49: 2 (0.00%)
MatchDistance = 50: 4 (0.00%)
MatchDistance = 51: 4 (0.00%)
MatchDistance = 52: 2 (0.00%)
MatchDistance = 53: 3 (0.00%)
MatchDistance = 54: 2 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 1 (0.00%)
MatchDistance = 61: 20 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 1 (0.00%)
MatchDistance = 61: 20 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)

In [8]:
df_nomatches = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)

In [18]:
df_exact_matches_or_nan = df_matches[(df_matches['MatchDistance'] == 0) | (df_matches['CompensationOffice1'].isna()) | (df_matches['CompensationOffice1'] == 'nan')]

df_exact_matches_or_nan

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
...,...,...,...
1901279,bayerisches landesentschädigungsamt,Bayerisches Landesentschädigungsamt,0.0
1901280,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
1901281,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
1901282,bezirksamt für wiedergutmachung koblenz,Bezirksamt für Wiedergutmachung Koblenz,0.0
1901283,bezirksamt für wiedergutmachung mainz,Bezirksamt\nfür Wiedergutmachung\nMainz,0.0

In [26]:
df_json["norm_office"] = df_json["CompensationOffice1"].apply(remove_linebreak)

exact_norm = set(df_exact_matches_or_nan["CompensationOffice1"].dropna())

df_json_filtered = df_json[~df_json["norm_office"].isin(exact_norm)].copy()

print(len(df_json), len(df_json_filtered))
df_json_filtered.head()

1901284 403408

,CompensationOffice1,BZKNr,filename,norm_office
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg,bezirksamt für wiedergutmachung neustadt a.d.w.
7,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
12,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
13,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
16,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,"hansestadt hamburg, sozialbehörde, amt für wie..."

In [27]:
df_json_filtered.to_json('compoff_extracted_filtered.jsonl', orient='records', lines=True)

# Continuing with Partial Dataset

In [5]:
df_json_filtered = pd.read_json('compoff_extracted_filtered.jsonl', lines=True)

df_json_filtered

,CompensationOffice1,BZKNr,filename,norm_office
0,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg,bezirksamt für wiedergutmachung neustadt a.d.w.
1,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
2,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
3,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
4,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,"hansestadt hamburg, sozialbehörde, amt für wie..."
...,...,...,...,...
403403,Aachen,41 952,1917_03_27_67_0.jpg,aachen
403404,Bayrisches Landesamt für Verfolgtenwesen,123312/VIII/55,1917_06_05_91_0.jpg,bayrisches landesamt für verfolgtenwesen
403405,Reg.-Präsident / Präsident des Verw.Bezirks,1 32601 a,1917_05_24_21_0.jpg,reg.-präsident / präsident des verw.bezirks
403406,Bezirksamt für Wiedergutmachung,111 427,1917_03_27_4_0.jpg,bezirksamt für wiedergutmachung
403407,Regierungsbezirksamt für Wiedergutmachung und ...,114 948,1917_07_04_61_0.jpg,regierungsbezirksamt für wiedergutmachung und ...

# Matching without Punctuation

In [8]:
def remove_linebreak(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

# remove linebreaks, punctuation and sequences of whitespaces
def remove_punctuation(s):
    p = ['?', '!', '.', ',', ';', ':', '-', '_', '(', ')', '[', ']', '{', '}', '"', "'", '/']
    for char in p:
        s = s.replace(char, ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

compensation_offices = list(df_csv['CompensationOffice'])

print(compensation_offices[:10])

compensation_offices = [remove_linebreak(remove_punctuation(office)) for office in compensation_offices]

print(compensation_offices[:10])

['Stadt Celle', 'Kreissonderhilfsausschuß \nDelmenhorst', 'Goslar', 'Goslar. Stadt', 'Göttingen-Stadt', 'Hannover', 'Hannover - Stadt', 'Stadt Hannover', 'Helmstedt', 'Hildesheim-Stadt']
['stadt celle', 'kreissonderhilfsausschuß delmenhorst', 'goslar', 'goslar stadt', 'göttingen stadt', 'hannover', 'hannover stadt', 'stadt hannover', 'helmstedt', 'hildesheim stadt']

In [9]:

#updated version of get_min_distance_dynamic_normalized that also removes punctuation
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak(remove_punctuation(name))
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        d = distance(name_clean, office)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json_filtered['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['CompensationOffice1'].apply(remove_punctuation),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,7.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,4.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,2.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
11,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,NaN,NaN
16,bundeskartei,NaN,NaN
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,3.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,NaN,NaN

In [10]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 52227 (12.95%)
MatchDistance = 1: 33750 (8.37%)
MatchDistance = 2: 10717 (2.66%)
MatchDistance = 3: 19463 (4.82%)
MatchDistance = 4: 43260 (10.72%)
MatchDistance = 5: 9386 (2.33%)
MatchDistance = 6: 23139 (5.74%)
MatchDistance = 7: 5620 (1.39%)
MatchDistance = 8: 6111 (1.51%)
MatchDistance = 9: 22174 (5.50%)
MatchDistance = 10: 3724 (0.92%)
MatchDistance = 11: 3588 (0.89%)
MatchDistance = 12: 10586 (2.62%)
MatchDistance = 13: 3822 (0.95%)
MatchDistance = 14: 2880 (0.71%)
MatchDistance = 15: 2658 (0.66%)
MatchDistance = 16: 2481 (0.62%)
MatchDistance = 17: 2541 (0.63%)
MatchDistance = 18: 2527 (0.63%)
MatchDistance = 19: 15769 (3.91%)
MatchDistance = 20: 2457 (0.61%)
MatchDistance = 21: 1501 (0.37%)
MatchDistance = 22: 1215 (0.30%)
MatchDistance = 23: 18172 (4.50%)
MatchDistance = 24: 1059 (0.26%)
MatchDistance = 25: 569 (0.14%)
MatchDistance = 26: 233 (0.06%)
MatchDistance = 27: 528 (0.13%)
MatchDistance = 28: 949 (0.24%)
MatchDistance = 29: 1741 (0.43%)
MatchDistance = 30: 384 (0.10%)
MatchDistance = 31: 480 (0.12%)
MatchDistance = 32: 269 (0.07%)
MatchDistance = 33: 794 (0.20%)
MatchDistance = 34: 72 (0.02%)
MatchDistance = 35: 75 (0.02%)
MatchDistance = 36: 29 (0.01%)
MatchDistance = 37: 43 (0.01%)
MatchDistance = 38: 26 (0.01%)
MatchDistance = 39: 39 (0.01%)
MatchDistance = 40: 29 (0.01%)
MatchDistance = 41: 13 (0.00%)
MatchDistance = 42: 16 (0.00%)
MatchDistance = 43: 8 (0.00%)
MatchDistance = 44: 10 (0.00%)
MatchDistance = 45: 9 (0.00%)
MatchDistance = 46: 6 (0.00%)
MatchDistance = 47: 10 (0.00%)
MatchDistance = 48: 7 (0.00%)
MatchDistance = 49: 0 (0.00%)
MatchDistance = 50: 3 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 3 (0.00%)
MatchDistance = 53: 1 (0.00%)
MatchDistance = 54: 4 (0.00%)
MatchDistance = 55: 13 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 2 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 8 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 0 (0.00%)
MatchDistance = 64: 1 (0.00%)

In [11]:
df_exact_matches = df_matches[df_matches['MatchDistance'] == 0]

df_exact_matches

,CompensationOffice1,MatchedOffice,MatchDistance
0,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
11,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
25,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
37,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
39,landesamt für die wiedergutmachung tübingen,landesamt für die wiedergutmachung tübingen,0.0
...,...,...,...
403373,oberfinanzdirektion köln,oberfinanzdirektion köln,0.0
403374,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
403381,bezirksamt für wiedergutmachung neustadt a d w,bezirksamt für wiedergutmachung neustadt a d w,0.0
403391,oberfinanzdirektion köln,oberfinanzdirektion köln,0.0
403407,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0

In [ ]:
df_json_filtered["norm_office"] = df_json_filtered["norm_office"].apply(remove_punctuation)

exact_norm = set(df_exact_matches["CompensationOffice1"].dropna())

df_json_filtered = df_json_filtered[~df_json_filtered["norm_office"].isin(exact_norm)].copy()

df_json_filtered

,CompensationOffice1,BZKNr,filename,norm_office
1,Amt für Wiedergutmachung des Selbstkantkreises...,48 583,1875_12_26_5_0.jpg,amt für wiedergutmachung des selbstkantkreises...
2,Bezirksamt für Wiedergutmachung Köln,407384,1875_00_00_11_0.jpg,bezirksamt für wiedergutmachung köln
3,Der Regierungspräsidium Düsseldorf,78872,1875_06_17_4_0.jpg,der regierungspräsidium düsseldorf
4,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",21806 Keb,1875_09_14_7_0.jpg,hansestadt hamburg sozialbehörde amt für wiede...
5,Regierungsbezirk für Wiedergutmachung und verw...,47 691,1875_04_05_13_0.jpg,regierungsbezirk für wiedergutmachung und verw...
...,...,...,...,...
403402,Reg.-Präsident /Präsident des Vereinsbezirks H...,1 27101 a,1917_06_23_32_0.jpg,reg präsident präsident des vereinsbezirks han...
403403,Aachen,41 952,1917_03_27_67_0.jpg,aachen
403404,Bayrisches Landesamt für Verfolgtenwesen,123312/VIII/55,1917_06_05_91_0.jpg,bayrisches landesamt für verfolgtenwesen
403405,Reg.-Präsident / Präsident des Verw.Bezirks,1 32601 a,1917_05_24_21_0.jpg,reg präsident präsident des verw bezirks
403406,Bezirksamt für Wiedergutmachung,111 427,1917_03_27_4_0.jpg,bezirksamt für wiedergutmachung

In [ ]:
df_no_matches_no_punctuation = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]
df_no_matches_no_punctuation = df_no_matches_no_punctuation.sort_values('MatchDistance', ascending=False)
df_no_matches_no_punctuation.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
422246,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,64.0
47910,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",61.0
227493,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt für Wiedergutmachung und ...,60.0
1135308,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1881670,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1617342,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1138927,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1126699,der regierungspräsident – dezernat für wiederg...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
293761,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1827229,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1309098,der herr regierungspräsident dezernat für wied...,a) Der Regierungspräsident - Dezernat für Wied...,59.0
1594676,a der regierungspräsident dezernat f wiedergut...,"a) Der Regierungspräsident, Dezernat für Wiede...",59.0
1247401,regierungspräsident dezernat für wiedergutmach...,Der Oberkreisdirektor -Amt für Wiedergutmachun...,59.0
1372604,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",58.0
514604,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",58.0
1897187,der regierungspräsident dezernat 14 in detmold...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
68367,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
393399,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
1857448,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,56.0
1590248,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,56.0

In [ ]:
df_no_matches_no_punctuation.to_excel('compensation_office_nomatches_no_punctuation.xlsx', index=False)

# No Matches

In [56]:
no_matched_office_df = df_nomatches[df_nomatches['MatchDistance'].isna()]

no_matched_office_df

,CompensationOffice1,MatchedOffice,MatchDistance
21,hess staatsministerium,NaN,NaN
30,nan,NaN,NaN
32,freie und hansestadt hamburg,NaN,NaN
34,hess staatsministerium,NaN,NaN
40,nan,NaN,NaN
...,...,...,...
1901202,hng,NaN,NaN
1901203,reg präsident präsident des verw bezirks hannover,NaN,NaN
1901238,hng,NaN,NaN
1901254,reg präsident präsident des vereinsbezirks han...,NaN,NaN
1901262,bayrisches landesamt für verfolgtenwesen,NaN,NaN

In [91]:
no_matched_office_df_set = set(no_matched_office_df['CompensationOffice1'])

len(no_matched_office_df_set)
for office in no_matched_office_df_set:
    print(office)

th bayerisches verfolgungsamt
schweiz
bezirksamt
ansl amtbremen
bmt ub4
landesherzogtum bayern
k817
entschädigungsbehörde landesentschädigungsbehörde für die bundesrepublik deutschland
kreisaußerhilfsausschübe
wiedergutmachung stuttgart
regionalverwaltungsamt neustadt a d weinstr
bmf vb 4
aör amt bremen
beauftragung
sondervermögens u bautverwaltung
hess ns hätefonds
bay staatsarchiv
niedersachsen präsident präsident des vermögensverwaltungsausschusses
kreissozialamt hade
bayerisches volksgericht
kreissozialamt jena
r a sladowsky
regierungsbezirksverwaltungsamt koblenz
land amt mainz
niedersachsen präsident präsident des verwaltungsgerichts aurich
dyepetrouke ukraine
pöltmann annemarie
15 5 23
bayerisches landesamt für die opfer des nationalsozialismus
kupfermints
wuttenstein salzgitter
rey frieda ruth geb ehrmann 8 10 33 kuhlmann jnge geb ehrmann 14 12 35 ehrmann doris renate 31 3 1937
staatsanwalt lg münchen
lka jülich
landsgericht und strafkammer münchen
niedersachsen präsident des verw bezirks braunschweig
regierung brüssel
lva speyer
niedersachsen präsident präsidentenkommission
schadensammlung
kreisverwaltungsbezirk mains
hildesheim im niedersachsen
kdo
fallingsbostel
reg präsident & präsident des verw bezirks
x61
st h 1332 k
kz buchenwald
kreissonderhilfusschübe
landesamt für die vergütung von opfern des nationalsozialismus
sondervermögens u baubewirtschaftung
bayessche kartei
st h 3142
neustadt neustadt
k & lm
kreissozialhilfeausschübe
o konferenz
ausgl amt bremen
bundes vcrw amt
1223
dvrnbnre e l m
united restitution office frankfurt m grunenburgweg 119
kreishilfsausschuss
st h 1111 200 p
ratxprasidentk präsident des verw bezirks braunschweig
kreisonderhelfsausschuf
regierungsamt münchen dnf
düsseldorfer landesjustiz
bayesische verfolgungsausschuss
regierung
restitutionsamt wied
reg präsident präsident des vorw bezirksk
kreissozialhilfsausschuss
st h 1992 w
united restitution office frankfurt main grüneburgweg 119
landesstelle für mahn und erinnerungsaufgaben
kreissozialhilfsauschuss
kreisverwaltung bielefeld
neustadt westerwald
neuschatz a rbg
e81n
bardorf
bhf vby 0 1478 15 10071
r a adam
kärntner landesregierung
usa
vorgang
ländesamt für die bayerische gleichstellung der verfolgten des nationalsozialismus
st h 1654
niedersachsen präsident präsident des bundesverwaltungsgerichts
sondervermögens u baurechtsverwaltung
dr merkens
emmendingen
verw hint münchen
kreissozialhilfe salzgitter
1 fs 1987 köln
wienerland reg
restitution office p o box 1180 johannesburg s afrika
15 3 24
kreisonderschutzbehörde gifhorn
kreissozialamt rinteln
regierungsamt aachen deft
kreissozialamt colle stadt
rey dr linnros
v reichsgericht köln
vehta
kshm melle
amtsvormund herrn franke landesamt für die rehabilitation der behörden für arbeit gesundheit u soziales der freie u hansestadt hamburg simm von utrecht str 4a 2000 hamburg 36
regierungsbezirksamt neustadt a d weinstr
öd 1131 e 4792
vorgang an bundesverw 7 4 64
bayer zentralstelle
kreissozialamt freiburg
ölg
reinhard anna moff
bayhö
lvia
bund fin stg
bayisches versicherungsamt
regionalverwaltungsgericht münchen und verwalteter vormögen
alfeld leine
kreissonderhilfsausschüf
reg präsident präsident des verw bezirks münchen
kreissozialamt münchen pasing
kammerwaldau
kreissonderhlfasschuf
b v
uro berlin m 50 reichspflichtsohuf 72 76
landkreis großhöft
düsseldorfer denegerierungspräsident
landesamt für ländliche entwicklung
kreissozialamt lecr
kreissozialamt priesland
c 2860
kreis sonderhilfegewährungsausschuss
ksha watenstedt salzgitter
entschädigungsbehörde reparationsbeamtung für verfolgte und verluste
stadtverwaltung bremen
gob teiblum
schreibtisungsausschuss
sachverständigenstelle für befristete reg
ksh nordheim
tr assamt
rz
an bundeekartei
aurich h i ostfriesl
ksha hameln pyrmont
kreissozialamt bielefeld
c 5182
sen f innere berlin
krefeld
rheinischer palatiner
ausglamt bremen
maximiliana a z
r d vollm
aussenstelle münchen württemberg
kreissozialamt emde
victoria 9 3 06
ksha hamm
kreissohnschaftsausschuss
nevrov
düsseldorfer regierungspräsidium
kreissozialamt osterholz
bayrische kartei regina
bmf vd4
bay l krim amt
c 5064
restitution office for the western zone and the administered areas mainz
st h 2980 st
bayrisches verwaltungsamt
landesbeirat in israel
niedersachsen präsident präsident des verwaltungs behörde
niedersachsen präsident präsident des vexvo bezirks hannover
sondervermögens uk b l e n z
key präsid münchen
regierungsbezirk baym
bundesministerium für vertriebene und flüchtlinge
niedersachsen präsident landesdenkmal des vaterlands
e 6443
bmf vtb 4
c 1997 e 3922
kreis nordhorn
dp camp lager lechfeld
lgd
bayerisches spreu
bayerisches namenverzeichnis registratur
16 in
kreisonderhilfsausschuss
hof
r a eckstein berlin 31 konstanzer str 10
amtsgericht amberg w e r i
kreissozialamt der stadt warendorf schöppingen
kreislaufsonderhilfsausschuss
kreisaußerhelfsausschuß
aurich ostfriesl
niedersachsen reg präsident präsident des verw bezirks silvesheim
niedersachsenpräsidium präsident des verw bezirks oldenburg old
landesamt für vertriebene wild und zuchtgeschäfts
ksha in freising
bayhaupt
neue karten für die erben
kölner amtsgruppe
doppelmeldung berlin ansbach
st 11 1427 r
landes nordr westfalen abteilung v
schreibt münchen
ksha hann st
bayerisches landeszentrale für die opfer des nationalsozialismus
kallm
kreissozialamt landkreis osieholtz
hinweis
k 31 n
281938
niedersachsen präsident präsident des meritoren
doppelung
bmf vt
amt bundeskartei
rostock ast kiel
bhf vbs4
xslm
h a 4425 st
ksha wingen luhe
reg präsident präsident des verw bezirksso hannover
länderzentrale münchen 2 abt 11
ksha götttingen
landesarchiv
doppelvermögens und baubehörde
3 h 2023 b
ra pfort
regierung rendsburg
wiadergutmachung stuttgart
bayrisches verfolgungsgesamtarchiv
bundesländer
haftbescheiden
der reg präs detmold dezernat 56
sinclair
unbekannt
bayrisches namesbüro
mag dr wimmer
bezirksamt von koblenz 86573
ksha hamm p
k 01
rayerisches versöhnungsamt
r81m
niedersachsen g präsident präsident des verw bezirksk
in land friede jakub
aussensenstelle freiburg br
moseltoff
kreisondeserhlfasschuf wittmund
enabäderungsausschuss der kultusministerien
tr bayerische kartei
aöl
e 4166
halbenreuth
amt zeppelin
kshb burgdorf
hnog
ansbet bundeskartei
hest staatsministerium
lvh niederbayern
f 446
reg präsident präsident des varw bezirks hannover
bayrisches landesamt für akten und archivwesen
sudkartei für bez reg
regierung brügge mfl
landrat des landkreises marburg lahn kreisjugendamt amtsvormundschaft
niedersachsen präsident räsidient des verw bezirks hannover
wirtschafts und sozialwissenschaftliches institut
k 8 in
kreissozialhilfe alfeld leine
der reichsverwaltungsgerichtshof
tr rudy
yv
köln nr 717 513
3 in
kreissozialamt hammel
bamleskartei
doppelbeladung
doppel meldung stuttgart
kreissonderhilfsschüf
st h 2620 b
mayerische landeszentrale für die verfolgten des nationalsozialismus
18 8 11
xiii
karlsruhe aussenstelle freiburg brsg
united restitution office frankfurt main gruneburgweg 119 hildesheim
sp 4614 w
r a neubut
deutscher verwaltungsamt
tr landeszentrale für die vergütung von opfern des nationalsozialismus
sondervermögensverwaltung
bht vb3
bayrisches verfolgtenarchiv
st h 1430 p
st h 6670 s
wittmund
waisenstädter salzgitter
ko1
regierung fürth würt
niedersachsen präsident präsidenten der mernwbenzksn
ksha hildesheim marienb
gefängenshaft genannt josef lewandowski
kreissozialamt see
kreissozialamt mappen
karlsruhe aussenstelle freiburg br
bayerisches landesamt für schäden durch krieg und ns verbrechen
c 3362
stadt amt dresden
st h 22 17 l
regionalverwaltungsbezirk köln
st h 1468 g
ksha
bauhaus
niedersachsen reg präsident landesarchiv
kreissozialhilfeauschuss leer
st h 744
vag
bmf vr4
landesherikskstelle
bundesamt für die verwaltung des vermögens der flüchtlinge und vertriebenen
sondervermögens und baubewertung
schreibtamt
kreissozialamt watenstedt salzgitter
reg präsident präsident des verw bezirks hannover
ludwigshafen a rh
bayern u nrw köln
länd zentral registratur
kreissozialamt jürm
niedersachsen präsidium präsident des niedersachsen bezirks
landesheiratstelle stuttgart
sondervermögens u bayerische kartei
niedersachsen präsidium präsident des merkzeichenbezirks hannover
regierung hessenberg
weimar
bayerisches vermögensamt
kölner büro
koblenz bv abteilung
niedersachsen präsident präsident des nerv bezirks
landesentschädigungsbehörde für die bundesrepublik deutschland
26 10 1929
nordenheim i o
gen krousch
reg präsident präsident des verw bezirks eckhoff
reg amsberg
niedersachsen präsident präsidentenkreisverwaltung
landkreis osnabrück
bayerisches landesamt für vertriebene steiger
bezirksamt koblenz
ksha grafshausen
regierung posen meß
inl
st h 1621 a
k m
st h 1459
bhf vtb4
doppelmeilung hamburg
gestapo bayerische kartei
nola
hächer
ko11
ksha schauemburg lippe
krefeld linn
regional office for compensation and administration of assets neusadt a d weinstraße
bundesarchive
s schreiber stuttgart
regierungsbezirk hessen nassau wiesbaden
köln riehler pl 2 5000 köln
sondervermögens u bäuerliche vermögenswaltung
niedersachsen präsident präsident des verw bezirks sülzesheim
regierungsbezirk neustadt a d aisch
bfd nest wörthstr 1 3
united restitution office frankfurt m grünheubergweg 119
vereinigung nachfolger
kö
aurich ootfrold
kreisverwaltungsreferat schwerin
landesbeauftragte
ua
c 4421
ksha alfeld leine
israel arjie
ostdeutsche beratungsstelle
ra rengh
ksha braunlage
niedersachsen präsident britsident des merkwest bekanntssx
sondervermögens und bautenverwaltung
24 2 24
st h 2513
düsseldorfer landesstelle
amtsgericht jena weimar
760n
e 2729
regionalverwaltungsbehörde der stadt münchen
schreiber landesverfolgungssamt
ksaha
e 7208
monaco
bayerische versicherungsanstalt
bay krim amt
stadtverwaltung stadthaus
a 691 läuft in karlsruhe gesondert als originaler antrag – schaden am leben nach landesamt für die wiedergutmachung karlsruhe
aurich 1 outfr
bay verwaltungsamt münchen
köln stettin
ksha diefpholz
aurich i osthavelland
kreissozialhilfsschule northheim
vorgang an düsseldorf
rheinische kassenstelle berlin
burgdorf
kraatz
kreissozialhilfsschuss hannover land
kreissozialamt göslar
präsidium des verwaltungsbezirks
klm
bayerisches staatsministerium für arbeit und sozialordnung familie frauen und integration
kreisbehörde
reg präsident präsident des landesgerichts hannover
reg präsident präsident des verw bezirks sildeshiem
regierung arnhem
kreissozialamt gelsenkirchen
doppelmeldeamt
aurich jetzt hannover
st h 2592 g
lubliner
landesanstalt für die regelung von vermögensangelegenheiten
höhr
landesbeirat für die opfer des nationalsozialismus göttingen
doppelmeier köln berlin
st h 525 64% l
restitution authority
bundesokartei
ön
reg präsident präsident des verw bezirks oldesheim
bmf vsb
kreissozialhilfeauschuss peine
höherer kommissar der vereinigten nationen für flüchtlingsangelegenheiten
höherer kommissar der flüchtlinge
bayerisches landesamt für staatsbürgerliche angelegenheiten
niedersachsen präsident präsident des landesarchivs
ksha bückeburg
niedersachsen präsident # präsident des verwaltungsbezirks
kreissozialamt nordhausen
polizeipräsidium a d
niedersächs minister d innern
d2 4260 e 6082
an der bunseskartei
niedersachsen präsident präsident des merkverbands
niedersachsen präsident präsident des vermögensverwaltungsm
st h 1092 180l
niedersachsen präsident präsident des verw bezirks göttingen
verreinigung
az 3 v 468 b
aurich oostfriese
kreis landau
d2 6441 e 8846
wuttenstäd salzgitter
königliches sonderhilfsausschuss
bay staat anst f tr u h
köln richter pl 2 5000 köln 1
gedenkstätte
knigsamt
b 541 c 179
deutsches zentrales stelle registrierungsstelle
reg präsident präsident des verw bezirks hann neustadt
regierung bielefeld rlp
landesanstalt für die regelung von folgeleistungen
regional amtsgruppe westf
dreierhof
senat der finanzen
ksha wuttenstedt salzgitter
bundesländerkartei
regionalverwaltungsbehörde für die bundesländer bayern und baden württemberg
reg präsident präsident des zweiten bezirks hannover
deutsche rentenversicherung köln
höherer kommissar der vereinten nationen für flüchtlinge
niedersachsen reg präsidium präsident des verw bezirks sildeshiem
mecklenburg mef
eschwege
american federation of jews from central europe inc
frankfurt a m
landesbezirksstelle
niedersachsen reg präsident präsident des landes
doppelbelmldung
kreissonderhilsausschuss
sondervermögens u bautewolung
e 1758
vergütungsausschuss
holz
bayer landesarchiv
bza zeichnenlorf
kreisonderhfsausschub
kreisshilfsausschuss hannover
tr goerlader
bayerisches hauptstaatsarchiv bda
doppelmeldung berlin 5 abt
wehrmacht
landesamt für das bayerische vermögensrecht
generaldirektion service center köln
frankfurt=main
doppelmeidung
an bundeskartelle hannover
bezirksamt von köln 146688
e 2742
köln riehler pl 2 x5900 köln 1
kreissozialhilfsschule hannover land
höherer kommissar der vereinigten nationen für flüchlinge
st h 2113 h
bhf vt84 0
sozialversicherungsanstalt münchen 2 arcisstraße 11
kreisaußerhilfsausschuss aurich
ganderkesheim i wolfshagen geändert
hohes kabinett der vereinten nationen für flüchlinge
niedersachsen reg präsident präsidenten der merkmale
agriculture rosenberg wehrm
bezirksamt köln
aurich i octro
deutsches zentrales stelle für opfer der nationalsozialistischen verfolgung
nemzadik
kreissonderhilfsschuf
bvamt 10 3 70
kreisaußerhelfsausschub
shanghai gruppe
stiftung
niedersachsen präsident präsidenten des niedersächsischen landesverwaltungsgerichts
st h 2715 s
magistrat der stadt münchen
neuösterreich
niedersachsen präsident präsident des verwaltungsgerichts auriach
hauptstaatsarchiv pyrmont
regierung pommersfelden
sondervermögens und bouverwaltung
regierungsamt ansbach mfv
aesiermann amon wehr
kreis lindeu
ansbetraekkartei
zweig
roth
kreissozialamt soltau
landesbeauftragte für die vergütung von opfern des nationalsozialismus
regierungspräsident in detmold kreisverwaltung warburg der oberkreisdirektor amt für wiedergutmachung in warburg westf
reg präsident präsident des verw bezirks gießheim
hof gruenbaum
halbzeit
regierungspräsident in detmold – dezernat 14 – oberkreisdirektor – amt für wiedergutmachung – wiedenbrück
e 4u a
an bundeseskartei
aurich i oostfriesland
königreich preußen
der rechtsanwalt
wiener bundesgericht
bmf vby
bza zelelonlort
johanna irma erlanger geb 2 5 02
pol krim amt hamburg
niedersachsen reg präsident präsident des yenwo bezirks hannover
landesjustizverwaltung münchen
entschädigungsausschuss für die opfer des nationalsozialismus
landsmannschaft der verfolgten des nationalsozialismus
st h 414
regierungsbezirk rheinhessen vermögensverwaltung mainz
kreis sonderhilfsgüterschutz
landesbeirat stuttgard
lubock
tr bayerisches verfolgten
koni
kreisonderschutzbehörde ganderkesheim
e 6383
regierungsbezirk saar
sondervermögens u baubehörde köln
e rychel
kreissozialhilfsschule northeim
schwabach
u|o|k
hessen ns haftpflicht
doppelbelung berlin
kriminalamt hamburg
st h 3085 b
k51a
düsseldorfer beamtengeschäftsstelle
reg präsident des verw bezirks aurich
landeszentrale für politische opferentschädigung münchen
landesunabhängige kommission
sondervermögens u bäuererwaltung
doppelmeier münchen
höchstrat
regierungsamt münchen mf
c 1429 e 2749
botschaft der brd
reg präsident präsident des verwaltungsbezirks
hess staatsministerium kassel
finanzmittelstelle münchen
köln reichler pl 2 5000 köln 1
reg präsident präsidentenodes verw bezirks hannover
länderzentrale für die regelung von schadensersatzansprüchen
reformationsbehörde
reg präsiklement präsident des verw bezirks braunschweig
st h w89 177 k
d1 2720
regierungsbezirk trier
staatsliches institut
kshä münden
kreissozialamt celle land
doppelheldendun
ra engin bein
h a 4304
united restitution organisation frankfurt m grünburgweg 119
julius u erben
reg präsident präsident des vermögensbeziektsm
lüdenscheid
c 4247
niedersachsen präsident präsident des verwaltungsgerichtshofs hannover
reg präsident landesverwaltungsbeauftragter
km
an baundeskartei
bover landeszentrale
landeszentrale für die vergütung der opfer des nationalsozialismus
schreibstube münchen
niedersachsen präsidialt präsident des verw bezirks braunschweig
koblenz ohne nr
landesarchiv und sterbeort
sondervermögens u bäuerwaltung
königliches sonderhilfsausschub
stuttgart s haus wernigerode
bundesamt magdeburg
landesbeauftragte für die verfolgten des nationalsozialismus
rheinland
kreissozialhilfsschule wesermünde
c 2750
doppelvermerkung münchen
schreiberding
romm
dm 150
wandziolek
deutscher kulturbund
reg träsid münster
bayerisches landesamt für kriegsopfer und kriegsversehrte
wiedergutmachung für verfolgte des nationalsozialismus und deren hinterbliebenen mainz
chemnitz
kshawatenstedt salzgitter
st h 2308 d
sscheindl sala a z
e 6834
regierung münchen iii e abt
vhl eichenshtein
st maur paris 11e
kreisondeserhifsausschuss watenstedt salzgitter
landesbeirksstelle
landesstelle für die rückstellung
schweizer gülükoglu patricia
st h 1147 w
st h 1122 s
landkreis osseholtz
bonn köln
regierungsamt aachen moep
landesbezirksstelle würzburg
gastfreund
ksb
doppelbeilung münchen
büttel
korrespondenzstelle für deutschland
deutsche bundesarchiv
kreislandesamt burgdorf hann
podolask
e 4397 f 750
kreissozialamt harburg land
c 2700 d1 1518 d2 4210 d3 1920 e 6312
bayerisches landesamt für vertriebene und flüchtlinge
sécurité sociale bruxelles köln
landkreis ischl
kreisonderhlfasschü
sondervermögens u rouvier alma
bayerisches verfolgungsarchiv
regierung breslau
roßn
karlsruhe außenstelle freiburg br
deutschland
niedersachsen reg präsident präsident des verw bezirks braunschweig
bayerisches verfolgten und opferschutzamt
st h 713 s
kreissozialamt wolfenbüttel
bezirksamt von homburg 61252
stuttgart s haus waldstein 2
bayerisches landesamt für den regierungsbezirk münchen
alpern ilan chodorow wolf chodorow dagobert eigenfeld malka davidk juda hersch chodorow
entscheidende behörde reg präsidium hildesheim
reg präsident präsident des verw bezirks stadtholm
d2 3627 d3 1435 d1 3809
lia leya dupiau geb reche 17 3 32
staatsamt l g frankfurt main
köln lyon
kreisbenderhilfsausschüß
st h 3204 w
landesstelle für heimatvertriebene in münchen 2 arcisstraße
regierungsbezirk pfalz für wien berlin und rheinland
südliches bundesarchiv
bmf vt 4
st h 2314 5°
niedersachsen präsident przedkardasowex
linden
an bundeskartothek
e 7245
st h 237 r
k13
präsid des verw bezirks hildesheim
zentralanmeldestelle
tachau
st h 3011 d
härtedefonds
st h 2226
st h 2600 k
kleindeutschland präsidium berlin
niedersachsen g präsident präsident des verw bezirksxx hannover
egon levy danderyd schweden rättarens väg 14 rudolf u heinz levy
bayisches landeszentrum für die opfer des nationalsozialismus
bayrisches versicherungsamt
entschädigungsbehördeabteilung für verwaltete vermögen koblenz
münch staatsministerium
niedersachsen präsident präsidentenamt
vereinigung der verfolgten des naziregimes e v und der landesverbände
sondervermögens u kob blenz
bundesarchiv fl 22
kreissozialamt uelzen
kreissozialamt schauanburg lippe
hu
hnc
hicn
landesbeihilfe
81m
united restitution office frankfurt main grineburgweg 119
r81n
kreissozialamt landkreis grafschaft gotha
bayerisches zentralarchiv für ns opfer
kshalandkreis osterholz
südliches standesamt
reg präsident bräsidient des verw bezirke hannover
regierungsbezirk hannover
reg präsident präsidenten des verw bezirks lüneburg
5425
karlsruhe baden freiburg
tr bayerische verfolgtenkartei
niedersachsen präsident braunschweiger verwaltungsgericht
hermann schmidt
sta
ksha cloppenburg
sondervermögens u baurwaiiung
hauptzuständige stelle
austrian ministry of finance
königshausener
träumer landau
hess staatsministerium ho
kreissozialhilfsschübe nienburg
bhf vt54
niedersachsen reg präsident präsident des wiedergutmachungshauptamtes hannover
st h 6727 sch
entschädigungsbehörde für die opfer der nationalsozialistischen verfolgung karlsruhe
kda
landesstelle für die opfer des nationalsozialismus
k g 19
hohner kommissar der vereinten nationen für flüchlinge

# Swapping out single Tokens with a match distance of 1

In [16]:
def office_token_set(series):
    tokens = set()
    cleaned = (
        series.fillna("")
        .astype(str)
        .str.lower()
        .str.replace(r"\n", " ", regex=True)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )
    for name in cleaned:
        tokens.update(token for token in re.findall(r"\b\w+\b", name, flags=re.UNICODE)
            if not token.isdigit())
    return tokens

csv_tokens = office_token_set(df_csv["CompensationOffice"].apply(remove_punctuation).apply(remove_linebreak))
json_tokens = office_token_set(df_json_filtered["norm_office"])

print(f"csv_tokens: {len(csv_tokens)}")
print(f"json_tokens: {len(json_tokens)}")

csv_tokens: 354
json_tokens: 10692

In [11]:
for t in csv_tokens:
    if len(t) == 3:
        print(t)

amt
hdt
ems
186
459
dez
neu
493
170
unk
für
reg
abt
die
108
und
süd
vb4
ofd
107
159
172
der
das
des
str
bad
fin
089
lrb
127
577
min
116

In [18]:
from collections import defaultdict

csv_tokens_by_len = defaultdict(list)
for token in csv_tokens:
    if len(token) >= 3:
        csv_tokens_by_len[len(token)].append(token)

json_to_csv_distance1_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue

    candidate_tokens = (
        csv_tokens_by_len[len(json_token) - 1]
        + csv_tokens_by_len[len(json_token)]
        + csv_tokens_by_len[len(json_token) + 1]
    )

    matches_dist1 = [csv_token for csv_token in candidate_tokens if distance(json_token, csv_token) == 1]
    if matches_dist1:
        json_to_csv_distance1_map[json_token] = sorted(set(matches_dist1))

single_token_matches_dist1_len3 =sorted(
    [item for item in json_to_csv_distance1_map.items() if len(item[1]) == 1],
    key=lambda item: len(item[0])
)

print(len(single_token_matches_dist1_len3))
single_token_matches_dist1_len3

966

[('re', ['reg']),
 ('st', ['str']),
 ('rb', ['lrb']),
 ('tr', ['str']),
 ('rg', ['reg']),
 ('sr', ['str']),
 ('vb', ['vb4']),
 ('of', ['ofd']),
 ('er', ['der']),
 ('ad', ['bad']),
 ('di', ['die']),
 ('bd', ['bad']),
 ('ba', ['bad']),
 ('uk', ['unk']),
 ('ht', ['hdt']),
 ('eg', ['reg']),
 ('mi', ['min']),
 ('dt', ['hdt']),
 ('da', ['das']),
 ('b4', ['vb4']),
 ('mt', ['amt']),
 ('lr', ['lrb']),
 ('dr', ['der']),
 ('hd', ['hdt']),
 ('nu', ['neu']),
 ('fr', ['für']),
 ('as', ['das']),
 ('dz', ['dez']),
 ('hdm', ['hdt']),
 ('abh', ['abt']),
 ('vr4', ['vb4']),
 ('keg', ['reg']),
 ('baf', ['bad']),
 ('rep', ['reg']),
 ('tür', ['für']),
 ('vd4', ['vb4']),
 ('oft', ['ofd']),
 ('dhe', ['die']),
 ('for', ['für']),
 ('efd', ['ofd']),
 ('mit', ['min']),
 ('vbh', ['vb4']),
 ('ofg', ['ofd']),
 ('per', ['der']),
 ('ub4', ['vb4']),
 ('wür', ['für']),
 ('db4', ['vb4']),
 ('and', ['und']),
 ('beg', ['reg']),
 ('lr8', ['lrb']),
 ('stg', ['str']),
 ('new', ['neu']),
 ('bau', ['bad']),
 ('fln', ['fin']),
 ('ref', ['reg']),
 ('vba', ['vb4']),
 ('fun', ['fin']),
 ('ddr', ['der']),
 ('doz', ['dez']),
 ('ger', ['der']),
 ('off', ['ofd']),
 ('oed', ['ofd']),
 ('vb3', ['vb4']),
 ('dcr', ['der']),
 ('krb', ['lrb']),
 ('ber', ['der']),
 ('mün', ['min']),
 ('her', ['der']),
 ('lüb', ['lrb']),
 ('rbg', ['reg']),
 ('lro', ['lrb']),
 ('eb4', ['vb4']),
 ('sta', ['str']),
 ('köl', ['köln']),
 ('sod', ['süd']),
 ('diö', ['die']),
 ('lbb', ['lrb']),
 ('ojd', ['ofd']),
 ('lab', ['lrb']),
 ('vt4', ['vb4']),
 ('ovd', ['ofd']),
 ('lie', ['die']),
 ('kad', ['bad']),
 ('dat', ['das']),
 ('rad', ['bad']),
 ('ord', ['ofd']),
 ('bam', ['bad']),
 ('uok', ['unk']),
 ('feg', ['reg']),
 ('hss', ['hess']),
 ('stv', ['str']),
 ('okd', ['ofd']),
 ('ubt', ['abt']),
 ('ier', ['der']),
 ('har', ['harz']),
 ('rey', ['reg']),
 ('v34', ['vb4']),
 ('rog', ['reg']),
 ('bar', ['bad']),
 ('stl', ['str']),
 ('lre', ['lrb']),
 ('abg', ['abt']),
 ('opd', ['ofd']),
 ('dme', ['die']),
 ('ges', ['des']),
 ('öln', ['köln']),
 ('stm', ['str']),
 ('trb', ['lrb']),
 ('bay', ['bad']),
 ('ami', ['amt']),
 ('ofs', ['ofd']),
 ('mii', ['min']),
 ('baw', ['bad']),
 ('bmt', ['amt']),
 ('stf', ['str']),
 ('fur', ['für']),
 ('dor', ['der']),
 ('lfd', ['ofd']),
 ('wes', ['des']),
 ('bav', ['bad']),
 ('brd', ['bad']),
 ('weg', ['reg']),
 ('ver', ['der']),
 ('qfd', ['ofd']),
 ('crb', ['lrb']),
 ('bak', ['bad']),
 ('mad', ['bad']),
 ('hst', ['hdt']),
 ('end', ['und']),
 ('hdn', ['hdt']),
 ('prs', ['präs']),
 ('lkb', ['lrb']),
 ('hdi', ['hdt']),
 ('rug', ['reg']),
 ('cas', ['das']),
 ('bod', ['bad']),
 ('rig', ['reg']),
 ('bie', ['die']),
 ('vc4', ['vb4']),
 ('vby', ['vb4']),
 ('bez', ['dez']),
 ('nec', ['neu']),
 ('rea', ['reg']),
 ('bah', ['bad']),
 ('lad', ['bad']),
 ('v84', ['vb4']),
 ('lüd', ['süd']),
 ('lra', ['lrb']),
 ('ind', ['und']),
 ('wie', ['die']),
 ('old', ['ofd']),
 ('läb', ['lrb']),
 ('xes', ['des']),
 ('ofr', ['ofd']),
 ('ib4', ['vb4']),
 ('ofo', ['ofd']),
 ('wtr', ['str']),
 ('bes', ['des']),
 ('kln', ['köln']),
 ('amf', ['amt']),
 ('kön', ['köln']),
 ('peg', ['reg']),
 ('erb', ['lrb']),
 ('köla', ['köln']),
 ('pres', ['präs']),
 ('keln', ['köln']),
 ('bayr', ['bayer']),
 ('miel', ['kiel']),
 ('kein', ['keine']),
 ('k5ln', ['köln']),
 ('höss', ['hess']),
 ('pltz', ['platz']),
 ('trie', ['trier']),
 ('kaln', ['köln']),
 ('pris', ['präs']),
 ('hees', ['hess']),
 ('vba4', ['vb4']),
 ('born', ['bonn']),
 ('wetf', ['westf']),
 ('371v', ['37iv']),
 ('oftd', ['ofd']),
 ('bann', ['bonn']),
 ('aöln', ['köln']),
 ('völn', ['köln']),
 ('palz', ['pfalz']),
 ('mein', ['min']),
 ('fund', ['und']),
 ('pras', ['präs']),
 ('röln', ['köln']),
 ('marz', ['harz']),
 ('trer', ['trier']),
 ('vbs4', ['vb4']),
 ('halz', ['harz']),
 ('wstf', ['westf']),
 ('pflz', ['pfalz']),
 ('lecr', ['leer']),
 ('lnrb', ['lrb']),
 ('hcss', ['hess']),
 ('mark', ['markt']),
 ('stat', ['stadt']),
 ('maiz', ['mainz']),
 ('pfaz', ['pfalz']),
 ('hund', ['und']),
 ('oder', ['der']),
 ('viel', ['kiel']),
 ('kess', ['hess']),
 ('kiln', ['köln']),
 ('döln', ['köln']),
 ('bohn', ['bonn']),
 ('west', ['westf']),
 ('frei', ['freie']),
 ('wess', ['hess']),
 ('amft', ['amt']),
 ('tier', ['trier']),
 ('kölñ', ['köln']),
 ('ostr', ['str']),
 ('höln', ['köln']),
 ('bona', ['bonn']),
 ('m8in', ['min']),
 ('wesf', ['westf']),
 ('eder', ['der']),
 ('trir', ['trier']),
 ('kölz', ['köln']),
 ('neve', ['neue']),
 ('ampt', ['amt']),
 ('jöln', ['köln']),
 ('vtb4', ['vb4']),
 ('aemt', ['amt']),
 ('koln', ['köln']),
 ('less', ['hess']),
 ('ster', ['str']),
 ('böln', ['köln']),
 ('falz', ['pfalz']),
 ('amth', ['amt']),
 ('hest', ['hess']),
 ('amnt', ['amt']),
 ('nöln', ['köln']),
 ('k3ln', ['köln']),
 ('361v', ['36iv']),
 ('seer', ['leer']),
 ('stdt', ['stadt']),
 ('moin', ['min']),
 ('manz', ['mainz']),
 ('k6ln', ['köln']),
 ('mess', ['hess']),
 ('k8ln', ['köln']),
 ('amat', ['amt']),
 ('amts', ['amt']),
 ('möln', ['köln']),
 ('amit', ['amt']),
 ('brak', ['brake']),
 ('patz', ['platz']),
 ('uöln', ['köln']),
 ('bönn', ['bonn']),
 ('fink', ['fin']),
 ('peer', ['leer']),
 ('ivb4', ['vb4']),
 ('bund', ['und']),
 ('präz', ['präs']),
 ('präf', ['präs']),
 ('plaz', ['platz']),
 ('mink', ['min']),
 ('herz', ['harz']),
 ('ness', ['hess']),
 ('baud', ['bad']),
 ('bayem', ['bayer']),
 ('nainz', ['mainz']),
 ('wesff', ['westf']),
 ('karte', ['kartei']),
 ('staat', ['stadt']),
 ('westr', ['westf']),
 ('westw', ['westf']),
 ('städt', ['stadt']),
 ('triel', ['trier']),
 ('payer', ['bayer']),
 ('westl', ['westf']),
 ('mains', ['mainz']),
 ('neuer', ['neue']),
 ('mahnz', ['mainz']),
 ('freib', ['freie']),
 ('weltf', ['westf']),
 ('mayer', ['bayer']),
 ('wcstf', ['westf']),
 ('trieß', ['trier']),
 ('kölin', ['köln']),
 ('tröer', ['trier']),
 ('ptalz', ['pfalz']),
 ('westu', ['westf']),
 ('stödt', ['stadt']),
 ('pfölz', ['pfalz']),
 ('mannz', ['mainz']),
 ('remen', ['bremen']),
 ('westi', ['westf']),
 ('pratz', ['platz']),
 ('ereis', ['kreis']),
 ('pfälz', ['pfalz']),
 ('weste', ['westf']),
 ('colle', ['celle']),
 ('frier', ['trier']),
 ('bayor', ['bayer']),
 ('kelle', ['celle']),
 ('glatz', ['platz']),
 ('buyer', ['bayer']),
 ('mairz', ['mainz']),
 ('aaden', ['baden']),
 ('esamt', ['samt']),
 ('köln2', ['köln']),
 ('westt', ['westf']),
 ('maink', ['mainz']),
 ('lands', ['landes']),
 ('bayes', ['bayer']),
 ('efurt', ['erfurt']),
 ('trher', ['trier']),
 ('neues', ['neue']),
 ('präsd', ['präs']),
 ('plitz', ['platz']),
 ('trüer', ['trier']),
 ('neuss', ['heuss']),
 ('triar', ['trier']),
 ('pfalt', ['pfalz']),
 ('ireis', ['kreis']),
 ('plötz', ['platz']),
 ('straß', ['straße']),
 ('kasse', ['kassel']),
 ('maina', ['mainz']),
 ('boyer', ['bayer']),
 ('marie', ['maria']),
 ('piatz', ['platz']),
 ('plaiz', ['platz']),
 ('meinz', ['mainz']),
 ('phalz', ['pfalz']),
 ('trler', ['trier']),
 ('krois', ['kreis']),
 ('neuen', ['neue']),
 ('pfals', ['pfalz']),
 ('essen', ['hessen']),
 ('maine', ['mainz']),
 ('melle', ['celle']),
 ('westp', ['westf']),
 ('blatz', ['platz']),
 ('mäinz', ['mainz']),
 ('pialz', ['pfalz']),
 ('siadt', ['stadt']),
 ('trien', ['trier']),
 ('gelle', ['celle']),
 ('state', ['stade']),
 ('kreix', ['kreis']),
 ('bunde', ['bundes']),
 ('tries', ['trier']),
 ('plätz', ['platz']),
 ('tríer', ['trier']),
 ('boann', ['bonn']),
 ('rayer', ['bayer']),
 ('fayer', ['bayer']),
 ('yelle', ['celle']),
 ('pralz', ['pfalz']),
 ('platt', ['platz']),
 ('pfaiz', ['pfalz']),
 ('mcinz', ['mainz']),
 ('mainsz', ['mainz']),
 ('triier', ['trier']),
 ('plaatz', ['platz']),
 ('pfaltz', ['pfalz']),
 ('karten', ['kartei']),
 ('fragen', ['frauen']),
 ('bremem', ['bremen']),
 ('ländes', ['landes']),
 ('tröier', ['trier']),
 ('auvich', ['aurich']),
 ('hessei', ['hessen']),
 ('kreise', ['kreis']),
 ('münden', ['minden']),
 ('lindau', ['landau']),
 ('dkreis', ['kreis']),
 ('hachen', ['aachen']),
 ('triber', ['trier']),
 ('brauke', ['brake']),
 ('kärtei', ['kartei']),
 ('bürgbr', ['bürger']),
 ('kirche', ['kirchen']),
 ('maintz', ['mainz']),
 ('sozial', ['soziale']),
 ('triern', ['trier']),
 ('weinsr', ['weinstr']),
 ('kassal', ['kassel']),
 ('grafsh', ['grafsch']),
 ('bremer', ['bremen']),
 ('borger', ['bürger']),
 ('kasse1', ['kassel']),
 ('iplatz', ['platz']),
 ('hremen', ['bremen']),
 ('amburg', ['hamburg']),
 ('neuied', ['neuwied']),
 ('kassei', ['kassel']),
 ('munden', ['minden']),
 ('minder', ['minden']),
 ('rheinl', ['rhein']),
 ('etmold', ['detmold']),
 ('berger', ['bürger']),
 ('aachan', ['aachen']),
 ('innere', ['innern']),
 ('messen', ['hessen']),
 ('aadhen', ['aachen']),
 ('göslar', ['goslar']),
 ('nessen', ['hessen']),
 ('menden', ['minden']),
 ('aremen', ['bremen']),
 ('trieer', ['trier']),
 ('bracke', ['brake']),
 ('beglin', ['berlin']),
 ('ustadt', ['stadt']),
 ('einstr', ['weinstr']),
 ('weinst', ['weinstr']),
 ('plaetz', ['platz']),
 ('herlin', ['berlin']),
 ('trizer', ['trier']),
 ('bumdes', ['bundes']),
 ('triers', ['trier']),
 ('brakel', ['brake']),
 ('tremen', ['bremen']),
 ('linden', ['minden']),
 ('trirer', ['trier']),
 ('landos', ['landes']),
 ('träier', ['trier']),
 ('gerlin', ['berlin']),
 ('kartel', ['kartei']),
 ('kolenz', ['koblenz']),
 ('detmol', ['detmold']),
 ('trüier', ['trier']),
 ('arburg', ['warburg']),
 ('oblenz', ['koblenz']),
 ('triver', ['trier']),
 ('jenner', ['jenaer']),
 ('neusadt', ['neustadt']),
 ('graisch', ['grafsch']),
 ('munchen', ['münchen']),
 ('hünster', ['münster']),
 ('keblenz', ['koblenz']),
 ('weinsfr', ['weinstr']),
 ('detmola', ['detmold']),
 ('koblinz', ['koblenz']),
 ('kassels', ['kassel']),
 ('gratsch', ['grafsch']),
 ('ko3lenz', ['koblenz']),
 ('rnsberg', ['arnsberg']),
 ('reiburg', ['freiburg']),
 ('inneren', ['innern']),
 ('8arburg', ['warburg']),
 ('betmold', ['detmold']),
 ('auriach', ['aurich']),
 ('berlins', ['berlin']),
 ('wernstr', ['weinstr']),
 ('dzernat', ['dezernat']),
 ('monster', ['münster']),
 ('marburg', ['warburg']),
 ('sociale', ['soziale']),
 ('köblenz', ['koblenz']),
 ('noblenz', ['koblenz']),
 ('kobleuz', ['koblenz']),
 ('annover', ['hannover']),
 ('garburg', ['warburg']),
 ('koblenc', ['koblenz']),
 ('koblonz', ['koblenz']),
 ('dezerna', ['dezernat']),
 ('neumark', ['neumarkt']),
 ('delmold', ['detmold']),
 ('koblanz', ['koblenz']),
 ('woblenz', ['koblenz']),
 ('deimold', ['detmold']),
 ('hoblenz', ['koblenz']),
 ('landesk', ['landes']),
 ('weisstr', ['weinstr']),
 ('weimstr', ['weinstr']),
 ('jetmold', ['detmold']),
 ('kassell', ['kassel']),
 ('bundesk', ['bundes']),
 ('ansberg', ['arnsberg']),
 ('feiburg', ['freiburg']),
 ('bremens', ['bremen']),
 ('petmold', ['detmold']),
 ('barburg', ['warburg']),
 ('cattbus', ['cottbus']),
 ('vermöge', ['vermögen']),
 ('weißstr', ['weinstr']),
 ('neuried', ['neuwied']),
 ('kohlenz', ['koblenz']),
 ('munster', ['münster']),
 ('hanover', ['hannover']),
 ('werburg', ['warburg']),
 ('dotmold', ['detmold']),
 ('darburg', ['warburg']),
 ('hesssen', ['hessen']),
 ('rishler', ['riehler']),
 ('nustadt', ['neustadt']),
 ('koblens', ['koblenz']),
 ('wetmold', ['detmold']),
 ('goslars', ['goslar']),
 ('arnberg', ['arnsberg']),
 ('defmold', ['detmold']),
 ('frauend', ['frauen']),
 ('bayerns', ['bayern']),
 ('weinsir', ['weinstr']),
 ('bamburg', ['hamburg']),
 ('goslari', ['goslar']),
 ('roblenz', ['koblenz']),
 ('wazburg', ['warburg']),
 ('richler', ['riehler']),
 ('homburg', ['hamburg']),
 ('ukoblenz', ['koblenz']),
 ('oldeburg', ['oldenburg']),
 ('prnsberg', ['arnsberg']),
 ('räsident', ['präsident']),
 ('sharburg', ['saarburg']),
 ('arnswerg', ['arnsberg']),
 ('behörden', ['behörde']),
 ('meustadt', ['neustadt']),
 ('reinland', ['rheinland']),
 ('armsberg', ['arnsberg']),
 ('chamnitz', ['chemnitz']),
 ('arnsherg', ['arnsberg']),
 ('göttigen', ['göttingen']),
 ('finanzan', ['finanzen']),
 ('preiburg', ['freiburg']),
 ('heinland', ['rheinland']),
 ('ostfrsld', ['ostfrld']),
 ('arnsoerg', ['arnsberg']),
 ('arasberg', ['arnsberg']),
 ('arnsborg', ['arnsberg']),
 ('arnoberg', ['arnsberg']),
 ('hensberg', ['heinsberg']),
 ('tubingen', ['tübingen']),
 ('karlruhe', ['karlsruhe']),
 ('bannover', ['hannover']),
 ('koblensz', ['koblenz']),
 ('dmzernat', ['dezernat']),
 ('degernat', ['dezernat']),
 ('searburg', ['saarburg']),
 ('neussadt', ['neustadt']),
 ('kobllenz', ['koblenz']),
 ('neuwiedt', ['neuwied']),
 ('arnßberg', ['arnsberg']),
 ('arnaberg', ['arnsberg']),
 ('orehbahn', ['drehbahn']),
 ('riehlner', ['riehler']),
 ('arnsbera', ['arnsberg']),
 ('hinsberg', ['heinsberg']),
 ('einsberg', ['heinsberg']),
 ('lezernat', ['dezernat']),
 ('desernat', ['dezernat']),
 ('tübinger', ['tübingen']),
 ('karsruhe', ['karlsruhe']),
 ('freiberg', ['freiburg']),
 ('darstadt', ['darmstadt']),
 ('arbeitss', ['arbeits']),
 ('beustadt', ['neustadt']),
 ('präsidet', ['präsident']),
 ('aunsberg', ['arnsberg']),
 ('stutgart', ['stuttgart']),
 ('naustadt', ['neustadt']),
 ('arnsperg', ['arnsberg']),
 ('finanzsn', ['finanzen']),
 ('tobingen', ['tübingen']),
 ('arosberg', ['arnsberg']),
 ('andesamt', ['landesamt']),
 ('neystadt', ['neustadt']),
 ('töbingen', ['tübingen']),
 ('nenstadt', ['neustadt']),
 ('hrnsberg', ['arnsberg']),
 ('drahbahn', ['drehbahn']),
 ('westfale', ['westfalen']),
 ('graftsch', ['grafsch']),
 ('ainsberg', ['arnsberg']),
 ('amnsberg', ['arnsberg']),
 ('zentrale', ['zentral']),
 ('weinsstr', ['weinstr']),
 ('landsamt', ['landesamt']),
 ('vermöger', ['vermögen']),
 ('koblencz', ['koblenz']),
 ('präsidnt', ['präsident']),
 ('helstedt', ['helmstedt']),
 ('soarburg', ['saarburg']),
 ('paarburg', ['saarburg']),
 ('neustadi', ['neustadt']),
 ('grafisch', ['grafsch']),
 ('newstadt', ['neustadt']),
 ('wartburg', ['warburg']),
 ('finanzon', ['finanzen']),
 ('riehlker', ['riehler']),
 ('heustadt', ['neustadt']),
 ('säarburg', ['saarburg']),
 ('mannover', ['hannover']),
 ('frnsberg', ['arnsberg']),
 ('arneberg', ['arnsberg']),
 ('baarburg', ['saarburg']),
 ('aensberg', ['arnsberg']),
 ('koblentz', ['koblenz']),
 ('sparburg', ['saarburg']),
 ('finanzer', ['finanzen']),
 ('kalsruhe', ['karlsruhe']),
 ('behördet', ['behörde']),
 ('vormögen', ['vermögen']),
 ('kaarburg', ['saarburg']),
 ('osteroede', ['osterode']),
 ('bezirkamt', ['bezirksamt']),
 ('osmabrück', ['osnabrück']),
 ('manistrat', ['magistrat']),
 ('arnnsberg', ['arnsberg']),
 ('rogierung', ['regierung']),
 ('hiesbaden', ['wiesbaden']),
 ('uldenburg', ['oldenburg']),
 ('ländesamt', ['landesamt']),
 ('kürlsruhe', ['karlsruhe']),
 ('landssamt', ['landesamt']),
 ('härtfonds', ['härtefonds']),
 ('prasident', ['präsident']),
 ('karlshuhe', ['karlsruhe']),
 ('holmstedt', ['helmstedt']),
 ('franzfurt', ['frankfurt']),
 ('staarburg', ['saarburg']),
 ('oltenburg', ['oldenburg']),
 ('alstädter', ['altstädter']),
 ('bayrische', ['bayerische']),
 ('detzernat', ['dezernat']),
 ('neuostadt', ['neustadt']),
 ('beroldung', ['besoldung']),
 ('dexzernat', ['dezernat']),
 ('schauburg', ['schaumburg']),
 ('präsidenz', ['präsident']),
 ('freiburgi', ['freiburg']),
 ('ostereode', ['osterode']),
 ('ersorgung', ['versorgung']),
 ('aegierung', ['regierung']),
 ('hätefonds', ['härtefonds']),
 ('nordboden', ['nordbaden']),
 ('weinsberg', ['heinsberg']),
 ('aernsberg', ['arnsberg']),
 ('cldenburg', ['oldenburg']),
 ('hildeheim', ['hildesheim']),
 ('verwaltet', ['verwaltete']),
 ('maristrat', ['magistrat']),
 ('wienbaden', ['wiesbaden']),
 ('arnswberg', ['arnsberg']),
 ('ahrnsberg', ['arnsberg']),
 ('arnsoberg', ['arnsberg']),
 ('ezirksamt', ['bezirksamt']),
 ('kheinland', ['rheinland']),
 ('président', ['präsident']),
 ('bayersche', ['bayerische']),
 ('finanzsen', ['finanzen']),
 ('regierang', ['regierung']),
 ('nordbuden', ['nordbaden']),
 ('heineberg', ['heinsberg']),
 ('derzernat', ['dezernat']),
 ('theinland', ['rheinland']),
 ('osnabruck', ['osnabrück']),
 ('veraltete', ['verwaltete']),
 ('präsidenc', ['präsident']),
 ('uneustadt', ['neustadt']),
 ('westfales', ['westfalen']),
 ('harnsberg', ['arnsberg']),
 ('president', ['präsident']),
 ('reyierung', ['regierung']),
 ('niesbaden', ['wiesbaden']),
 ('aarnsberg', ['arnsberg']),
 ('kärlsruhe', ['karlsruhe']),
 ('finanzzen', ['finanzen']),
 ('ministers', ['minister']),
 ('arnstberg', ['arnsberg']),
 ('kurlsruhe', ['karlsruhe']),
 ('bezirksam', ['bezirksamt']),
 ('weinsteig', ['weinsteige']),
 ('drehrbahn', ['drehbahn']),
 ('stuttgard', ['stuttgart']),
 ('seaarburg', ['saarburg']),
 ('karlscuhe', ['karlsruhe']),
 ('vermögens', ['vermögen']),
 ('rheinländ', ['rheinland']),
 ('farnsberg', ['arnsberg']),
 ('weilstraße', ['weinstraße']),
 ('desseldorf', ['düsseldorf']),
 ('bayedische', ['bayerische']),
 ('woinsteige', ['weinsteige']),
 ('bexirksamt', ['bezirksamt']),
 ('schäumburg', ['schaumburg']),
 ('leinstraße', ['weinstraße']),
 ('karlsruhes', ['karlsruhe']),
 ('mayerische', ['bayerische']),
 ('bildesheim', ['hildesheim']),
 ('helmsstedt', ['helmstedt']),
 ('bazirksamt', ['bezirksamt']),
 ('spinkenhof', ['sprinkenhof']),
 ('bayetische', ['bayerische']),
 ('regierungs', ['regierung']),
 ('präsidentk', ['präsident']),
 ('spräsident', ['präsident']),
 ('göttlingen', ['göttingen']),
 ('härtetonds', ['härtefonds']),
 ('osanabrück', ['osnabrück']),
 ('bozirksamt', ['bezirksamt']),
 ('zuständige', ['zuständig']),
 ('karlshruhe', ['karlsruhe']),
 ('besirksamt', ['bezirksamt']),
 ('bayesische', ['bayerische']),
 ('präsidenat', ['präsident']),
 ('osnaubrück', ['osnabrück']),
 ('ministerie', ['ministerin']),
 ('bosnabrück', ['osnabrück']),
 ('registatur', ['registratur']),
 ('präsidenta', ['präsident']),
 ('dezirksamt', ['bezirksamt']),
 ('landeesamt', ['landesamt']),
 ('payerische', ['bayerische']),
 ('sildesheim', ['hildesheim']),
 ('ayerisches', ['bayerisches']),
 ('jüsseldorf', ['düsseldorf']),
 ('bézirksamt', ['bezirksamt']),
 ('verfolgten', ['verfolgte']),
 ('bekirksamt', ['bezirksamt']),
 ('dusseldorf', ['düsseldorf']),
 ('götttingen', ['göttingen']),
 ('arcistraße', ['arcisstraße']),
 ('nördlicher', ['nördliche']),
 ('karlsruher', ['karlsruhe']),
 ('vorwaltete', ['verwaltete']),
 ('verfolgter', ['verfolgte']),
 ('gildesheim', ['hildesheim']),
 ('verwalteta', ['verwaltete']),
 ('schaußburg', ['schaumburg']),
 ('weimsteige', ['weinsteige']),
 ('rheinlande', ['rheinland']),
 ('präsidient', ['präsident']),
 ('präsident7', ['präsident']),
 ('bayrisches', ['bayerisches']),
 ('lezirksamt', ['bezirksamt']),
 ('düsseldort', ['düsseldorf']),
 ('weinstrabe', ['weinstraße']),
 ('auerstraße', ['auestraße']),
 ('weinsteine', ['weinsteige']),
 ('xpräsident', ['präsident']),
 ('hartefonds', ['härtefonds']),
 ('sayerische', ['bayerische']),
 ('landesamts', ['landesamt']),
 ('bayersches', ['bayerisches']),
 ('landessamt', ['landesamt']),
 ('verwaltets', ['verwaltete']),
 ('sarbrücken', ['saarbrücken']),
 ('rheinsberg', ['heinsberg']),
 ('weinsteigo', ['weinsteige']),
 ('verwalteto', ['verwaltete']),
 ('hikdesheim', ['hildesheim']),
 ('bäzirksamt', ['bezirksamt']),
 ('müsseldorf', ['düsseldorf']),
 ('büsseldorf', ['düsseldorf']),
 ('weinsteire', ['weinsteige']),
 ('landsesamt', ['landesamt']),
 ('verfolgtes', ['verfolgte']),
 ('söarbrücken', ['saarbrücken']),
 ('benzirksamt', ['bezirksamt']),
 ('verwaltetes', ['verwaltete']),
 ('bremenhaven', ['bremerhaven']),
 ('sprenkenhof', ['sprinkenhof']),
 ('verwalteter', ['verwaltete']),
 ('bayetisches', ['bayerisches']),
 ('schnaumburg', ['schaumburg']),
 ('bayernische', ['bayerische']),
 ('ministerien', ['ministerin']),
 ('weinsstraße', ['weinstraße']),
 ('bayernsches', ['bayerisches']),
 ('bezirkssamt', ['bezirksamt']),
 ('meisestraße', ['meiserstraße']),
 ('haildesheim', ['hildesheim']),
 ('schlaumburg', ['schaumburg']),
 ('sprintenhof', ['sprinkenhof']),
 ('düsseldorff', ['düsseldorf']),
 ('nayerisches', ['bayerisches']),
 ('schauumburg', ['schaumburg']),
 ('springenhof', ['sprinkenhof']),
 ('härttefonds', ['härtefonds']),
 ('payerisches', ['bayerisches']),
 ('bezirksamts', ['bezirksamt']),
 ('verwalteten', ['verwaltete']),
 ('verwaltgete', ['verwaltete']),
 ('düesseldorf', ['düsseldorf']),
 ('schauemburg', ['schaumburg']),
 ('rayerisches', ['bayerisches']),
 ('düsseldorft', ['düsseldorf']),
 ('registrator', ['registratur']),
 ('beezirksamt', ['bezirksamt']),

In [19]:
unique_distance1_token_map = {
    json_token: csv_candidates[0]
    for json_token, csv_candidates in json_to_csv_distance1_map.items()
    if len(csv_candidates) == 1
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_json_filtered['CompensationOffice_token_swap'] = df_json_filtered['norm_office'].apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_json_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['norm_office'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 966

,CompensationOffice1,MatchedOffice,MatchDistance
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,7.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,3.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,2.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,NaN,NaN
16,bundeskartei,NaN,NaN
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,3.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,NaN,NaN
20,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,6.0
21,hess staatsministerium,NaN,NaN

In [20]:
total = len(df_matches_token_swap)
max_dist = int(df_matches_token_swap['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches_token_swap['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 12792 (3.64%)
MatchDistance = 1: 21227 (6.04%)
MatchDistance = 2: 11203 (3.19%)
MatchDistance = 3: 20804 (5.92%)
MatchDistance = 4: 41702 (11.87%)
MatchDistance = 5: 9182 (2.61%)
MatchDistance = 6: 23788 (6.77%)
MatchDistance = 7: 4670 (1.33%)
MatchDistance = 8: 6243 (1.78%)
MatchDistance = 9: 22337 (6.36%)
MatchDistance = 10: 3547 (1.01%)
MatchDistance = 11: 3583 (1.02%)
MatchDistance = 12: 10961 (3.12%)
MatchDistance = 13: 3567 (1.02%)
MatchDistance = 14: 2843 (0.81%)
MatchDistance = 15: 2780 (0.79%)
MatchDistance = 16: 2670 (0.76%)
MatchDistance = 17: 2328 (0.66%)
MatchDistance = 18: 2979 (0.85%)
MatchDistance = 19: 15769 (4.49%)
MatchDistance = 20: 3547 (1.01%)
MatchDistance = 21: 1501 (0.43%)
MatchDistance = 22: 1430 (0.41%)
MatchDistance = 23: 18083 (5.15%)
MatchDistance = 24: 1149 (0.33%)
MatchDistance = 25: 539 (0.15%)
MatchDistance = 26: 247 (0.07%)
MatchDistance = 27: 521 (0.15%)
MatchDistance = 28: 993 (0.28%)
MatchDistance = 29: 1717 (0.49%)
MatchDistance = 30: 380 (0.11%)
MatchDistance = 31: 486 (0.14%)
MatchDistance = 32: 253 (0.07%)
MatchDistance = 33: 809 (0.23%)
MatchDistance = 34: 69 (0.02%)
MatchDistance = 35: 71 (0.02%)
MatchDistance = 36: 31 (0.01%)
MatchDistance = 37: 44 (0.01%)
MatchDistance = 38: 22 (0.01%)
MatchDistance = 39: 37 (0.01%)
MatchDistance = 40: 37 (0.01%)
MatchDistance = 41: 9 (0.00%)
MatchDistance = 42: 15 (0.00%)
MatchDistance = 43: 7 (0.00%)
MatchDistance = 44: 11 (0.00%)
MatchDistance = 45: 8 (0.00%)
MatchDistance = 46: 8 (0.00%)
MatchDistance = 47: 9 (0.00%)
MatchDistance = 48: 6 (0.00%)
MatchDistance = 49: 1 (0.00%)
MatchDistance = 50: 2 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 3 (0.00%)
MatchDistance = 53: 1 (0.00%)
MatchDistance = 54: 4 (0.00%)
MatchDistance = 55: 13 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 2 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 8 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 0 (0.00%)
MatchDistance = 64: 1 (0.00%)

In [21]:
def token_count(s):
    return len(str(s).split())

extracted_longer = sorted(
    {
        (str(a), str(b))
        for a, b in zip(df_matches_token_swap['CompensationOffice1'], df_matches_token_swap['MatchedOffice'])
        if token_count(a) > token_count(b) and str(b) != 'nan'
    },
    key=lambda item: token_count(item[0])
)

extracted_longer

[('hannover köln', 'hannover'),
 ('ksha münchen', 'münchen'),
 ('lg köln', 'köln'),
 ('lg hamburg', 'hamburg'),
 ('neu stadt', 'neustadt'),
 ('bfj berlin', 'berlin'),
 ('führer koblenz', 'koblenz'),
 ('neustadt 484945', 'neustadt'),
 ('köln hamburg', 'hamburg'),
 ('münchen bürgbr', 'münchen'),
 ('köln düsseldorf', 'düsseldorf'),
 ('ksha nordern', 'hannover'),
 ('hannover löd', 'hannover'),
 ('ksh stade', 'stade'),
 ('ovd berlin', 'berlin'),
 ('oldeburg oldb', 'oldenburg'),
 ('oed koblenz', 'koblenz'),
 ('neu neustadt', 'neustadt'),
 ('ofo berlin', 'berlin'),
 ('aegyung aensberg', 'arnsberg'),
 ('nrw tüssleldorf', 'düsseldorf'),
 ('braunschweig mascherode', 'braunschweig'),
 ('neustadt pk', 'neustadt'),
 ('braunschweig ii', 'braunschweig'),
 ('hfa berlin', 'berlin'),
 ('mainz neustadt', 'neustadt'),
 ('tries neustadt', 'neustadt'),
 ('hannover fund', 'hannover'),
 ('stl desheim', 'hildesheim'),
 ('rp düsseldorf', 'düsseldorf'),
 ('münchen beg', 'münchen'),
 ('bayern dt', 'bayern'),
 ('ksha darmstadt', 'darmstadt'),
 ('amt köln', 'köln'),
 ('stuttgart et5770', 'stuttgart'),
 ('träger koblentz', 'koblenz'),
 ('va hamburg', 'hamburg'),
 ('lg münchen', 'münchen'),
 ('bfz berlin', 'berlin'),
 ('münchen 91519', 'münchen'),
 ('barburg neustadt', 'neustadt'),
 ('ra reppenhagen', 'bremerhaven'),
 ('bayerische landesregierung', 'bezirksregierung'),
 ('main z', 'mainz'),
 ('saarburg berlin', 'saarbrücken'),
 ('ansl amtdüsseldorf', 'düsseldorf'),
 ('in detmold', 'detmold'),
 ('k sln', 'köln'),
 ('ojj münster', 'münster'),
 ('lvh hamburg', 'hamburg'),
 ('lva hamburg', 'hamburg'),
 ('kreis limburg', 'freiburg'),
 ('arnsberg köln', 'arnsberg'),
 ('ksha lüneburg', 'lüneburg'),
 ('nds braunschweig', 'braunschweig'),
 ('iva hamburg', 'hamburg'),
 ('stuttgart freiburg', 'stuttgart'),
 ('an niedersachsen', 'niedersachsen'),
 ('w köln', 'köln'),
 ('trier saarburg', 'saarburg'),
 ('an stade', 'stade'),
 ('bayern düsseldorf', 'düsseldorf'),
 ('oftd münchen', 'münchen'),
 ('ovd köln', 'köln'),
 ('uoy köln', 'köln'),
 ('lwa düsseldorf', 'düsseldorf'),
 ('oft köl', 'köln'),
 ('stadt bremerhaven', 'bremerhaven'),
 ('ovd düsseldorf', 'düsseldorf'),
 ('oftd berlin', 'berlin'),
 ('oldenburg oldbg', 'oldenburg'),
 ('uro berlin', 'berlin'),
 ('mainz a', 'mainz'),
 ('k5 n', 'köln'),
 ('münchner eg', 'münchen'),
 ('s arburg', 'saarburg'),
 ('reg braunschweig', 'braunschweig'),
 ('bayerische staatsregierung', 'bezirksregierung'),
 ('lg hannover', 'hannover'),
 ('bva köln', 'köln'),
 ('köln münchen', 'münchen'),
 ('ofd düsseldorf', 'düsseldorf'),
 ('köln lva', 'köln'),
 ('hess lka', 'hessen'),
 ('ka hamburg', 'hamburg'),
 ('aurich niedersachsen', 'niedersachsen'),
 ('afw essen', 'hessen'),
 ('k8m düsseldorf', 'düsseldorf'),
 ('betrifft regierung', 'bezirksregierung'),
 ('ksha osnabrück', 'osnabrück'),
 ('lka münchen', 'münchen'),
 ('landkreis braunschweig', 'braunschweig'),
 ('eb düsseldorf', 'düsseldorf'),
 ('lvg hamburg', 'hamburg'),
 ('braunschweig 19', 'braunschweig'),
 ('hann lüb', 'hannover'),
 ('saarburg trier', 'saarburg'),
 ('ksha niedersachsen', 'niedersachsen'),
 ('bayern münchen', 'münchen'),
 ('lg darmstadt', 'darmstadt'),
 ('oed berlin', 'berlin'),
 ('hamburg land', 'hamburg'),
 ('trier koblenz', 'koblenz'),
 ('nva hamburg', 'hamburg'),
 ('amt bremen', 'bremen'),
 ('cva düsseldorf', 'düsseldorf'),
 ('hva hamburg', 'hamburg'),
 ('ksha würzburg', 'saarburg'),
 ('ksha hildesheim', 'hildesheim'),
 ('aurich osnabrück', 'osnabrück'),
 ('wga berlin', 'berlin'),
 ('ksha bremen', 'bremen'),
 ('köln arnsberg', 'arnsberg'),
 ('stuttgart mainz', 'stuttgart'),
 ('an bremen', 'bremen'),
 ('karl wolke', 'karlsruhe'),
 ('kiel t51', 'kiel'),
 ('braunschweig hannover', 'braunschweig'),
 ('ksha braunschweig', 'braunschweig'),
 ('neu isenburg', 'oldenburg'),
 ('düsseldorfer schule', 'düsseldorf'),
 ('bayer london', 'bayern'),
 ('fried saarburg', 'saarburg'),
 ('wiesbadener kreis', 'wiesbaden'),
 ('einst berlin', 'berlin'),
 ('tr neustadt', 'neustadt'),
 ('dwd berlin', 'berlin'),
 ('stuttgart bayern', 'stuttgart'),
 ('lva berlin', 'berlin'),
 ('münster w', 'münster'),
 ('koblenz 395070', 'koblenz'),
 ('mok köln', 'köln'),
 ('ksha stuttgart', 'stuttgart'),
 ('braunschweig i', 'braunschweig'),
 ('wega berlin', 'berlin'),
 ('eb koblenz', 'koblenz'),
 ('lg koblenz', 'koblenz'),
 ('olg köln', 'köln'),
 ('oed freiburg', 'freiburg'),
 ('ksh hammover', 'hannover'),
 ('karlsruhe freiburg', 'karlsruhe'),
 ('düsseldorf köln', 'düsseldorf'),
 ('ag hannover', 'hannover'),
 ('k öln', 'köln'),
 ('land bayern', 'bayern'),
 ('ksha harburg', 'saarburg'),
 ('münchen eg', 'münchen'),
 ('münchen 2', 'münchen'),
 ('ksha händersheim', 'hildesheim'),
 ('neustadt rwkv', 'neustadt'),
 ('stadt düsseldorf', 'düsseldorf'),
 ('könig düsseldorf', 'düsseldorf'),
 ('oldenburg stadt', 'oldenburg'),
 ('düsseldorf saarbrücken', 'saarbrücken'),
 ('berlin hamburg', 'hamburg'),
 ('gob berliner', 'berlin'),
 ('rb detmold', 'detmold'),
 ('ksha bremenhaven', 'bremerhaven'),
 ('amt bery', 'arnsberg'),
 ('nva düsseldorf', 'düsseldorf'),
 ('wiesbaden luhe', 'wiesbaden'),
 ('bayern köln', 'bayern'),
 ('ofs berlin', 'berlin'),
 ('blka münchen', 'münchen'),
 ('stadt v', 'stade'),
 ('lka mainz', 'mainz'),
 ('lg würzburg', 'lüneburg'),
 ('köln münster', 'münster'),
 ('ig berlin', 'berlin'),
 ('saarbrücken düsseldorf', 'saarbrücken'),
 ('ksha wiesbaden', 'wiesbaden'),
 ('oft karlsruhe', 'karlsruhe'),
 ('stadt stuttgart', 'stuttgart'),
 ('nürnberg a', 'arnsberg'),
 ('5510 saarburg', 'saarburg'),
 ('bayer berlin', 'bayern'),
 ('ksha berlin', 'berlin'),
 ('aurich ostf', 'aurich'),
 ('lvf hamburg', 'hamburg'),
 ('braunschweig stadt', 'braunschweig'),
 ('detmold köln', 'detmold'),
 ('aha hamburg', 'hamburg'),
 ('mainz berlin', 'berlin'),
 ('schwab münchen', 'münchen'),
 ('olg koblenz', 'koblenz'),
 ('bayer reg', 'bayern'),
 ('münchen i', 'münchen'),
 ('bfh berlin', 'berlin'),
 ('an hildesheim', 'hildesheim'),
 ('hamburg i', 'hamburg'),
 ('qfd köln', 'köln'),
 ('bva hamburg', 'hamburg'),
 ('saarburg mainz', 'saarburg'),
 ('kshb goslari', 'goslar'),
 ('münchen ii', 'münchen'),
 ('darmstadt stadt', 'darmstadt'),
 ('b köln', 'köln'),
 ('nrw münster', 'münster'),
 ('stadt promerhaven', 'bremerhaven'),
 ('öl n', 'köln'),
 ('bzk mainz', 'mainz'),
 ('fidos münchen', 'münchen'),
 ('bezirksamt berlin', 'bezirksregierung'),
 ('braunschweig land', 'braunschweig'),
 ('karlsruhe baden', 'karlsruhe'),
 ('reg oldenburg', 'oldenburg'),
 ('köln lv', 'köln'),
 ('lvva hamburg', 'hamburg'),
 ('niedersachsenen präsident', 'niedersachsen'),
 ('kiel niedersachsen', 'niedersachsen'),
 ('ofd köln', 'köln'),
 ('olg stuttgart', 'stuttgart'),
 ('niedersachsen hannover', 'niedersachsen'),
 ('ksha helmsstedt', 'helmstedt'),
 ('berlin niedersachsen', 'niedersachsen'),
 ('lka niesbaden', 'wiesbaden'),
 ('trion neustadt', 'neustadt'),
 ('hamburger amt', 'hamburg'),
 ('sha hildesheim', 'hildesheim'),
 ('köln detmold', 'detmold'),
 ('soza münchen', 'münchen'),
 ('düsseldorfer gericht', 'düsseldorf'),
 ('karl wilhelm', 'karlsruhe'),
 ('barb burg', 'freiburg'),
 ('lva münster', 'münster'),
 ('arnsberg münster', 'arnsberg'),
 ('saarburger vogt', 'saarburg'),
 ('düsseldorfer kartei', 'düsseldorf'),
 ('neustadt m', 'neustadt'),
 ('rp arnswerg', 'arnsberg'),
 ('ofg hannover', 'hannover'),
 ('brauns hweig', 'braunschweig'),
 ('ba oldenburg', 'oldenburg'),
 ('liva münster', 'münster'),
 ('agr münchen', 'münchen'),
 ('opd berlin', 'berlin'),
 ('ek karlsruhe', 'karlsruhe'),
 ('nds hannover', 'hannover'),
 ('bla münchen', 'münchen'),
 ('eb münchen', 'münchen'),
 ('mai nz', 'mainz'),
 ('lkamt düsseldorf', 'düsseldorf'),
 ('lg berlin', 'berlin'),
 ('olg münchen', 'münchen'),
 ('braun schweig', 'braunschweig'),
 ('bfpa berlin', 'berlin'),
 ('iva düsseldorf', 'düsseldorf'),
 ('bonn stadt', 'neustadt'),
 ('braunschweig dep', 'braunschweig'),
 ('la hannover', 'hannover'),
 ('ra munster', 'münster'),
 ('köl n', 'köln'),
 ('bezirksamt mainz', 'bezirksregierung'),
 ('wiener landesregierung', 'bezirksregierung'),
 ('oft köln', 'köln'),
 ('ksha peine', 'peine'),
 ('hannover l', 'hannover'),
 ('oed köln', 'köln'),
 ('hessen dp', 'hessen'),
 ('lva oldenburg', 'oldenburg'),
 ('ofo köln', 'köln'),
 ('stadt hildesheim', 'hildesheim'),
 ('rp darmstadt', 'darmstadt'),
 ('ksha goslar', 'goslar'),
 ('lka stuttgart', 'stuttgart'),
 ('niedersachsen osnabrück', 'niedersachsen'),
 ('mainz wiesbaden', 'wiesbaden'),
 ('kolle land', 'koblenz'),
 ('köln a', 'köln'),
 ('awk köln', 'köln'),
 ('ofd münchen', 'münchen'),
 ('hessen neu', 'hessen'),
 ('lka wiesbaden', 'wiesbaden'),
 ('bfa berlin', 'berlin'),
 ('ksa goslar', 'goslar'),
 ('lvd hamburg', 'hamburg'),
 ('lka düsseldorf', 'düsseldorf'),
 ('lg düsseldorf', 'düsseldorf'),
 ('stuttgart i', 'stuttgart'),
 ('ag nürnberg', 'arnsberg'),
 ('okg münchen', 'münchen'),
 ('hesse neu', 'hessen'),
 ('ofd berlin', 'berlin'),
 ('darmstadt eg', 'darmstadt'),
 ('hessen nu', 'hessen'),
 ('neustadt trier', 'neustadt'),
 ('darmstadt mainz', 'darmstadt'),
 ('anstalt saarburg', 'saarburg'),
 ('hamburg az', 'hamburg'),
 ('afw köln', 'köln'),
 ('der regierung', 'bezirksregierung'),
 ('bayern neustadt', 'neustadt'),
 ('oftd köln', 'köln'),
 ('ksha oldenburg', 'oldenburg'),
 ('dva hamburg', 'hamburg'),
 ('ksha hamburg', 'hamburg'),
 ('ksh hannover', 'hannover'),
 ('berlin neustadt', 'neustadt'),
 ('rp köln', 'köln'),
 ('j cuttigart', 'stuttgart'),
 ('lva münchen', 'münchen'),
 ('nba lüneburg', 'lüneburg'),
 ('land hessen', 'hessen'),
 ('oldenburg olb', 'oldenburg'),
 ('neu ischad', 'neustadt'),
 ('stadt desseldorf', 'düsseldorf'),
 ('bezirksamt würzburg', 'bezirksregierung'),
 ('lea berlin', 'berlin'),
 ('oft berlin', 'berlin'),
 ('boyer london', 'bayern'),
 ('kshabraunschweig i', 'braunschweig'),
 ('der regierungso', 'bezirksregierung'),
 ('maine niedersachsen', 'niedersachsen'),
 ('aurich oetfr', 'aurich'),
 ('bfv berlin', 'berlin'),
 ('neustadt 483556', 'neustadt'),
 ('hva köln', 'köln'),
 ('neu isaadt', 'neustadt'),
 ('berlin platz', 'berlin'),
 ('ksha münster', 'münster'),
 ('münchen ost', 'münchen'),
 ('har nover', 'hannover'),
 ('dva duesseldorf', 'düsseldorf'),
 ('rp hildesheim', 'hildesheim'),
 ('hamburg köln', 'hamburg'),
 ('saarburg düsseldorf', 'düsseldorf'),
 ('stuttgart s', 'stuttgart'),
 ('neustadt neubist', 'neustadt'),
 ('zentral registrierung', 'bezirksregierung'),
 ('bayer verw', 'bayern'),
 ('hessen alt', 'hessen'),
 ('lvh hessen', 'hessen'),
 ('umw köln', 'köln'),
 ('haupt berlin', 'berlin'),
 ('düsseldorf hamm', 'düsseldorf'),
 ('oft hannover', 'hannover'),
 ('neustadt 484076', 'neustadt'),
 ('niedersachsen oldenburg', 'niedersachsen'),
 ('oldenburg old', 'oldenburg'),
 ('noblenz 225511', 'koblenz'),
 ('ksh braunschweig', 'braunschweig'),
 ('ba lüneburg', 'lüneburg'),
 ('bezirksregierung bmf', 'bezirksregierung'),
 ('ksha gandersheim', 'hildesheim'),
 ('lka hannover', 'hannover'),
 ('lg stuttgart', 'stuttgart'),
 ('an braunschweig', 'braunschweig'),
 ('kshax niedersachsen', 'niedersachsen'),
 ('münchen k81n', 'münchen'),
 ('k6 n', 'köln'),
 ('lüneburg land', 'lüneburg'),
 ('kshb braunschweig', 'braunschweig'),
 ('lka darmstadt', 'darmstadt'),
 ('lg mainz', 'mainz'),
 ('düsseldorf münchen', 'düsseldorf'),
 ('ilva darmstadt', 'darmstadt'),
 ('lva düsseldorf', 'düsseldorf'),
 ('ig münchen', 'münchen'),
 ('k8 n', 'köln'),
 ('k6 ln', 'köln'),
 ('rp arnsberg', 'arnsberg'),
 ('koblenz saarburg', 'saarburg'),
 ('lüneburg stadt', 'lüneburg'),
 ('berlin köln', 'berlin'),
 ('rhb berlin', 'berlin'),
 ('niedersachsen präsident', 'niedersachsen'),
 ('kreis lüneburg', 'lüneburg'),
 ('oldenburg oldb', 'oldenburg'),
 ('darmstadt dp', 'darmstadt'),
 ('oed münchen', 'münchen'),
 ('land berlin', 'berlin'),
 ('ksha augsburg', 'saarburg'),
 ('hannover lt', 'hannover'),
 ('neustadt 47825', 'neustadt'),
 ('ojd berlin', 'berlin'),
 ('jörns hessen', 'hessen'),
 ('früher koblenz', 'koblenz'),
 ('regierung braunschweig', 'braunschweig'),
 ('düsseldorf westf', 'düsseldorf'),
 ('hamburg 1', 'hamburg'),
 ('sozialamt düsseldorf', 'düsseldorf'),
 ('lg salzburg', 'saarburg'),
 ('referat arnsberg', 'arnsberg'),
 ('os nabruck', 'osnabrück'),
 ('bayrisches regierung', 'bezirksregierung'),
 ('oft koln', 'köln'),
 ('kreis osnabrück', 'osnabrück'),
 ('münchen 14219', 'münchen'),
 ('stadt oldenburg', 'oldenburg'),
 ('lüneburg straar', 'lüneburg'),
 ('köln saarbrücken', 'saarbrücken'),
 ('bza berlin', 'berlin'),
 ('bpa berlin', 'berlin'),
 ('dza zehlendorf', 'düsseldorf'),
 ('neustadt w', 'neustadt'),
 ('ksha düsseldorf', 'düsseldorf'),
 ('ksha aurich', 'aurich'),
 ('oft münster', 'münster'),
 ('ham pr', 'hamburg'),
 ('ksa hannover', 'hannover'),
 ('niedersachsen präsidium', 'niedersachsen'),
 ('ofg köln', 'köln'),
 ('uni marburg', 'saarburg'),
 ('reg arnsberg', 'arnsberg'),
 ('tr münchen', 'münchen'),
 ('b münchen', 'münchen'),
 ('braunschweig 1g', 'braunschweig'),
 ('bsha oldenburg', 'oldenburg'),
 ('lvii hamburg', 'hamburg'),
 ('kg berlin', 'berlin'),
 ('uok köln', 'köln'),
 ('lya hamburg', 'hamburg'),
 ('regoldenburg oldb', 'oldenburg'),
 ('niedersachsen braunschweig', 'niedersachsen'),
 ('kreissonderhilfsschule goslar stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ksha osnabrück land', 'osnabrück stadt'),
 ('kreissonderhilfsausschuss göttmünster stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('der hmg düsseldorf', 'düsseldorf'),
 ('e amt berlin', 'berlin'),
 ('kreisonderrhilfsausschuss osterode harz',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss hildesheim stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungsamt aachen mf', 'regierungspräsident aachen'),
 ('kreissonderbehilfsausschuss alfeld leine',
  'kreissonderhilfsausschuß delmenhorst'),
 ('bergedorfer gericht düsseldorf', 'bezirksregierung düsseldorf'),
 ('entschädigungsbehörde köln australien', 'entschädigungsbehörde münster'),
 ('kreissozialhilfeausschuss götttingen stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('berlin 0 17', 'berlin'),
 ('bayerische kardinalrhein westfalen', 'nordrhein westfalen'),
 ('der stadt bremen', 'darmstadt wiesbaden'),
 ('kreissoenderhilfsausschuss nienburg weser',
  'kreissonderhilfsausschuß delmenhorst'),
 ('der reichsvereinigung düsseldorf', 'bezirksregierung düsseldorf'),
 ('regierungsbezirk aachen wehr', 'regierungspräsident aachen'),
 ('bayrisches landesarchiv münchen', 'bayerisches landesentschädigungsamt'),
 ('kshax la hannover', 'stadt hannover'),
 ('regierungsamt münchen würzburg', 'regierungspräsident arnsberg'),
 ('ksha oldenburg stadt', 'hannover stadt'),
 ('kreisondeserhifsausschub braunschweig stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('lg münchen i', 'münchen'),
 ('kreissonderhilfsausschuss oldenburg land',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreisonderhilfsausschuss brake wesermarsch',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss colle stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfeausschuss celle stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss nienburg weser',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss hammeln stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ksha osterode harz', 'osterode harz'),
 ('kreissonderhilfsausschuss hannover 8a',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kn bayerisches landesentschädigungsamt',
  'bayerisches landesentschädigungsamt'),
 ('kreissozialhilfsausschuss alfeld leine',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungspräsidium oldenburg old', 'regierungspräsidium darmstadt'),
 ('freiburg i br', 'freiburg br'),
 ('regierungspräsidium ansbach welf', 'regierungspräsident aachen'),
 ('kreissozialhilfsausschübe celle stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfesausschuss nienburg weser',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungspräsidium m ögl', 'regierungspräsident köln'),
 ('kreissonderhilfsausschuss winsen luhe',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfsausschuss rottenburg hann',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschub watenstedt salzgitter',
  'kreissonderhilfsausschuß delmenhorst'),
 ('oberfinanzdirektion des saarlandes', 'oberfinanzdirektion saarbrücken'),
 ('bayrisches rosenheim landesentschädigungsamt',
  'bayerisches landesentschädigungsamt'),
 ('lvh rheinland pfalz', 'rheinland pfalz'),
 ('regierungsbezirk arnach weiß', 'regierungspräsident aachen'),
 ('kreissonderhilfsschübe göttingen stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ksha braunschweig i', 'braunschweig'),
 ('regierungsbezirk ansbach meß', 'regierungspräsident aachen'),
 ('niedersächsisches landesarchiv hannover',
  'niedersächsisches landesverwaltungsamt'),
 ('chr bayerisches landesverwaltungsamt',
  'niedersächsisches landesverwaltungsamt'),
 ('reg präsident arnswerg', 'regierungspräsident arnsberg'),
 ('münster l w', 'münster'),
 ('landesentschädigungssamt münchen 24',
  'landesentschädigungsamt saarbrücken'),
 ('regierungspräsident entschädigungsbehörde detmold',
  'regierungspräsident detmold'),
 ('regierungspräsidium arnshofen württ', 'regierungspräsident arnsberg'),
 ('landesentschädigungsamt 2 münchen', 'landesentschädigungsamt saarbrücken'),
 ('kreissozialhilfsausschuss landkreis mündern',
  'kreissonderhilfsausschuß delmenhorst'),
 ('rwvv neustadt w', 'neustadt'),
 ('kreisssonderhilfssausschuss stadt celle',
  'kreissonderhilfsausschuß delmenhorst'),
 ('ra adlersreutein düsseldorf', 'bezirksregierung düsseldorf'),
 ('kreisonderhilfsausschuss göttingen stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissozialhilfeauschuss goslar stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsschüle osterode harz',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungspräsidium düsseldorf westf', 'regierungspräsident düsseldorf'),
 ('kreisaußerhilfsausschub braunschweig stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreisonderhlfasschuf stadt hannover',
  'kreissonderhilfsausschuß delmenhorst'),
 ('kreissonderhilfsausschuss collo land',
  'kreissonderhilfsausschuß delmenhorst'),
 ('entschädigungsbehörde c 2875', 'entschädigungsbehörde köln'),
 ('kreissonderhilfsschüle hildesheim marienten',
  'kreissonderhilfsausschuß delmenhorst'),
 ('hessen ns hilfe', 'hessen kassel'),
 ('v koordinierung köln', 'bezirksregierung köln'),
 ('schbayerisches landesarchiv münchen',
  'bayerisches landesentschädigungsamt'),
 ('regierungspräsidium düsseldorf weltf', 'regierungspräsident düsseldorf'),
 ('ksha osterode h', 'osterode h'),
 ('th bayerisches landesentschädigungsamt',
  'bayerisches landesentschädigungsamt'),
 ('kreissozialhilfeauschuss celle stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungsbezirk münchen dachverband', 'regierungspräsident aachen'),
 ('reg braßbident münster', 'regierungspräsident münster'),
 ('kreissonderhilfsausschuss oldenburg stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('regierungspräsidium hannover nds', 'regierungspräsidium darmstadt'),
 ('kreissonderhilfsausschuss hamm land',
  'kreissonderhilfsausschuß delmenhorst'),
 ('landesentschädigungsamt r saarbrücken',
  'landesentschädigungsamt saarbrücken'),
 ('kreisaußerhilfsausschuss hildesheim stadt',
  'kreissonderhilfsausschuß delmenhorst'),
 ('knbayerisches landesentschädigungsamt münchen',
  'bayerisches landesentschädigungsamt'),
 ('bay tr landesentschädigungsamt', 'bayer landesentschädigungsamt'),
 ('oldenburg i o', 'oldenburg'),
 ('regierung düsseldorf dm', 'bezirksregierung düsseldorf'),
 ('kassel i 7', 'kassel'),
 ('kreissozialhilfsausschuss hamein pyrmont',
  'kreissonderhilfsausschuß delmenhorst'),
 ('sarbrücken rheinland pfalz', 'rheinland pfalz'),
 ('regierungsbezirk aachen wff', 'regierungspräsident aachen'),
 ('landesentschädigungsamt b saarbrücken',
  'landesentschädigungsamt saarbrücken'),
 ('regierungsbezirk posen wohl', 'regierungspräsident köln'),
 ('feiburg i br', 'freiburg br'),
 ('sozialamt bayerisches landesentschädigungsamt',

# Swapping out single tokens with a match distance of up to half of the token's lenght

In [ ]:
json_to_csv_closest_map = {}
for json_token in json_tokens:
    if json_token in csv_tokens:
        continue
    
    max_distance = len(json_token) // 2
    best_match = None
    best_dist = float('inf')
    
    for csv_token in csv_tokens:
        if len(csv_token) >= 3:
            if abs(len(csv_token) - len(json_token)) > max_distance:
                continue
            dist = distance(json_token, csv_token)
            if dist <= max_distance and dist < best_dist:
                best_dist = dist
                best_match = csv_token
    
    if best_match is not None:
        json_to_csv_closest_map[json_token] = [best_match]

single_token_matches_closest = sorted(
    json_to_csv_closest_map.items(),
    key=lambda item: len(item[0])
)
print(len(single_token_matches_closest))
single_token_matches_closest

6957

[('re', ['reg']),
 ('st', ['str']),
 ('rb', ['lrb']),
 ('tr', ['str']),
 ('rg', ['reg']),
 ('sr', ['str']),
 ('vb', ['vb4']),
 ('of', ['ofd']),
 ('er', ['der']),
 ('ad', ['bad']),
 ('es', ['des']),
 ('di', ['die']),
 ('bd', ['bad']),
 ('ba', ['bad']),
 ('uk', ['unk']),
 ('ht', ['hdt']),
 ('de', ['der']),
 ('eg', ['reg']),
 ('mi', ['min']),
 ('dt', ['hdt']),
 ('da', ['das']),
 ('b4', ['vb4']),
 ('mt', ['amt']),
 ('lr', ['lrb']),
 ('dr', ['der']),
 ('hd', ['hdt']),
 ('nu', ['neu']),
 ('fr', ['für']),
 ('as', ['das']),
 ('dz', ['dez']),
 ('hdm', ['hdt']),
 ('abh', ['abt']),
 ('vr4', ['vb4']),
 ('keg', ['reg']),
 ('ein', ['fin']),
 ('baf', ['bad']),
 ('rep', ['reg']),
 ('tür', ['für']),
 ('vd4', ['vb4']),
 ('oft', ['ofd']),
 ('dhe', ['die']),
 ('for', ['für']),
 ('efd', ['ofd']),
 ('mit', ['min']),
 ('vbh', ['vb4']),
 ('drs', ['das']),
 ('ofg', ['ofd']),
 ('per', ['der']),
 ('ub4', ['vb4']),
 ('alt', ['abt']),
 ('vin', ['fin']),
 ('wür', ['für']),
 ('db4', ['vb4']),
 ('ant', ['abt']),
 ('and', ['und']),
 ('beg', ['reg']),
 ('lr8', ['lrb']),
 ('stg', ['str']),
 ('new', ['neu']),
 ('bau', ['bad']),
 ('fln', ['fin']),
 ('ref', ['reg']),
 ('vba', ['vb4']),
 ('fun', ['fin']),
 ('ddr', ['der']),
 ('dem', ['der']),
 ('doz', ['dez']),
 ('ger', ['der']),
 ('off', ['ofd']),
 ('oed', ['ofd']),
 ('vb3', ['vb4']),
 ('dcr', ['der']),
 ('krb', ['lrb']),
 ('art', ['abt']),
 ('ber', ['der']),
 ('mün', ['min']),
 ('her', ['der']),
 ('xin', ['fin']),
 ('lüb', ['lrb']),
 ('rbg', ['reg']),
 ('lro', ['lrb']),
 ('deu', ['der']),
 ('eb4', ['vb4']),
 ('sta', ['str']),
 ('köl', ['köln']),
 ('hes', ['hess']),
 ('sod', ['süd']),
 ('diö', ['die']),
 ('hin', ['fin']),
 ('lbb', ['lrb']),
 ('ojd', ['ofd']),
 ('lab', ['lrb']),
 ('ast', ['abt']),
 ('vt4', ['vb4']),
 ('ovd', ['ofd']),
 ('lie', ['die']),
 ('kad', ['bad']),
 ('dat', ['das']),
 ('den', ['der']),
 ('rad', ['bad']),
 ('ord', ['ofd']),
 ('bam', ['bad']),
 ('bfd', ['ofd']),
 ('uok', ['unk']),
 ('din', ['fin']),
 ('feg', ['reg']),
 ('hss', ['hess']),
 ('stv', ['str']),
 ('okd', ['ofd']),
 ('ubt', ['abt']),
 ('ier', ['der']),
 ('dep', ['der']),
 ('neg', ['neu']),
 ('har', ['harz']),
 ('det', ['der']),
 ('sin', ['fin']),
 ('rey', ['reg']),
 ('v34', ['vb4']),
 ('rog', ['reg']),
 ('bar', ['bad']),
 ('stl', ['str']),
 ('lre', ['lrb']),
 ('abg', ['abt']),
 ('opd', ['ofd']),
 ('dme', ['die']),
 ('ges', ['des']),
 ('öln', ['köln']),
 ('hmt', ['amt']),
 ('stm', ['str']),
 ('dar', ['der']),
 ('trb', ['lrb']),
 ('bay', ['bad']),
 ('ami', ['amt']),
 ('ofs', ['ofd']),
 ('dei', ['der']),
 ('mii', ['min']),
 ('def', ['der']),
 ('baw', ['bad']),
 ('bmt', ['amt']),
 ('stf', ['str']),
 ('fur', ['für']),
 ('dor', ['der']),
 ('lfd', ['ofd']),
 ('wes', ['des']),
 ('bav', ['bad']),
 ('brd', ['bad']),
 ('weg', ['reg']),
 ('ver', ['der']),
 ('qfd', ['ofd']),
 ('crb', ['lrb']),
 ('bak', ['bad']),
 ('del', ['der']),
 ('mad', ['bad']),
 ('ung', ['unk']),
 ('res', ['reg']),
 ('hst', ['hdt']),
 ('end', ['und']),
 ('hdn', ['hdt']),
 ('prs', ['präs']),
 ('lkb', ['lrb']),
 ('hdi', ['hdt']),
 ('deg', ['der']),
 ('rug', ['reg']),
 ('cas', ['das']),
 ('kin', ['fin']),
 ('bod', ['bad']),
 ('rig', ['reg']),
 ('bie', ['die']),
 ('vc4', ['vb4']),
 ('vby', ['vb4']),
 ('bez', ['dez']),
 ('nec', ['neu']),
 ('cin', ['fin']),
 ('uni', ['unk']),
 ('rin', ['fin']),
 ('rea', ['reg']),
 ('tin', ['fin']),
 ('bah', ['bad']),
 ('lad', ['bad']),
 ('v84', ['vb4']),
 ('lüd', ['süd']),
 ('lra', ['lrb']),
 ('ind', ['und']),
 ('wie', ['die']),
 ('old', ['ofd']),
 ('läb', ['lrb']),
 ('xes', ['des']),
 ('ofr', ['ofd']),
 ('ib4', ['vb4']),
 ('ofo', ['ofd']),
 ('pin', ['fin']),
 ('wtr', ['str']),
 ('bes', ['des']),
 ('kln', ['köln']),
 ('amf', ['amt']),
 ('dos', ['das']),
 ('ain', ['fin']),
 ('kön', ['köln']),
 ('dad', ['das']),
 ('peg', ['reg']),
 ('erb', ['lrb']),
 ('verw', ['der']),
 ('ches', ['hess']),
 ('sala', ['samt']),
 ('vero', ['der']),
 ('k8lm', ['köln']),
 ('noln', ['bonn']),
 ('köla', ['köln']),
 ('pres', ['präs']),
 ('keln', ['köln']),
 ('kobl', ['kiel']),
 ('bern', ['der']),
 ('fclz', ['pfalz']),
 ('träg', ['präs']),
 ('oste', ['str']),
 ('weaf', ['westf']),
 ('würt', ['für']),
 ('bamf', ['amt']),
 ('wigl', ['kiel']),
 ('hdin', ['fin']),
 ('hamt', ['amt']),
 ('vrtr', ['str']),
 ('yerv', ['der']),
 ('zond', ['ofd']),
 ('jews', ['hess']),
 ('bürg', ['für']),
 ('bayr', ['bayer']),
 ('xoin', ['fin']),
 ('m81n', ['min']),
 ('pfla', ['pfalz']),
 ('stlh', ['str']),
 ('miel', ['kiel']),
 ('kein', ['keine']),
 ('mies', ['kiel']),
 ('deft', ['der']),
 ('elbe', ['celle']),
 ('rafe', ['brake']),
 ('prez', ['prinz']),
 ('k5ln', ['köln']),
 ('r8ln', ['köln']),
 ('brem', ['bremen']),
 ('haus', ['das']),
 ('kell', ['celle']),
 ('dung', ['unk']),
 ('rest', ['westf']),
 ('kall', ['kiel']),
 ('woff', ['ofd']),
 ('weis', ['kreis']),
 ('höss', ['hess']),
 ('delf', ['der']),
 ('koll', ['kiel']),
 ('zeig', ['reg']),
 ('pltz', ['platz']),
 ('merg', ['der']),
 ('trie', ['trier']),
 ('kaln', ['köln']),
 ('prag', ['präs']),
 ('kala', ['köln']),
 ('k6hn', ['köln']),
 ('pris', ['präs']),
 ('ivbf', ['vb4']),
 ('vier', ['der']),
 ('vers', ['der']),
 ('hald', ['harz']),
 ('kzin', ['fin']),
 ('afdr', ['ofd']),
 ('varw', ['harz']),
 ('hadf', ['harz']),
 ('hees', ['hess']),
 ('yerw', ['der']),
 ('wein', ['fin']),
 ('mann', ['bonn']),
 ('wist', ['westf']),
 ('vba4', ['vb4']),
 ('hölm', ['köln']),
 ('akte', ['abt']),
 ('born', ['bonn']),
 ('fuer', ['der']),
 ('wetf', ['westf']),
 ('w8in', ['fin']),
 ('nöll', ['köln']),
 ('bdln', ['baden']),
 ('ordn', ['ofd']),
 ('371v', ['37iv']),
 ('ring', ['prinz']),
 ('vegw', ['reg']),
 ('blon', ['bonn']),
 ('röhn', ['köln']),
 ('koni', ['bonn']),
 ('oftd', ['ofd']),
 ('holz', ['harz']),
 ('wied', ['kiel']),
 ('h8in', ['fin']),
 ('grls', ['präs']),
 ('mehr', ['der']),
 ('lion', ['fin']),
 ('leya', ['leer']),
 ('vewg', ['reg']),
 ('görz', ['harz']),
 ('pflk', ['pfalz']),
 ('jung', ['unk']),
 ('bann', ['bonn']),
 ('81in', ['fin']),
 ('zell', ['celle']),
 ('büro', ['für']),
 ('aöln', ['köln']),
 ('korn', ['bonn']),
 ('völn', ['köln']),
 ('moln', ['bonn']),
 ('xerv', ['der']),
 ('east', ['abt']),
 ('sohn', ['bonn']),
 ('über', ['der']),
 ('verv', ['der']),
 ('löin', ['fin']),
 ('rale', ['brake']),
 ('palz', ['pfalz']),
 ('neua', ['neu']),
 ('kstu', ['str']),
 ('dort', ['der']),
 ('merx', ['der']),
 ('alma', ['amt']),
 ('wölf', ['köln']),
 ('eros', ['präs']),
 ('mein', ['min']),
 ('münx', ['min']),
 ('stal', ['stade']),
 ('syke', ['ecke']),
 ('fund', ['und']),
 ('pala', ['pfalz']),
 ('vt54', ['vb4']),
 ('dolz', ['dez']),
 ('pras', ['präs']),
 ('döin', ['fin']),
 ('wald', ['bad']),
 ('flaz', ['platz']),
 ('bery', ['der']),
 ('röln', ['köln']),
 ('marz', ['harz']),
 ('draf', ['das']),
 ('höll', ['köln']),
 ('sinz', ['prinz']),
 ('hrin', ['prinz']),
 ('leop', ['leer']),
 ('trer', ['trier']),
 ('cstf', ['westf']),
 ('berg', ['der']),
 ('vbs4', ['vb4']),
 ('kclm', ['köln']),
 ('rabe', ['abt']),
 ('halz', ['harz']),
 ('isar', ['str']),
 ('linn', ['fin']),
 ('meck', ['ecke']),
 ('holn', ['bonn']),
 ('ismd', ['süd']),
 ('syrm', ['str']),
 ('wstf', ['westf']),
 ('amon', ['amt']),
 ('wflz', ['pfalz']),
 ('plak', ['platz']),
 ('röin', ['fin']),
 ('prüm', ['präs']),
 ('ptlz', ['pfalz']),
 ('marb', ['lrb']),
 ('pflz', ['pfalz']),
 ('lecr', ['leer']),
 ('lnrb', ['lrb']),
 ('hcss', ['hess']),
 ('neus', ['neu']),
 ('chtr', ['str']),
 ('möll', ['köln']),
 ('lech', ['leer']),
 ('trhr', ['trier']),
 ('mark', ['markt']),
 ('negi', ['neu']),
 ('linz', ['prinz']),
 ('lend', ['und']),
 ('orde', ['ofd']),
 ('kshd', ['süd']),
 ('weßf', ['westf']),
 ('kälm', ['köln']),
 ('hans', ['das']),
 ('rech', ['reg']),
 ('baft', ['abt']),
 ('wega', ['reg']),
 ('mold', ['ofd']),
 ('stat', ['stadt']),
 ('koex', ['kiel']),
 ('hann', ['bonn']),
 ('kdin', ['fin']),
 ('heil', ['hess']),
 ('kglm', ['köln']),
 ('maiz', ['mainz']),
 ('pfaz', ['pfalz']),
 ('woln', ['bonn']),
 ('wepf', ['westf']),
 ('pils', ['präs']),
 ('weff', ['westf']),
 ('barb', ['lrb']),
 ('wetl', ['westf']),
 ('elsa', ['ems']),
 ('hund', ['und']),
 ('rich', ['aurich']),
 ('koín', ['bonn']),
 ('stau', ['stade']),
 ('pfiz', ['prinz']),
 ('k81n', ['köln']),
 ('kola', ['köln']),
 ('hayt', ['abt']),
 ('lkad', ['bad']),
 ('prsä', ['präs']),
 ('kart', ['abt']),
 ('road', ['ofd']),
 ('pius', ['präs']),
 ('reta', ['reg']),
 ('stml', ['samt']),
 ('kblm', ['köln']),
 ('oder', ['der']),
 ('camp', ['amt']),
 ('hwdg', ['hdt']),
 ('bank', ['bonn']),
 ('blen', ['baden']),
 ('viel', ['kiel']),
 ('bahn', ['baden']),
 ('krim', ['kreis']),
 ('k8in', ['fin']),
 ('rbge', ['reg']),
 ('kess', ['hess']),
 ('molf', ['adolf']),
 ('wcst', ['westf']),
 ('länd', ['und']),
 ('kiln', ['köln']),
 ('noin', ['fin']),
 ('hung', ['unk']),
 ('kolm', ['köln']),
 ('kxlm', ['köln']),
 ('mell', ['celle']),
 ('john', ['bonn']),
 ('döln', ['köln']),
 ('bohn', ['bonn']),
 ('over', ['der']),
 ('west', ['westf']),
 ('sprl', ['str']),
 ('kstn', ['köln']),
 ('jeru', ['der']),
 ('kstl', ['kiel']),
 ('deff', ['der']),
 ('frei', ['freie']),
 ('wess', ['hess']),
 ('vis4', ['vb4']),
 ('nauo', ['neu']),
 ('amft', ['amt']),
 ('nolu', ['neu']),
 ('dope', ['die']),
 ('höhn', ['köln']),
 ('paus', ['präs']),
 ('ienz', ['dez']),
 ('triv', ['trier']),
 ('lohr', ['leer']),
 ('paiz', ['prinz']),
 ('trag', ['reg']),
 ('meln', ['köln']),
 ('k5lm', ['köln']),
 ('tier', ['trier']),
 ('kald', ['köln']),
 ('sohr', ['str']),
 ('k3in', ['fin']),
 ('matn', ['mainz']),
 ('päiz', ['prinz']),
 ('kölñ', ['köln']),
 ('ostr', ['str']),
 ('höln', ['köln']),
 ('göll', ['köln']),
 ('mdef', ['der']),
 ('bona', ['bonn']),
 ('wolf', ['adolf']),
 ('dorf', ['der']),
 ('helm', ['hess']),
 ('m8in', ['min']),
 ('neuw', ['neu']),
 ('saar', ['samt']),
 ('36s4', ['36iv']),
 ('3hft', ['hdt']),
 ('wesf', ['westf']),
 ('gill', ['kiel']),
 ('eder', ['der']),
 ('schr', ['str']),
 ('trir', ['trier']),
 ('aisz', ['mainz']),
 ('vweg', ['reg']),
 ('jötn', ['köln']),
 ('wien', ['fin']),
 ('kölz', ['köln']),
 ('wdtt', ['hdt']),
 ('seit', ['samt']),
 ('kohn', ['bonn']),
 ('welf', ['westf']),
 ('drit', ['die']),
 ('buer', ['der']),
 ('baym', ['bayer']),
 ('wief', ['kiel']),
 ('wfst', ['westf']),
 ('lern', ['der']),
 ('labo', ['abt']),
 ('bmft', ['amt']),
 ('frau', ['frauen']),
 ('neve', ['neue']),
 ('karl', ['kiel']),
 ('ampt', ['amt']),
 ('jöön', ['köln']),
 ('röge', ['reg']),
 ('lenz', ['dez']),
 ('kglw', ['köln']),
 ('wels', ['hess']),
 ('bafö', ['bad']),
 ('hauß', ['harz']),
 ('henn', ['bonn']),
 ('jöln', ['köln']),
 ('waln', ['köln']),
 ('vtb4', ['vb4']),
 ('rüdt', ['süd']),
 ('aemt', ['amt']),
 ('koln', ['köln']),
 ('klin', ['fin']),
 ('hier', ['der']),
 ('jöhn', ['köln']),
 ('völk', ['köln']),
 ('hölt', ['köln']),
 ('udln', ['köln']),
 ('juni', ['unk']),
 ('less', ['hess']),
 ('lind', ['fin']),
 ('ofen', ['ofd']),
 ('werw', ['der']),
 ('sürm', ['für']),
 ('thei', ['rhein']),
 ('k6lu', ['köln']),
 ('verf', ['der']),
 ('korb', ['lrb']),
 ('hade', ['baden']),
 ('minz', ['mainz']),
 ('main', ['mainz']),
 ('hicn', ['fin']),
 ('b81n', ['bonn']),
 ('ster', ['str']),
 ('meif', ['min']),
 ('polz', ['pfalz']),
 ('baun', ['baden']),
 ('böln', ['köln']),
 ('falz', ['pfalz']),
 ('verm', ['der']),
 ('kond', ['ofd']),
 ('berm', ['der']),
 ('betr', ['der']),
 ('wals', ['das']),
 ('hill', ['kiel']),
 ('k3lm', ['köln']),
 ('dörf', ['der']),
 ('börn', ['bonn']),
 ('amth', ['amt']),
 ('bell', ['celle']),
 ('h8ln', ['köln']),
 ('würm', ['für']),
 ('adam', ['das']),
 ('ostz', ['str']),
 ('hest', ['hess']),
 ('nord', ['ofd']),
 ('nöin', ['fin']),
 ('amnt', ['amt']),
 ('kalu', ['köln']),
 ('lieb', ['kiel']),
 ('k31n', ['köln']),
 ('sitz', ['str']),
 ('ciss', ['hess']),
 ('loin', ['fin']),
 ('dell', ['der']),
 ('berl', ['der']),
 ('dept', ['der']),
 ('malz', ['mainz']),
 ('ehrt', ['hdt']),
 ('mich', ['min']),
 ('k6lm', ['köln']),
 ('kohl', ['kiel']),
 ('hamb', ['amt']),
 ('anat', ['abt']),
 ('land', ['landau']),
 ('baik', ['bad']),
 ('weef', ['westf']),
 ('vb15', ['vb4']),
 ('mels', ['hess']),
 ('aust', ['abt']),
 ('name', ['amt']),
 ('anst', ['abt']),
 ('nöln', ['köln']),
 ('wehr', ['der']),
 ('dein', ['der']),
 ('bayz', ['bayer']),
 ('jürm', ['für']),
 ('lüba', ['lrb']),
 ('blin', ['fin']),
 ('kuin', ['fin']),
 ('veb3', ['vb4']),
 ('k3ln', ['köln']),
 ('361v', ['36iv']),
 ('hand', ['harz']),
 ('memw', ['ems']),
 ('hödn', ['köln']),
 ('uojn', ['bonn']),
 ('hamm', ['amt']),
 ('verh', ['der']),
 ('pröf', ['präs']),
 ('seer', ['leer']),
 ('stdt', ['stadt']),
 ('bauk', ['bad']),
 ('kass', ['das']),
 ('würf', ['für']),
 ('moin', ['min']),
 ('lutz', ['platz']),
 ('kann', ['bonn']),
 ('einz', ['prinz']),
 ('brsg', ['reg']),
 ('auch', ['aurich']),
 ('kats', ['das']),
 ('manz', ['mainz']),
 ('icin', ['fin']),
 ('lond', ['ofd']),
 ('dith', ['die']),
 ('k6ln', ['köln']),
 ('k5in', ['fin']),
 ('unna', ['unk']),
 ('welt', ['westf']),
 ('best', ['westf']),
 ('wesu', ['neu']),
 ('dolm', ['adolf']),
 ('sara', ['samt']),
 ('vbst', ['abt']),
 ('leib', ['lrb']),
 ('mess', ['hess']),
 ('pelz', ['dez']),
 ('rogf', ['reg']),
 ('stnz', ['str']),
 ('roln', ['bonn']),
 ('poin', ['prinz']),
 ('nerv', ['der']),
 ('rölm', ['köln']),
 ('mgrb', ['lrb']),
 ('faiz', ['fin']),
 ('eusk', ['unk']),
 ('löbn', ['lrb']),
 ('vt34', ['vb4']),
 ('kfar', ['für']),
 ('k8ln', ['köln']),
 ('huss', ['hess']),
 ('sind', ['fin']),
 ('amat', ['amt']),
 ('mief', ['kiel']),
 ('amts', ['amt']),
 ('nest', ['neu']),
 ('dürk', ['der']),
 ('basa', ['das']),
 ('vts4', ['vb4']),
 ('mitz', ['mainz']),
 ('iren', ['reg']),
 ('möln', ['köln']),
 ('bafh', ['bad']),
 ('vern', ['der']),
 ('fels', ['hess']),
 ('antt', ['abt']),
 ('dmef', ['der']),
 ('k61n', ['köln']),
 ('levy', ['leer']),
 ('pätz', ['platz']),
 ('amit', ['amt']),
 ('kalt', ['abt']),
 ('stin', ['fin']),
 ('gesb', ['hess']),
 ('bein', ['fin']),
 ('mölt', ['köln']),
 ('auln', ['köln']),
 ('k62n', ['köln']),
 ('brak', ['brake']),
 ('männ', ['bonn']),
 ('abge', ['abt']),
 ('höin', ['fin']),
 ('viec', ['kiel']),
 ('ratg', ['reg']),
 ('bass', ['das']),
 ('depl', ['der']),
 ('roßn', ['bonn']),
 ('aviv', ['36iv']),
 ('pots', ['präs']),
 ('zone', ['bonn']),
 ('ukln', ['köln']),
 ('nauß', ['neu']),
 ('bdst', ['hdt']),
 ('r8in', ['fin']),
 ('patz', ['platz']),
 ('aach', ['aachen']),
 ('uöln', ['köln']),
 ('mahn', ['mainz']),
 ('bönn', ['bonn']),
 ('herr', ['der']),
 ('simm', ['samt']),
 ('hunc', ['unk']),
 ('fink', ['fin']),
 ('peer', ['leer']),
 ('jena', ['jenaer']),
 ('k8lu', ['köln']),
 ('gera', ['der']),
 ('kelm', ['kiel']),
 ('fölz', ['pfalz']),
 ('merw', ['der']),
 ('oldb', ['ofd']),
 ('hint', ['fin']),
 ('ivb4', ['vb4']),
 ('bayg', ['bayer']),
 ('emde', ['ecke']),
 ('sand', ['samt']),
 ('bund', ['und']),
 ('pegn', ['reg']),
 ('k6in', ['fin']),
 ('kbin', ['fin']),
 ('häin', ['fin']),
 ('auss', ['hess']),
 ('rexx', ['reg']),
 ('sent', ['samt']),
 ('mitt', ['min']),
 ('vt84', ['vb4']),
 ('dess', ['hess']),
 ('präz', ['präs']),
 ('area', ['reg']),
 ('ungb', ['unk']),
 ('hofn', ['ofd']),
 ('präf', ['präs']),
 ('plaz', ['platz']),
 ('sekt', ['samt']),
 ('kalm', ['köln']),
 ('mink', ['min']),
 ('kref', ['kiel']),
 ('rbln', ['köln']),
 ('ruin', ['fin']),
 ('heße', ['hess']),
 ('baum', ['bad']),
 ('heim', ['hess']),
 ('kela', ['kiel']),
 ('kdst', ['hdt']),
 ('efrn', ['fin']),
 ('herz', ['harz']),
 ('duck', ['unk']),
 ('kolu', ['köln']),
 ('merk', ['der']),
 ('x8in', ['fin']),
 ('dent', ['der']),
 ('koen', ['kiel']),
 ('benr', ['der']),
 ('prof', ['präs']),
 ('hain', ['fin']),
 ('xxln', ['köln']),
 ('thür', ['für']),
 ('münz', ['mainz']),
 ('erfu', ['erfurt']),
 ('dole', ['die']),
 ('ness', ['hess']),
 ('b61n', ['bonn']),
 ('neuo', ['neu']),
 ('koin', ['fin']),
 ('xoln', ['bonn']),
 ('merl', ['der']),
 ('stad', ['stade']),
 ('baud', ['bad']),
 ('moff', ['ofd']),
 ('k51n', ['köln']),
 ('ostf', ['westf']),
 ('wenf', ['westf']),
 ('mölln', ['köln']),
 ('josef', ['joseph']),
 ('board', ['bad']),
 ('bayem', ['bayer']),
 ('kroio', ['kreis']),
 ('paris', ['präs']),
 ('areas', ['kreis']),
 ('nainz', ['mainz']),
 ('leine', ['peine']),
 ('wesff', ['westf']),
 ('halbz', ['harz']),
 ('weins', ['weinstr']),
 ('basel', ['baden']),
 ('fürth', ['für']),
 ('bayhj', ['bayer']),
 ('aurid', ['aurich']),
 ('blenz', ['koblenz']),
 ('malka', ['markt']),
 ('karte', ['kartei']),
 ('staat', ['stadt']),
 ('kirch', ['kirchen']),
 ('kroic', ['kreis']),
 ('juden', ['baden']),
 ('welti', ['westf']),
 ('erbin', ['berlin']),
 ('pfahl', ['pfalz']),
 ('htaiz', ['harz']),
 ('saale', ['stade']),
 ('stern', ['str']),
 ('urtei', ['kartei']),
 ('westr', ['westf']),
 ('wehrf', ['westf']),
 ('feyer', ['bayer']),
 ('froim', ['freie']),
 ('dukas', ['das']),
 ('brünn', ['bonn']),
 ('hoyer', ['bayer']),
 ('kolin', ['köln']),
 ('westw', ['westf']),
 ('bover', ['bayer']),
 ('städt', ['stadt']),
 ('geier', ['trier']),
 ('triel', ['trier']),
 ('piaiz', ['platz']),
 ('emden', ['baden']),
 ('payer', ['bayer']),
 ('italz', ['pfalz']),
 ('klein', ['kreis']),
 ('westl', ['westf']),
 ('mains', ['mainz']),
 ('demol', ['detmold']),
 ('neuer', ['neue']),
 ('gölle', ['celle']),
 ('kalis', ['kreis']),
 ('phälz', ['pfalz']),
 ('mahnz', ['mainz']),
 ('freib', ['freie']),
 ('heydt', ['hdt']),
 ('weltf', ['westf']),
 ('trzor', ['trier']),
 ('mayer', ['bayer']),
 ('pflaz', ['platz']),
 ('ausch', ['aurich']),
 ('magin', ['mainz']),
 ('wcstf', ['westf']),
 ('trieß', ['trier']),
 ('braun', ['brauer']),
 ('kölin', ['köln']),
 ('regie', ['freie']),
 ('alden', ['baden']),
 ('merit', ['markt']),
 ('traun', ['frauen']),
 ('heins', ['hess']),
 ('ptaiz', ['platz']),
 ('tröer', ['trier']),
 ('ptalz', ['pfalz']),
 ('knies', ['kiel']),
 ('kremn', ['bremen']),
 ('völbn', ['köln']),
 ('müden', ['baden']),
 ('westu', ['westf']),
 ('koble', ['koblenz']),
 ('füger', ['für']),
 ('stödt', ['stadt']),
 ('bünde', ['bundes']),
 ('trift', ['trier']),
 ('pfölz', ['pfalz']),
 ('mannz', ['mainz']),
 ('remen', ['bremen']),
 ('haldt', ['hdt']),
 ('preiz', ['prinz']),
 ('obers', ['ebert']),
 ('westi', ['westf']),
 ('fides', ['des']),
 ('protz', ['prinz']),
 ('pratz', ['platz']),
 ('ereis', ['kreis']),
 ('mellf', ['celle']),
 ('weber', ['leer']),
 ('trlir', ['trier']),
 ('bayot', ['bayer']),
 ('pfälz', ['pfalz']),
 ('weste', ['westf']),
 ('colle', ['celle']),
 ('benin', ['bonn']),
 ('stift', ['stadt']),
 ('herne', ['peine']),
 ('kroin', ['kreis']),
 ('gring', ['prinz']),
 ('emder', ['der']),
 ('santa', ['samt']),
 ('wrest', ['westf']),
 ('fried', ['freie']),
 ('kölle', ['celle']),
 ('frier', ['trier']),
 ('bayor', ['bayer']),
 ('plink', ['prinz']),
 ('höamt', ['amt']),
 ('efrat', ['referat']),
 ('lamet', ['amt']),
 ('koeln', ['kiel']),
 ('regic', ['reg']),
 ('kelle', ['celle']),
 ('glatz', ['platz']),
 ('straf', ['straße']),
 ('siadr', ['stade']),
 ('buyer', ['bayer']),
 ('sache', ['aachen']),
 ('eifel', ['kiel']),
 ('weißf', ['westf']),
 ('praes', ['präs']),
 ('welff', ['westf']),
 ('bayam', ['bayer']),
 ('mairz', ['mainz']),
 ('aaden', ['baden']),
 ('esamt', ['samt']),
 ('maier', ['mainzer']),
 ('rölin', ['köln']),
 ('kolle', ['celle']),
 ('köln2', ['köln']),
 ('westt', ['westf']),
 ('maink', ['mainz']),
 ('dölln', ['köln']),
 ('trüir', ['trier']),
 ('lands', ['landes']),
 ('heute', ['neue']),
 ('minsk', ['min']),
 ('bayes', ['bayer']),
 ('siedl', ['kiel']),
 ('meckl', ['ecke']),
 ('leben', ['leer']),
 ('trücr', ['trier']),
 ('borna', ['bonn']),
 ('green', ['bremen']),
 ('field', ['kiel']),
 ('efurt', ['erfurt']),
 ('theil', ['rhein']),
 ('reche', ['ecke']),
 ('hesse', ['hess']),
 ('lesem', ['leer']),
 ('fritz', ['prinz']),
 ('ueber', ['leer']),
 ('trher', ['trier']),
 ('collo', ['celle']),
 ('philz', ['prinz']),
 ('meins', ['mainz']),
 ('ostpr', ['str']),
 ('neues', ['neue']),
 ('amter', ['amt']),
 ('nauhe', ['neue']),
 ('tierr', ['trier']),
 ('statz', ['platz']),
 ('dezlf', ['dez']),
 ('präsd', ['präs']),
 ('plitz', ['platz']),
 ('trüer', ['trier']),
 ('radem', ['baden']),
 ('gräss', ['präs']),
 ('neuss', ['heuss']),
 ('admin', ['min']),
 ('triar', ['trier']),
 ('bvamt', ['amt']),
 ('buren', ['baden']),
 ('weser', ['westf']),
 ('nauue', ['neue']),
 ('nberg', ['ebert']),
 ('lower', ['leer']),
 ('amtes', ['amt']),
 ('flanz', ['platz']),

In [30]:
unique_distance1_token_map = {
    json_token: csv_candidates[0]
    for json_token, csv_candidates in json_to_csv_closest_map.items()
    if len(csv_candidates) == 1
}

def replace_unique_distance1_tokens(text):
    text = "" if pd.isna(text) else str(text)
    return re.sub(
        r"\b\w+\b",
        lambda match: unique_distance1_token_map.get(match.group(0).lower(), match.group(0)),
        text,
        flags=re.UNICODE
    )

df_json_filtered['CompensationOffice_token_swap'] = df_json_filtered['norm_office'].apply(replace_unique_distance1_tokens)

print(f"Unique token replacements available: {len(unique_distance1_token_map)}")

results = df_json_filtered['CompensationOffice_token_swap'].apply(get_min_distance_dynamic_normalized)
df_matches_token_swap = pd.DataFrame({
    'CompensationOffice1': df_json_filtered['norm_office'],
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches_token_swap.head(20)

Unique token replacements available: 6957

,CompensationOffice1,MatchedOffice,MatchDistance
1,amt für wiedergutmachung des selbstkantkreises...,amt für wiedergutmachung des selfkantkreises g...,10.0
2,bezirksamt für wiedergutmachung köln,bezirksamt für wiedergutmachung mainz,4.0
3,der regierungspräsidium düsseldorf,der regierungspräsident düsseldorf,3.0
4,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
5,regierungsbezirk für wiedergutmachung und verw...,regierungsbezirksamt für wiedergutmachung und ...,3.0
6,hess staatsministerium,NaN,NaN
7,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,0.0
8,freie und hansestadt hamburg,NaN,NaN
9,hess staatsministerium,NaN,NaN
10,hansestadt hamburg sozialbehörde amt für wiede...,hansestadt hamburg sozialbehörde amt für wiede...,1.0
12,amt für wiedergutmachung stadt bonn,amt für wiedergutmachung bremen,9.0
13,hess staatsministerium,NaN,NaN
14,hess staatsministerium,NaN,NaN
15,kreisaußerhelfsausschübe,kreissonderhilfsausschuß delmenhorst,12.0
16,bundeskartei,kassel,3.0
17,der innernister des landes nordrhein westfalen...,der innenminister des landes nordrhein westfal...,0.0
18,hess staatsministerium,NaN,NaN
19,kreissonderhilfsschübe peine,kreissonderhilfsausschuß delmenhorst,9.0
20,regierungsbezirksamt für wiedergutmachung und ...,regierungsbezirksamt für wiedergutmachung und ...,6.0
21,hess staatsministerium,NaN,NaN

In [31]:
total = len(df_matches_token_swap)
max_dist = int(df_matches_token_swap['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches_token_swap['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 25402 (7.23%)
MatchDistance = 1: 20177 (5.75%)
MatchDistance = 2: 6929 (1.97%)
MatchDistance = 3: 24342 (6.93%)
MatchDistance = 4: 41748 (11.89%)
MatchDistance = 5: 6293 (1.79%)
MatchDistance = 6: 24025 (6.84%)
MatchDistance = 7: 3830 (1.09%)
MatchDistance = 8: 6655 (1.90%)
MatchDistance = 9: 24577 (7.00%)
MatchDistance = 10: 3689 (1.05%)
MatchDistance = 11: 2849 (0.81%)
MatchDistance = 12: 13240 (3.77%)
MatchDistance = 13: 4714 (1.34%)
MatchDistance = 14: 1555 (0.44%)
MatchDistance = 15: 3294 (0.94%)
MatchDistance = 16: 3072 (0.87%)
MatchDistance = 17: 4192 (1.19%)
MatchDistance = 18: 1918 (0.55%)
MatchDistance = 19: 13472 (3.84%)
MatchDistance = 20: 1324 (0.38%)
MatchDistance = 21: 2064 (0.59%)
MatchDistance = 22: 691 (0.20%)
MatchDistance = 23: 17697 (5.04%)
MatchDistance = 24: 1092 (0.31%)
MatchDistance = 25: 433 (0.12%)
MatchDistance = 26: 201 (0.06%)
MatchDistance = 27: 669 (0.19%)
MatchDistance = 28: 1417 (0.40%)
MatchDistance = 29: 1916 (0.55%)
MatchDistance = 30: 176 (0.05%)
MatchDistance = 31: 473 (0.13%)
MatchDistance = 32: 161 (0.05%)
MatchDistance = 33: 870 (0.25%)
MatchDistance = 34: 44 (0.01%)
MatchDistance = 35: 52 (0.01%)
MatchDistance = 36: 34 (0.01%)
MatchDistance = 37: 40 (0.01%)
MatchDistance = 38: 20 (0.01%)
MatchDistance = 39: 30 (0.01%)
MatchDistance = 40: 22 (0.01%)
MatchDistance = 41: 5 (0.00%)
MatchDistance = 42: 7 (0.00%)
MatchDistance = 43: 14 (0.00%)
MatchDistance = 44: 11 (0.00%)
MatchDistance = 45: 5 (0.00%)
MatchDistance = 46: 7 (0.00%)
MatchDistance = 47: 5 (0.00%)
MatchDistance = 48: 4 (0.00%)
MatchDistance = 49: 1 (0.00%)
MatchDistance = 50: 1 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 1 (0.00%)
MatchDistance = 53: 0 (0.00%)
MatchDistance = 54: 3 (0.00%)
MatchDistance = 55: 14 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 2 (0.00%)
MatchDistance = 58: 2 (0.00%)
MatchDistance = 59: 2 (0.00%)
MatchDistance = 60: 10 (0.00%)
MatchDistance = 61: 4 (0.00%)

# Calling LLM via API using NaN values

In [ ]:
from groq import Groq
from huggingface_hub import InferenceClient
from huggingface_hub.utils import HfHubHTTPError

import time
import json
import os
from dotenv import load_dotenv
from tqdm import tqdm

In [ ]:
load_dotenv()

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "groq").strip().lower()
HF_MODEL = os.getenv("HF_MODEL", "Qwen/Qwen3-8B")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")

if LLM_PROVIDER == "huggingface":
    HF_API_TOKEN = os.getenv("HF_API_KEY")
    if not HF_API_TOKEN:
        raise ValueError("HF_API_KEY is required when LLM_PROVIDER='huggingface'")
    client = InferenceClient(
        model=HF_MODEL,
        token=HF_API_TOKEN
    )
    ACTIVE_MODEL = HF_MODEL
elif LLM_PROVIDER == "groq":
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")
    if not GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY is required when LLM_PROVIDER='groq'")
    client = Groq(api_key=GROQ_API_KEY)
    ACTIVE_MODEL = GROQ_MODEL
else:
    raise ValueError("LLM_PROVIDER must be either 'huggingface' or 'groq'")

print(f"Using LLM provider: {LLM_PROVIDER}, model: {ACTIVE_MODEL}")

offices_list = "\n".join([f"- {office}" for office in compensation_offices])

In [ ]:

def get_llm_match_batch(query_names, offices_list, max_retries=3):
    
    queries = "\n".join([f"{i+1}. \"{name}\"" for i, name in enumerate(query_names)])
    
    prompt = f"""You are an expert at matching German compensation office names (Entschädigungsämter).

Given these query names:
{queries}

Find the BEST match for EACH from this list:
{offices_list}

Rules:
1. Return ONLY a numbered list with the exact name from the list
2. Consider spelling variations and OCR errors
3. If no match exists, write \"NO_MATCH\"
4. Format: \"1. Matching Name\" or \"1. NO_MATCH\"

Answers:"""

    messages = [{"role": "user", "content": prompt}]
    
    for attempt in range(max_retries):
        try:
            if LLM_PROVIDER == "huggingface":
                response = client.chat_completion(
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            elif LLM_PROVIDER == "groq":
                response = client.chat.completions.create(
                    model=ACTIVE_MODEL,
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            else:
                raise ValueError(f"Unsupported LLM provider: {LLM_PROVIDER}")
            
            matches = []
            lines = text.split('\n')
            for line in lines:
                line = line.strip()
                if line and len(line) > 0 and line[0].isdigit():
                    parts = line.split('.', 1) if '.' in line else line.split(')', 1)
                    if len(parts) > 1:
                        match = parts[1].strip()
                        matches.append(match)
            
            while len(matches) < len(query_names):
                matches.append("PARSE_ERROR")
            
            return matches[:len(query_names)]
            
        except HfHubHTTPError as e:
            error_str = str(e).lower()
            if "429" in str(e) or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in str(e) or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  # Signal to stop processing
            elif "503" in str(e) or "loading" in error_str:
                print(f"Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"HTTP Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
        except Exception as e:
            error_str = str(e).lower()
            if "429" in error_str or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in error_str or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  
            elif "503" in error_str or "loading" in error_str:
                print("Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
    
    return ["ERROR"] * len(query_names)

if len(no_matched_office_df) >= 2:
    test_names = no_matched_office_df['CompensationOffice1'].iloc[:2].tolist()
    print(f"Testing with:")
    for i, name in enumerate(test_names):
        print(f"  {i+1}. {name}")
    print()
    results = get_llm_match_batch(test_names, offices_list)
    if results:
        print("LLM suggested matches:")
        for i, result in enumerate(results):
            print(f"  {i+1}. {result}")
    else:
        print("API limit reached during test!")

Testing with:
  1. hess staatsministerium
  2. nan

HTTP Error: (Request ID: Root=1-69b1eb80-71adc530557736b071097d90;d9f9dd39-1eb3-4ef0-ba3c-5262937b9357)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb80-71adc530557736b071097d90;d9f9dd39-1eb3-4ef0-ba3c-5262937b9357)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb8b-327d3b150fb21f54500eaa1b;53e79627-7379-4e6b-b427-8c7f26fab5c4)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb8b-327d3b150fb21f54500eaa1b;53e79627-7379-4e6b-b427-8c7f26fab5c4)

Bad request:
HTTP Error: (Request ID: Root=1-69b1eb96-03491cd562a1abed5f8cafe4;88b979cc-beaa-4cfd-bf6d-8c5d12e7cb32)

Bad request:
LLM suggested matches:
  1. ERROR
  2. ERROR
HTTP Error: (Request ID: Root=1-69b1eb96-03491cd562a1abed5f8cafe4;88b979cc-beaa-4cfd-bf6d-8c5d12e7cb32)

Bad request:
LLM suggested matches:
  1. ERROR
  2. ERROR

In [ ]:
BATCH_SIZE = 10
DELAY_BETWEEN_BATCHES = 5  

output_file = 'hf_llm_matches_progress.jsonl'

processed = set()
llm_matches = []
try:
    with open(output_file, 'r') as f:
        for line in f:
            entry = json.loads(line)
            llm_matches.append(entry)
            processed.add(entry['CompensationOffice1'])
    print(f"Resuming from {len(processed)} already processed entries")
except FileNotFoundError:
    print("Starting fresh")

df_remaining = no_matched_office_df[~no_matched_office_df['CompensationOffice1'].isin(processed)]
print(f"Remaining to process: {len(df_remaining)}")

total_batches = (len(df_remaining) + BATCH_SIZE - 1) // BATCH_SIZE
api_limit_reached = False

for batch_idx in tqdm(range(total_batches), desc="Processing batches"):
    if api_limit_reached:
        break
        
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(df_remaining))
    
    batch_df = df_remaining.iloc[start_idx:end_idx]
    batch_names = batch_df['CompensationOffice1'].tolist()
    
    batch_results = get_llm_match_batch(batch_names, offices_list)
    
    if batch_results is None:
        print("\nAPI limit reached! Saving progress and stopping.")
        api_limit_reached = True
        break
    
    for i, (idx, row) in enumerate(batch_df.iterrows()):
        entry = {
            'CompensationOffice1': row['CompensationOffice1'],
            'MatchedOffice': row['MatchedOffice'],
            'MatchDistance': float(row['MatchDistance']) if pd.notna(row['MatchDistance']) else None,
            'LLMMatch': batch_results[i] if i < len(batch_results) else "ERROR"
        }
        llm_matches.append(entry)
        
        with open(output_file, 'a') as f:
            f.write(json.dumps(entry) + '\n')
    
    if batch_idx < total_batches - 1 and not api_limit_reached:
        time.sleep(DELAY_BETWEEN_BATCHES)

df_hf_matches = pd.DataFrame(llm_matches)
print(f"\nProcessed: {len(df_hf_matches)} entries")
if api_limit_reached:
    print("Note: Processing stopped due to API limit. Run again later to continue.")
df_hf_matches.head(20)

In [ ]:
valid_matches = df_hf_matches[~df_hf_matches['LLMMatch'].isin(['NO_MATCH', 'ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]
no_matches = df_hf_matches[df_hf_matches['LLMMatch'] == 'NO_MATCH']
errors = df_hf_matches[df_hf_matches['LLMMatch'].isin(['ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]

print(f"Total processed: {len(df_hf_matches)}")
print(f"LLM found matches: {len(valid_matches)} ({len(valid_matches)/max(len(df_hf_matches),1)*100:.1f}%)")
print(f"No match found: {len(no_matches)}")
print(f"Errors: {len(errors)}")

df_hf_matches.to_excel('compensation_office_hf_llm_matches.xlsx', index=False)
print("\nSaved to compensation_office_hf_llm_matches.xlsx")