In [1]:
import pandas as pd
from Levenshtein import distance
import numpy as np
import re

In [2]:
df_csv = pd.read_excel('2025_01_27_Liste der Entschädigungsämter mit Adressen, Varianten und Archiven.xlsx')
df_csv.head()

,Layout class,Filename,Bundesland,CompensationOffice,Zuständiges Archiv,Zuständiges Archiv - GND-Nummer,Unnamed: 6
0,ABC-Karten,1930_12_13_41_0,Niedersachsen,Stadt Celle,Niedersächsisches Landesarchiv,6510041-4,NaN
1,ABC-Karten,1901_03_02_64_0,Niedersachsen,Kreissonderhilfsausschuß \nDelmenhorst,Niedersächsisches Landesarchiv,6510041-4,NaN
2,ABC-Karten,1907_12_31_115_0,Niedersachsen,Goslar,Niedersächsisches Landesarchiv,6510041-4,NaN
3,ABC-Karten,1909_01_06_66_0,Niedersachsen,Goslar. Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN
4,ABC-Karten,1904_01_08_54_0,Niedersachsen,Göttingen-Stadt,Niedersächsisches Landesarchiv,6510041-4,NaN

In [3]:
df_json = pd.read_json('compoff_extracted.jsonl', lines=True)
df_json.head()

,CompensationOffice1,BZKNr,filename
0,Regierungsbezirksamt für Wiedergutmachung und ...,65477,1875_00_00_101_0.jpg
1,Landesamt für die Wiedergutmachung Karlsruhe,EK 20093 A,1875_04_05_16_0.jpg
2,Niedersachsen,1 27574 c,1875_06_15_14_0.jpg
3,Bezirksamt für Wiedergutmachung Neustadt a.d.W.,200 488,1875_04_15_1_0.jpg
4,Entschädigungsamt Berlin,70 002,1875_07_12_9_0.jpg

In [4]:
print(len(df_csv))
print(len(df_json))

n = df_json['CompensationOffice1'].isin(df_csv['CompensationOffice']).sum()
print(f'Number of matches: {n}')

424
1901284
Number of matches: 1121989

# Matching based on Lvenshtein Distance

In [5]:
compensation_offices = list(df_csv['CompensationOffice'])

# remove linebreaks and sequences of whitespaces
def remove_linebreak(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

# return the minimum distance and the best match up to a threshold of half the length of the cleaned name
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = remove_linebreak(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'].apply(remove_linebreak),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
3,bezirksamt für wiedergutmachung neustadt a.d.w.,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,2.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
6,köln,Köln,0.0
7,amt für wiedergutmachung des selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,9.0
8,landesentschädigungsamt schleswig-holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,0.0
9,hessen kassel,Hessen Kassel,0.0
10,nordrhein-westfalen,Nordrhein-Westfalen,0.0
11,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
12,bezirksamt für wiedergutmachung köln,Bezirksamt\nfür Wiedergutmachung\nMainz,4.0
13,der regierungspräsidium düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,köln,Köln,0.0
15,bezirksamt für wiedergutmachung trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,"hansestadt hamburg, sozialbehörde, amt für wie...","Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,freiburg,Freiburg,0.0
18,hessen,HESSEN,0.0
19,regierungsbezirk für wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,4.0

In [6]:
print(f"Max MatchDistance: {df_matches['MatchDistance'].max()}")

Max MatchDistance: 67.0

In [7]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1422538 (74.82%)
MatchDistance = 1: 64054 (3.37%)
MatchDistance = 2: 24334 (1.28%)
MatchDistance = 3: 22113 (1.16%)
MatchDistance = 4: 43303 (2.28%)
MatchDistance = 5: 10644 (0.56%)
MatchDistance = 6: 24848 (1.31%)
MatchDistance = 7: 6033 (0.32%)
MatchDistance = 8: 5534 (0.29%)
MatchDistance = 9: 21285 (1.12%)
MatchDistance = 10: 4700 (0.25%)
MatchDistance = 11: 4947 (0.26%)
MatchDistance = 12: 10438 (0.55%)
MatchDistance = 13: 3892 (0.20%)
MatchDistance = 14: 2818 (0.15%)
MatchDistance = 15: 2491 (0.13%)
MatchDistance = 16: 2054 (0.11%)
MatchDistance = 17: 2153 (0.11%)
MatchDistance = 18: 2218 (0.12%)
MatchDistance = 19: 5044 (0.27%)
MatchDistance = 20: 1473 (0.08%)
MatchDistance = 21: 1185 (0.06%)
MatchDistance = 22: 13153 (0.69%)
MatchDistance = 23: 1518 (0.08%)
MatchDistance = 24: 17725 (0.93%)
MatchDistance = 25: 582 (0.03%)
MatchDistance = 26: 1000 (0.05%)
MatchDistance = 27: 269 (0.01%)
MatchDistance = 28: 242 (0.01%)
MatchDistance = 29: 635 (0.03%)
MatchDistance = 30: 267 (0.01%)
MatchDistance = 31: 1225 (0.06%)
MatchDistance = 32: 256 (0.01%)
MatchDistance = 33: 843 (0.04%)
MatchDistance = 34: 349 (0.02%)
MatchDistance = 35: 146 (0.01%)
MatchDistance = 36: 649 (0.03%)
MatchDistance = 37: 44 (0.00%)
MatchDistance = 38: 31 (0.00%)
MatchDistance = 39: 45 (0.00%)
MatchDistance = 40: 19 (0.00%)
MatchDistance = 41: 36 (0.00%)
MatchDistance = 42: 11 (0.00%)
MatchDistance = 43: 15 (0.00%)
MatchDistance = 44: 17 (0.00%)
MatchDistance = 45: 7 (0.00%)
MatchDistance = 46: 5 (0.00%)
MatchDistance = 47: 8 (0.00%)
MatchDistance = 48: 8 (0.00%)
MatchDistance = 49: 2 (0.00%)
MatchDistance = 50: 4 (0.00%)
MatchDistance = 51: 4 (0.00%)
MatchDistance = 52: 2 (0.00%)
MatchDistance = 53: 3 (0.00%)
MatchDistance = 54: 2 (0.00%)
MatchDistance = 55: 0 (0.00%)
MatchDistance = 56: 1 (0.00%)
MatchDistance = 57: 1 (0.00%)
MatchDistance = 58: 1 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 1 (0.00%)
MatchDistance = 61: 20 (0.00%)
MatchDistance = 62: 2 (0.00%)
MatchDistance = 63: 4 (0.00%)
MatchDistance = 64: 5 (0.00%)
MatchDistance = 65: 2 (0.00%)
MatchDistance = 66: 0 (0.00%)
MatchDistance = 67: 1 (0.00%)

In [8]:
df_nomatches = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]

df_nomatches.sort_values('MatchDistance', ascending=True).to_excel('compensation_office_nomatches.xlsx', index=False)

# Matching without Punctuation

In [9]:
compensation_offices = list(df_csv['CompensationOffice'])

# remove linebreaks, punctuation and sequences of whitespaces
def remove_linebreak_punctuation(s):
    s = str(s).replace('\n', ' ').replace('\r', ' ')
    p = ['?', '!', '.', ',', ';', ':', '-', '_', '(', ')', '[', ']', '{', '}', '"', "'", '/']
    for char in p:
        s = s.replace(char, ' ')
    return re.sub(r'\s+', ' ', s).strip().lower()

#updated version of get_min_distance_dynamic_normalized that also removes punctuation
def get_min_distance_dynamic_normalized(name):
    name_clean = remove_linebreak_punctuation(name)
    threshold = len(name_clean) // 2
    
    min_dist = float('inf')
    best_match = None
    for office in compensation_offices:
        office_clean = remove_linebreak_punctuation(office)
        d = distance(name_clean, office_clean)
        if d == 0:
            return 0, office
        if d < min_dist:
            min_dist = d
            best_match = office
    if min_dist <= threshold:
        return min_dist, best_match
    return np.nan, None

results = df_json['CompensationOffice1'].apply(get_min_distance_dynamic_normalized)

df_matches = pd.DataFrame({
    'CompensationOffice1': df_json['CompensationOffice1'].apply(remove_linebreak_punctuation),
    'MatchedOffice': results.apply(lambda x: x[1]),
    'MatchDistance': results.apply(lambda x: x[0])
})

df_matches.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
0,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt \nfür Wiedergutmachung \n...,0.0
1,landesamt für die wiedergutmachung karlsruhe,Landesamt für die Wiedergutmachung \nKarlsruhe,0.0
2,niedersachsen,Niedersachsen,0.0
3,bezirksamt für wiedergutmachung neustadt a d w,Bezirksamt \nfür Wiedergutmachung \nNeustadt a...,0.0
4,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
5,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
6,köln,Köln,0.0
7,amt für wiedergutmachung des selbstkantkreises...,Amt für Wiedergutmachung des Selfkantkreises G...,7.0
8,landesentschädigungsamt schleswig holstein in ...,Landesentschädigungsamt\nSchleswig-Holstein in...,0.0
9,hessen kassel,Hessen Kassel,0.0
10,nordrhein westfalen,Nordrhein-Westfalen,0.0
11,entschädigungsamt berlin,Entschädigungsamt Berlin,0.0
12,bezirksamt für wiedergutmachung köln,Bezirksamt\nfür Wiedergutmachung\nMainz,4.0
13,der regierungspräsidium düsseldorf,Der Regierungspräsident Düsseldorf,3.0
14,köln,Köln,0.0
15,bezirksamt für wiedergutmachung trier,Bezirksamt für Wiedergutmachung Trier,0.0
16,hansestadt hamburg sozialbehörde amt für wiede...,"Hansestadt Hamburg, Sozialbehörde, Amt für Wie...",1.0
17,freiburg,Freiburg,0.0
18,hessen,HESSEN,0.0
19,regierungsbezirk für wiedergutmachung und verw...,Regierungsbezirksamt\nfür Wiedergutmachung\nun...,4.0

In [10]:
total = len(df_matches)
max_dist = int(df_matches['MatchDistance'].max()) + 1
for i in range(max_dist):
    count = (df_matches['MatchDistance'] == i).sum()

    pct = count / total * 100    
    print(f'MatchDistance = {i}: {count} ({pct:.2f}%)')

MatchDistance = 0: 1474765 (77.57%)
MatchDistance = 1: 33750 (1.78%)
MatchDistance = 2: 10717 (0.56%)
MatchDistance = 3: 19463 (1.02%)
MatchDistance = 4: 43260 (2.28%)
MatchDistance = 5: 9386 (0.49%)
MatchDistance = 6: 23139 (1.22%)
MatchDistance = 7: 5620 (0.30%)
MatchDistance = 8: 6111 (0.32%)
MatchDistance = 9: 22174 (1.17%)
MatchDistance = 10: 3724 (0.20%)
MatchDistance = 11: 3588 (0.19%)
MatchDistance = 12: 10586 (0.56%)
MatchDistance = 13: 3822 (0.20%)
MatchDistance = 14: 2880 (0.15%)
MatchDistance = 15: 2658 (0.14%)
MatchDistance = 16: 2481 (0.13%)
MatchDistance = 17: 2541 (0.13%)
MatchDistance = 18: 2527 (0.13%)
MatchDistance = 19: 15769 (0.83%)
MatchDistance = 20: 2457 (0.13%)
MatchDistance = 21: 1501 (0.08%)
MatchDistance = 22: 1215 (0.06%)
MatchDistance = 23: 18172 (0.96%)
MatchDistance = 24: 1059 (0.06%)
MatchDistance = 25: 569 (0.03%)
MatchDistance = 26: 233 (0.01%)
MatchDistance = 27: 528 (0.03%)
MatchDistance = 28: 949 (0.05%)
MatchDistance = 29: 1741 (0.09%)
MatchDistance = 30: 384 (0.02%)
MatchDistance = 31: 480 (0.03%)
MatchDistance = 32: 269 (0.01%)
MatchDistance = 33: 794 (0.04%)
MatchDistance = 34: 72 (0.00%)
MatchDistance = 35: 75 (0.00%)
MatchDistance = 36: 29 (0.00%)
MatchDistance = 37: 43 (0.00%)
MatchDistance = 38: 26 (0.00%)
MatchDistance = 39: 39 (0.00%)
MatchDistance = 40: 29 (0.00%)
MatchDistance = 41: 13 (0.00%)
MatchDistance = 42: 16 (0.00%)
MatchDistance = 43: 8 (0.00%)
MatchDistance = 44: 10 (0.00%)
MatchDistance = 45: 9 (0.00%)
MatchDistance = 46: 6 (0.00%)
MatchDistance = 47: 10 (0.00%)
MatchDistance = 48: 7 (0.00%)
MatchDistance = 49: 0 (0.00%)
MatchDistance = 50: 3 (0.00%)
MatchDistance = 51: 0 (0.00%)
MatchDistance = 52: 3 (0.00%)
MatchDistance = 53: 1 (0.00%)
MatchDistance = 54: 4 (0.00%)
MatchDistance = 55: 13 (0.00%)
MatchDistance = 56: 8 (0.00%)
MatchDistance = 57: 3 (0.00%)
MatchDistance = 58: 2 (0.00%)
MatchDistance = 59: 3 (0.00%)
MatchDistance = 60: 8 (0.00%)
MatchDistance = 61: 1 (0.00%)
MatchDistance = 62: 0 (0.00%)
MatchDistance = 63: 0 (0.00%)
MatchDistance = 64: 1 (0.00%)

In [11]:
df_no_matches_no_punctuation = df_matches[(df_matches['MatchDistance'] > 0) | (df_matches['MatchDistance'].isna())]
df_no_matches_no_punctuation = df_no_matches_no_punctuation.sort_values('MatchDistance', ascending=False)
df_no_matches_no_punctuation.head(20)

,CompensationOffice1,MatchedOffice,MatchDistance
422246,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,64.0
47910,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",61.0
227493,regierungsbezirksamt für wiedergutmachung und ...,Regierungsbezirksamt für Wiedergutmachung und ...,60.0
1135308,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1881670,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1617342,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1138927,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1126699,der regierungspräsident – dezernat für wiederg...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
293761,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",60.0
1827229,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,60.0
1309098,der herr regierungspräsident dezernat für wied...,a) Der Regierungspräsident - Dezernat für Wied...,59.0
1594676,a der regierungspräsident dezernat f wiedergut...,"a) Der Regierungspräsident, Dezernat für Wiede...",59.0
1247401,regierungspräsident dezernat für wiedergutmach...,Der Oberkreisdirektor -Amt für Wiedergutmachun...,59.0
1372604,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",58.0
514604,freie und hansestadt hamburg behörde für arbei...,"Behörde für Arbeit, Gesunheit und Soziales - ...",58.0
1897187,der regierungspräsident dezernat 14 in detmold...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
68367,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
393399,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,57.0
1857448,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,56.0
1590248,der regierungspräsident dezernat für wiedergut...,Der Regierungspräsident \n- Dezernat für Wiede...,56.0

In [ ]:
df_no_matches_no_punctuation.to_excel('compensation_office_nomatches_no_punctuation.xlsx', index=False)

# No Matches

In [12]:
no_matched_office_df = df_nomatches[df_nomatches['MatchDistance'].isna()]

no_matched_office_df

,CompensationOffice1,MatchedOffice,MatchDistance
21,hess. staatsministerium,NaN,NaN
30,nan,NaN,NaN
32,freie und hansestadt hamburg,NaN,NaN
34,hess. staatsministerium,NaN,NaN
40,nan,NaN,NaN
...,...,...,...
1901203,reg.-präsident / präsident des verw.-bezirks h...,NaN,NaN
1901238,hng,NaN,NaN
1901254,reg.-präsident /präsident des vereinsbezirks h...,NaN,NaN
1901262,bayrisches landesamt für verfolgtenwesen,NaN,NaN
1901263,reg.-präsident / präsident des verw.bezirks,NaN,NaN

In [13]:
no_matched_office_df_set = set(no_matched_office_df['CompensationOffice1'])

len(no_matched_office_df_set)
for office in no_matched_office_df_set:
    print(office)

6.7.28
w8in
r.a. rumpel
st. h. 6664
bmf - v34
ostalbisch-land
hessisches ministerium für jugend, familie und gesundheit
sondervermögens- und bauförderungsbehörde
feststellungsbeschv. stuttgart erhalten
rheinland-pfälzische landesregierung, neustadt a.d. weinstr.
st. h. 1665/1966 h
niedergmachungsämter von berlin
ksha düsseldorf-stadt
betty ludwig rogert albert goetz irma herbert
bayerisches landesstelle
holzminden
niedersachsen-präsidium / präsident des verw.-bezirks braunschweig
sachverständigenstelle für befristete reg.
n
länderzentrale für die regelung von schadensersatzansprüchen
reg.-präsident / präsident des verw.-bezirks-hildesheim
deutscher pellmeldung
sta
tr. bayrisches landesarchiv
kshä winsen/l.
st. h. 2050
usmf
freiburg, karlsruhe
niedersachsen / reg.-präsident / präsident des verw.-bezirks hildesheim
nentwich
bu, verw, amt
namenloses bayerisches versicherungsamt
bayrisches landesamt für verfolgte des nationalsozialismus
kreissonderhilfsausschübe
e 2742
landesarchiv für baden-württemberg, stuttgart
stadtverwaltung des bezirks einbeek
regierungsbezirk köln und verwaltete vermögen
e 9340
e 6476
nevrov
k61
lro nw br d'd
staatsschutzsozialamt
4 10 1939
doppelmeldung saarburg
bundeskartei in osnabrück
aurich, 1. outfr.
hilfsfond wien
kroa linda
rp köln: doppelet für einfach gültig
schweiz
kreissozialamt d. landkreises blankenburg (brit. zone)
sondervermögens-u.
entschädigungsbehörde für verfolgtenbezirkskartei und wiedergutmachung koblenz
sondervermögens-u. bayerische verwaltung
landeszentrale - kriminalstatistik
bundes.amt
ksha gölle/land
bad-kreuznach
niedersachsen reg.-präsident / präsident des verw.-bezirkskox hannover
sen.f.fin.
hauptbesold
kirch
r.a. coenen
reg.-präsident / präsident des verw.-bezirks xx hannover
vereinigte nationen für flüchtlinge
hußisches versicherungsamt
niedersachsen-präsident / präsident des memmelsdorfer bezirks
kreissozialhilfsschübe colle/land
altenkirchen/westerwald
landesbezirksstelle, stuttgart
buyer landeszentrale
a 807 c 2880
ebersbach/baden kr. heidelberg
berlin/352 284
der bundesbeauftragte für die vermögensverwaltung
reg.-präsident / präsident des vorw. bezirks
obernormen am 2 von düsseldorf 4520/26
ksha landkreis göttingen
ksha gelle-land
st. h. 2116 m
landeszentrale für die vergütung
niedersachsen-präsidium/präsidium des verw.-bezirks oldenburg
bhf - vts
bayesische verfolgungsamt
e 4397 f 750
wiener landesgericht
generalkonsulat, new york
regierungsbezirk main
lahnsentrale - registrierstelle
regierungsbezirk trier (1001)
x81nt
an bundeskartelle
bmt
landesamt für die rückstellung von kriegsfolgeleidtragenden
darmstadt stuttgart
kreissozialamt nordhorn
reg.-präsident präsident des verw.bezirks sildeshelm
wiesner landesreg.
niedersachsen-präsident / reg.-präsident hannover
a 470
landsmannschaft der verfolgten des naziregimes
reg.-präsident / präsident des verw.-bezirks h.annover
bmf-vb 4
ausl.amt.bremen
doppelermeldung münchen
kroßdorf
payerische versicherungsgesellschaft
bayisches hauptstaatsarchiv
kreissozialamt spiring
regional office for compensation for victims of national socialism and their assets
regional office for compensation and administration of assets, neustadt a.d. weinstr.
tr. bayerisches landeszentrum
düsseldorfer beauftragter
landesrentenanstalt
regierung potsdam
königlich bayerische staatskommission für die wiedergutmachung
verw.amt münchen
bayerisches landesamt für gesetzliche versicherungen münchen 2
kammerentscheid
schreiberding
lg. bochum
hauptbeschied
kurt schwa
regierungsbezirk potsdam
niedersachsen / präsident / präsidentenamt / bezirksamt hannover
ansgel. amt bremen
regional office for compensation for victims of nazi persecution and their assets
kreissozialamt des landkreises graf. sch. sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch., sch
st. h. 2729 sch
darussadat 24591
sondervermögensbehörde bayern
12 7 23
tr. landesverfolgtenbehörde münchen 2
kreisaußerordentliche hauptschadensbehörde hannover-schöneweide
united restitution office, frankfurt/m., grunburgweg 119
st. h. 3204 w
kreissonderhilfsschutz
d2 4910
ksha zellerrfeld
kreisonderhlfsschuss
landesanstalt für die regelung von vermögensangelegenheiten
a) der regierungspräsident -dezernat f.wiedergutmachung- detmold b) landkreis höxter. amt für wiedergutmachung- höxter/weser
tr. grünstein
ksha wölfenbüttel
ham-iv
united restitution office, ffm., grüneburgweg 119
stuttgart-s, haus waldstein 2
reg.-präsident / präsident des vorw.bezirks hannover
doppelmeldung tübingen
regierung amstbeern
dme
aeros linzau
regierungsbezirk trier
anspraltiy amt bohn
kreissozialamt minden
niedersachsen reg. präsident / präsident des verw.-bezirks hannover
service-center köln
theverisches namentliches verfolgtenregister
united restitution organization, frankfurt / main, grüneburgweg 119
stadtverwaltung wuppertal
hohes kommisariat der vereinigten nationen für flüchtlinge
r.a.s. porat
königlich-preußische prälz
lv/a/h
st. h. 1965 h
16
ra. weber 15/108
doppelfeldung
landesverwaltungsamt
vorgang an koblenz
trägerschaft
nürnberger amtsgruppe
bayer. bundesarchiv
frankfurt
kreissozialhilfsausschuss stade
munster, arnsberg
ra.
ereis linlan
kreissozialhilfsschübe peine
kreisbehörde
niedersachsen-präsident / präsident des vermögensbeziekts
reg.-präsidium präsident des verw.-bezirks braunschweig
bayrisches landesamt für die opfer des nationalsozialismus
anspruchsmuseum der rückerstattung
landesamt für vertriebene, abteilung wiedergutmachung
rat. dr. mosse 12 münchener str. köln
u.r.o.
vereinten kriegsopferfürsorge
landesarchiv muenchen abteilung 11
münchner verein zur förderung der präzedenz e.v.
st. franzfurt
kreisaußerhelfsausschub watenstedt-salzgitter
niedersachsen - reg.-präsident / präsident des verwaltungsgerichts
niedersachsen reg.-präsident/präsident des verw.-bezirks oldenburg
bezirksamt koblenz
kreisonderhlfasschuf peine
reg.-präsid. / präsident des verw.-bezirks
landesbeamtentum der bundesrepublik deutschland
511
gwiazda/in israel stern
alpern, ilan chodorow, wolf chodorow, dagobert eigenfeld, malka davidk, juda hersch chodorow
brauneck
deutsches reichsverwaltungsamt düsseldorf
kreissozialamt hoy
doppelbeiligung berlin
preußisches kultusministerium
doppelmeilung münchen
kreissozialamt hannover-kampen
regierungsbezirk neuburg
israel office
düsseldorfer landesstelle
regierungsamt aachen (mfv)
landesjustizverwaltung württemberg
kreisonderhauptschutz
wess. staatsministerium
hessen - ns-haftpflicht
karlruhe, außenstelle freiburg
ko11
bundesbank
an der bundesbank hannover
ausland
3hf - vb3 - 04081889/10031
tr. bressau
jdzn
niedersachsen / reg.-präsident / präsident des verw.-bezirks braunschweig
könig:präsidium: präsident des verw.-bezirks oldenburg/old.
d 1 1070
ksha oldenburg i.oldb.
dm 500.---erh.ausw.beihilfe
schreiber des verfolgten
regierung brünn (mähren)
r.a. theisen
st. h. 2330
stammiert
haupt nachshalt
landesamt zentral-registratur
kreissozialhilfsausschuss watenstedt-salzgitter
reg.-präsident / präsident des verw.-bezirks
roland
kreis isr.
rheinland-pfälzische entschädigungsbehörde
beschädigtenrente § 15 beg
doppelung
oldeburg (oldb)
niedersachsen - präsident / präsident des vermögensbeirats hannover
niedersachsen - präsident / präsident des verw.-bezirks oldenburg
staatsanw. l. g. frankfurt/main
bezirksamt köln
united restitution organization, frankfurt/m., grünburgweg 119
niedersachsen - präsident / präsident / des verw.-bezirks hannover
führer
an bundeseskartotek
landes justizverwaltung, münchen
niedersachsen-präsident / präsident des landesgerichtsbezirks hannover
h. - kond
kreisaußerhelfsausschuss peine
bürg
kreisaußerhilfsausschüβ
reg.-präsident / präsident des verw.bezirkskox hannover
chemnitz
bayrisches landesamt für statistik und archiv
neustadt - kaiserslautern
landesamt für vertriebene, flüchtlinge und kriegsgeschädigte, köln
kshatei
rosenberg, schule - geb. 48.99
1051
a.z. dp. 133
staatsanwaltschaft frankfurt
doppelbeilung münchen
restitution office, p. o. box 1180, johannesburg, s-afrika
niedersachsen - präsident / bundesarchiv
reg.-präsid. / präsident des verw.-bezirks hannover
oran
leipzig n. 45
bayerische landesanstalt für versäumnis- und schadensersatz
niedersachsen-präsident / präsident des yenwo-bezirks
he 618
amt für wiedergutmachung, freie und hansestadt hamburg, arbeit- und sozialbehörde, 2 hamburg 76, adolph-schönfelder-straße 5
reg.-präsident / präsident des vewobekdscx hannover
unbekannt
bayer. staatsanwalt
niedersachsen g.-präsident / präsident des verw.bezirksxx hannover
der reg.prsä.detmold
hild. marb.
schrein
die vorg. des ksha celle-land
frankfurt/main
restitution authority
lg
doppelmeloung
medical board
nordhorn
rudesheimer finanzamt
entscheidungsberechtigte kommission
hess-niedermöller
ra uro frankfurt/main
regionalverwaltungsbehörde in münchen
südliches standesamt
tr. bayerisches landesamt
stadtthagen
stuttgart-s, haus wernigerode
b.a. dr. h. wolf
sen. f. fin
bez. amt deutschlanddorf
bayerische landeszentrale für die opfer des nationalsozialismus
x8lm
aurich i.octfrsld.
niedersachsen hannover, entschr.-behörde; reg.-präsid
bfh
st.h. 1250 d
reichsverfolgungsausschuss
königshausen-verlag
varläger
niedersachsen-präsident / präsident des vermögensverwaltungsgesetzes
rheinischer-palatiner
landesamt für die belange der ns-zeit
bundesekartei
freiburg i. br. / karlsruhe
lva rheinprovinz u. westf.-entschädigungsamt berlin
hilfsfonds / sammelstelle wien
st.h. 860 st.
stadthaus stadthaus
höherer verwaltungsgerichtshof
schreiber, dr. amth
bayerisches amter für vertriebene (münchen)
nazi-verfolgungsausschuss
kzn
kreissozialamt celle-stadt
m1
st. h. 744
kreissozialamt leer
regierungspräsidium für wien und wien-umgebung
wolm
bay. prof. wieschober
niedersachsen - reg.-präsident / präsidenten der merkmale
reg.-präs. - arnsberg
kreissozialhilfsschule wesermünde
höllwege
r8lm
o.st.anw.köln
kreissozialamt dortmund
regierungsbezirk meinz
niedersachsen - reg.-präsident / präsident des verwaltungsgerichts hannover
kreisondesonderhilfsausschuss
landeszentrale für politische bildung
niedersachsen / präsident des verw.-bezirks hannover
bayrisches archiv
landgericht münchen
bayrisches landesamt für kriegsopfer und kriegsversehrte
st. h. 2772
köln, riehl, pl. 2, 5000 köln 1
kreisonderschutzbehörde brake/wesermarsch
bpa
manistrat der stadt bremen
kowu
regional office for compensation and administration of estates, koblenz
tr. bayerisches landesamt für verfolgtenfragen
trier we 1815
reg.-präsident / präsidenten des verw.-bezirks lüneburg
rundesammlung der phänomen
an referat 10 zi. 413
kreissozialhilfesausschuss hoy
stuttgart-s, neue weinsteige 2
kreissonderhilfsschule watenstedt-salzgitter
st.h. 643 g
bayer. staatsanwalt berlin
ksha bückeburg
deutsche dienststelle
koppatz
niedersachsen-präsident / präsident des merw.-bezirks hannover
der amtshauptmann des landkreises nordrhein-westfalen
lg düsseldorf, i.g. hamburg
kzm
bundeskartei stuttgart
niedersachsen reg.-präsident/ präsident des verw.-bezirks
tr. landratsamt münchen ii
united restitution office, frankfurt/m. gruneburgweg 119
kreissozialamt hamburg-ohm
st.h. 1450 st.
reg.-präsident / präsident des verw.-bezirksvor
stuttgart-s, piusae wonniesie 2
kreissonderhilfsausschüf
friesland-fund
lv4 dortmund
köln (früher münster/westf.)
sondervermögens- und bayerwaltung
staatsanwaltschaft münchen
senat für finanzen
regierungsbezirkshauptmannschaft koblenz
landeshezirksstelle
rheinland-pfalz bezirksamt von koblenz für wiedergutmachung
bay. landesentsch
reg.-präsident des vewo-bezirks hannover
sp 4476 9
b 1704 c 2556 e 4685
karlruhe aussenstelle freiburg
schreibt. münchen
ksha leer/ostfriesl.
münchen eg 9840
abteilung für rückwanderer
ksha mepen
k618
st.h. 2410 r
ksha osterholz
kreissozialamt göttingen stadt
regierung
beg.-präsident / präsident des verw.-bezirks braunschweig
niedersachsen-präsidium / residenzbezirksverwaltung hannover
doppelmeldung hamburg
regional ansbach (melfi)
staatsanw. l.g. frankfurt / main
niedersachsen-präsident / präsident des/verw./bezirks/osnabrück
magdeborn/leipzig(sowj.z.)
st. m. 1436 r
und verwaltete vermögenskoblen
kreis linlaun
krois lindeau
höherer kommissar der flüchtlinge
kreissozialamt a. d. rhein
reg.-präsident / präsident des vew.-bezirks hannover
kota
k514
kollegium der sonderhelfsausschüsse
kshd
münchener staatministerium
kreissozialamt düsseldorf-stadt
d 2 1516 d3 543 e 2524
landesamt für bayerische verwaltung der flüchlinge, münchen
reg.-büro münster
niedersachsen - reg.-präsident / präsident des verw.-bezirks braunschweig
kreissozialamt münchen-pasing
schw.
kreissozialhilfsschule osterode/harz
amtsgericht arnsberg (wf)
regierung pirmasens
berlin nr. 377 321
stadtverwaltung bielefeld
kreissozialamt osnabrück
reg.-präsident präsident des verw.-bezirks silesheim
bayerisches landeszentrum für verfolgtenliteratur
ländesverwaltungsamt münchen
doppelbelung berlin
doppelmeldung braunschweig
e 633
kreissozialamt ulm
st. h. 2600 k
st. h. 12 16 k
altenkirchen'westerw.
kreis-sonderhilfsausschub
kreissozialhilfsschutz braunschweig-stadt
niedersachsen, reg.-präsidium, präsident des verw.-bezirks oldenburg
bekirksamt
aurich30stfriesland
landesherzogstoll
niedersachsen -präsident / präsident des verw.-bezirks hannover
rechtsverwaltungsbezirkskammer mainz
rabbinerbezirkssparkasse
berlin reg.nr.950
kreissozialamt bersenbrück
niedersachsenpräsidium präsident des verw.-bezirks oldenburg/old
st.h. 2755
tel-aviv jaffo
reg.-präsident / präsident des vorstandes der bundesbeihilfe
frankfurt/n.
köln, reichler pl. 2, 5000 köln 1
niedersachsen / reg.-präsident / präsident des verwaltungsbezirks hannover
hund. verw. amt
bisher e amt-münchen
reg.-präsident / präsident des vew. benenicks
st. h. a 6 b
regierungsbezirk würzburg und wehrmachtvermögensverwaltung neustadt
regierungsbezirk arnach (meßl.)
bayrisches landesamt für geschichtliche materialien
sachbearbeitung für bez. reg.
bayrisches wiedergutmachungsausschuss
dp assembly center i.r.o.
bund, fin, stg
sondervermögens-u. barverwaltung
kreisonderhfsausschuss
baft
reg.-präsident / präsident des merw.bezirks hannover
ksha hamm-pyrmont
regierungsbezirk arnswalde (1945-47)
traches
sozialamt münchen 2
cas trop-rauxel
reg.-präsident / präsident des mernwirkungs
hamburg 36, drehbahn 36 iv
niedersachsen reg.-präsident / präsident des verwaltungsgerichtshofs
landeskriegsverwaltungsstelle
landesamt für den bundesverband der opfer des nationalsozialismus
k 81n
3l 1662 b
tr.
e 7290
kreissozialhilfausschuss braunschweig-stadt
koerperliche betroffenheit (west)
reg.-präsident / präsident des merw.-bezirks hannover
bundesstelle köln
regierungsbezirk trier und verwaltete varländer
regionalamt fürstenberg (meckl.)
regierungsbezirkam
bayrisches l.e.a.
obernommen am 17.5.67 von neustadt 483557
kreissozialamt seer
kreissozialamt hildesheim-marienthal
sp 4493 b
th. r. s 1 r t 1
51n
reinhard anna (moff.)
reg.-präsident / präsidentenmodeksverw.bezirks hannover
düsseldorfer restitutionsspräsident
niedersachsen-präsident / landesarchiv hannover
wirtschaft
amt für wohlfahrt und sozialhilfe - wiedergutmachung
k81m
niedersachsen - präsident / präsident des landesarchivs
bay. landeszentrale
doppeld meldung
schwedisches
ksha norden
kreissonderbehelfsausschuss
heeresgruppe
reg.-präsident / präsident des vw-bekannt
köln, riehler pl. 2, 5000 köln 1
staatsschutz, sozialamt, lg. würzburg
landesdenkmalamt münchen und straßburg
gathesdheid
kreissozialamt götttingen
kreissozialamt cuxhaven
bureau de résititution
k 815
karlsruhe, bv in freiburg
kreissozialhilfsausschuss hann.
sachverständigenstelle für bez. rea.
an b 15. sep 1955
landesamt für die opfer der ns-zeit
doppelmeier, köln berlin
ks
ausgl. amt berlin
versicherungsamt
niedersachsen-präsident / president des verwaltungsgerichtshofs
landesjustizministerium
zuständigkeit für norddeutschland
amt für wiedergutmachung, freie und hansestadt hamburg, arbeit- und sozialbehörde
adlershtein & blaschke, düsseldorf, beethovenstr. 12
bayerisches verfolgtenamt
3699
fides vermögensberatung vornameverwaltungs-cmbh
st.h. 2536
reg. rat. münchen
regionalverwaltungsamt für flüchtlingsangelegenheiten
bayer. zent. stelle
okd wiedenbrück afv
thälmann
köln, riehler pl. 2, 5000 köln 4
tr. bayerisches verfolgtenamt
ocho.sches
regierungsbezirk münchen (doppel)
aurich /ostfriesland.
amt für kriegsopfer 82050
k 6 n
bund, zent, amt
ksha hannover-grünwald
kreissozialhilfsschule hannover-misburg
rug.-präsident / präsident des verw.-bezirks braunschweig
an bundesakartei
niedersachsen-präsident / präsident des nrw. bezirks
landesstelle für schadensersatz
kreissozialhilfsschule goslar-stadt
kreissozialamt göttingen - stadt
st. h. 617 k
s. schreiben bfa berlin
arnhem/niederlande, sickeres-plein 3
sondervermögens- und bauerwaltung
stadt. amt. dresden
v. koiering fölli übernommen
bayhuches landesamt für verfolgten
61n
regierung (koblenz)
slobo 195504
die kinder
kreissozialamt hammeln-jeypm
st. h. 1709 r
berlin 50, stoltenbergstr. 11/13
doppelmeldung trier
nabers verfolgten
afw - mettmann, rp - düsseldorf
sozialaus ausschuss der verfolgten des naziregimes hessen, frankfurt a.m., rossebertstr. 4
fu bayerisches verfolgten/abgabestelle
reg.-präsident / präsident des verw.-bezirks göttingen
united restitution office, ffm., grünburgweg 119
ko
niedersachsen - präsident / präsident des verw.-bezirks
doppelanmeldung in wien
bundeszentralstelle für verfolgte
k61a
kreissonderhilfsschuf
higher commissioner of the allied nations for refugees
wbb
efurt
neustadt saarburg
nieders. minister des innern hannover
kreissozialamt schauemburg-lippe
niedersachsenpräsidex präsident des verw.-bezirks braunschweig
e 3598
kreis
k.g.19
kreissozialamt - land
niedersachsen-präsident / präsident des versicherungsverwaltungsbezirks
soz.amt münchen
st. lambert
bundesamt für die verwaltung des vermögens der flüchtlinge und vertriebenen
reg.-präsident / präsident des verw.-bezirksso
bayerische verwaltungsbehörde
niedersachsen g.-präsident / präsident des verwaltungsgerichts hannover
regierung pommersfelden
reg.-präsident / präsident des verw.-bezirks braune hwdg
bayerisches landesamt für den regierungsbezirk münchen
altenkirchen 'westf.
staatsliches institut
niedersachsen-präsident / präsident des niedersächsischen verwaltungsgerichts
2101n
beschädigtenbehörde
bundesverwaltung
kärnten
89835/i=15449
reg.-präsident / präsident des vew. bezirks hannover
regierungsbezirk neuss
niedersachsen - präsident / präsident des verwaltungs-bereichs
niedersachsen - präsident / president of the state
doppelmeldungen mainz
e 101-54
regional office for compensation and administration of assets, koblenz
k8n
emmendingen
sondervermögens- u. raubvermögenswaltung
bayrisches landesamt für archiv und genealogie

# Calling LLM via API using NaN values

In [14]:
from groq import Groq
from huggingface_hub import InferenceClient
from huggingface_hub.utils import HfHubHTTPError

import time
import json
import os
from dotenv import load_dotenv
from tqdm import tqdm

/home/Benha/Projects/Arbeit/FIZ/compensation-office-analysis/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
load_dotenv()

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "groq").strip().lower()
HF_MODEL = os.getenv("HF_MODEL", "Qwen/Qwen3-8B")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")

# choosing between Hugging Face and Groq based on environment variable, standard = groq
if LLM_PROVIDER == "huggingface":
    HF_API_TOKEN = os.getenv("HF_API_KEY")
    if not HF_API_TOKEN:
        raise ValueError("HF_API_KEY is required when LLM_PROVIDER='huggingface'")
    client = InferenceClient(
        model=HF_MODEL,
        token=HF_API_TOKEN
    )
    ACTIVE_MODEL = HF_MODEL
elif LLM_PROVIDER == "groq":
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")
    if not GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY is required when LLM_PROVIDER='groq'")
    client = Groq(api_key=GROQ_API_KEY)
    ACTIVE_MODEL = GROQ_MODEL
else:
    raise ValueError("LLM_PROVIDER must be either 'huggingface' or 'groq'")

print(f"Using LLM provider: {LLM_PROVIDER}, model: {ACTIVE_MODEL}")

offices_list = "\n".join([f"- {office}" for office in compensation_offices])

Using LLM provider: groq, model: llama-3.1-8b-instant

In [ ]:
# function to get LLM matches for a batch of query names, with error handling and retries
def get_llm_match_batch(query_names, offices_list, max_retries=3):
    
    queries = "\n".join([f"{i+1}. \"{name}\"" for i, name in enumerate(query_names)])
    
    prompt = f"""You are an expert at matching German compensation office names (Entschädigungsämter).

Given these query names:
{queries}

Find the BEST match for EACH from this list:
{offices_list}

Rules:
1. Return ONLY a numbered list with the exact name from the list
2. Consider spelling variations and OCR errors
3. If no match exists, write \"NO_MATCH\"
4. Format: \"1. Matching Name\" or \"1. NO_MATCH\"

Answers:"""

    messages = [{"role": "user", "content": prompt}]
    
    for attempt in range(max_retries):
        try:
            if LLM_PROVIDER == "huggingface":
                response = client.chat_completion(
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            elif LLM_PROVIDER == "groq":
                response = client.chat.completions.create(
                    model=ACTIVE_MODEL,
                    messages=messages,
                    max_tokens=500,
                    temperature=0.1
                )
                text = response.choices[0].message.content
            else:
                raise ValueError(f"Unsupported LLM provider: {LLM_PROVIDER}")
            
            matches = []
            lines = text.split('\n')
            for line in lines:
                line = line.strip()
                if line and len(line) > 0 and line[0].isdigit():
                    parts = line.split('.', 1) if '.' in line else line.split(')', 1)
                    if len(parts) > 1:
                        match = parts[1].strip()
                        matches.append(match)
            
            # if the model returned fewer matches than query names, fill the rest with "PARSE_ERROR"
            # TODO: here the mapping might break if one input is skipped by the model in the middle rather than the end
            while len(matches) < len(query_names):
                matches.append("PARSE_ERROR")
            
            return matches[:len(query_names)]
            
        except HfHubHTTPError as e:
            error_str = str(e).lower()
            if "429" in str(e) or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in str(e) or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  # Signal to stop processing
            elif "503" in str(e) or "loading" in error_str:
                print(f"Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"HTTP Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
        except Exception as e:
            error_str = str(e).lower()
            if "429" in error_str or "rate" in error_str:
                print(f"Rate limited. Waiting 30s before retry (attempt {attempt+1}/{max_retries})...")
                time.sleep(30)
            elif "402" in error_str or "quota" in error_str or "exceeded" in error_str:
                print("API quota exceeded! Stopping.")
                return None  
            elif "503" in error_str or "loading" in error_str:
                print("Model loading. Waiting 20s...")
                time.sleep(20)
            else:
                print(f"Error: {e}")
                if attempt < max_retries - 1:
                    time.sleep(10)
                else:
                    return ["ERROR"] * len(query_names)
    
    return ["ERROR"] * len(query_names)

# test the function with the first 2 unmatched office names
test_names = no_matched_office_df['CompensationOffice1'].iloc[:2].tolist()
print(f"Testing with:")
for i, name in enumerate(test_names):
    print(f"  {i+1}. {name}")
print()
results = get_llm_match_batch(test_names, offices_list)
if results:
    print("LLM suggested matches:")
    for i, result in enumerate(results):
        print(f"  {i+1}. {result}")
else:
    print("API limit reached during test!")

Testing with:
  1. hess. staatsministerium
  2. nan

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...
LLM suggested matches:
  1. ERROR
  2. ERROR

In [ ]:
BATCH_SIZE = 10
DELAY_BETWEEN_BATCHES = 5  

output_file = 'llm_matches_progress.jsonl'

# Load already processed entries to avoid duplicates and allow resuming
processed = set()
llm_matches = []
try:
    with open(output_file, 'r') as f:
        for line in f:
            entry = json.loads(line)
            llm_matches.append(entry)
            processed.add(entry['CompensationOffice1'])
    print(f"Resuming from {len(processed)} already processed entries")
except FileNotFoundError:
    print("Starting fresh")

df_remaining = no_matched_office_df[~no_matched_office_df['CompensationOffice1'].isin(processed)]
print(f"Remaining to process: {len(df_remaining)}")


# Process in batches and save progress after each batch
total_batches = (len(df_remaining) + BATCH_SIZE - 1) // BATCH_SIZE
api_limit_reached = False

for batch_idx in tqdm(range(total_batches), desc="Processing batches"):
    if api_limit_reached:
        break
        
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(df_remaining))
    
    batch_df = df_remaining.iloc[start_idx:end_idx]
    batch_names = batch_df['CompensationOffice1'].tolist()
    
    batch_results = get_llm_match_batch(batch_names, offices_list)
    
    if batch_results is None:
        print("\nAPI limit reached! Saving progress and stopping.")
        api_limit_reached = True
        break
    
    for i, (idx, row) in enumerate(batch_df.iterrows()):
        entry = {
            'CompensationOffice1': row['CompensationOffice1'],
            'MatchedOffice': row['MatchedOffice'],
            'MatchDistance': float(row['MatchDistance']) if pd.notna(row['MatchDistance']) else None,
            'LLMMatch': batch_results[i] if i < len(batch_results) else "ERROR"
        }
        llm_matches.append(entry)
        
        with open(output_file, 'a') as f:
            f.write(json.dumps(entry) + '\n')
    
    if batch_idx < total_batches - 1 and not api_limit_reached:
        time.sleep(DELAY_BETWEEN_BATCHES)

df_llm_matches = pd.DataFrame(llm_matches)
print(f"\nProcessed: {len(df_llm_matches)} entries")
if api_limit_reached:
    print("Note: Processing stopped due to API limit. Run again later to continue.")
df_llm_matches.head(20)

Resuming from 59 already processed entries
Remaining to process: 70457

Processing batches:   0%|          | 0/7046 [00:00<?, ?it/s]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 1/7046 [01:35<186:25:28, 95.26s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 2/7046 [03:10<186:24:41, 95.27s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 3/7046 [04:45<186:25:15, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 4/7046 [06:21<186:25:45, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 5/7046 [07:56<186:22:32, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 6/7046 [09:31<186:21:02, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 7/7046 [11:07<186:18:45, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 8/7046 [12:42<186:16:36, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 9/7046 [14:17<186:14:49, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 10/7046 [15:52<186:13:20, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 11/7046 [17:28<186:10:47, 95.27s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 12/7046 [19:03<186:09:41, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 13/7046 [20:38<186:10:23, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 14/7046 [22:14<186:08:27, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 15/7046 [23:49<186:06:31, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 16/7046 [25:24<186:03:31, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 17/7046 [26:59<186:01:32, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 18/7046 [28:35<185:59:34, 95.27s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 19/7046 [30:10<185:56:36, 95.26s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 20/7046 [31:45<185:56:30, 95.27s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 21/7046 [33:20<185:55:41, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 22/7046 [34:56<185:55:41, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 23/7046 [36:31<185:54:23, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 24/7046 [38:07<185:59:14, 95.35s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 25/7046 [39:42<185:54:06, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 26/7046 [41:17<185:59:13, 95.38s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 27/7046 [42:53<185:54:16, 95.35s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 28/7046 [44:28<185:50:35, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 29/7046 [46:03<185:46:04, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 30/7046 [47:38<185:43:55, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 31/7046 [49:14<185:42:19, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 32/7046 [50:49<185:41:33, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 33/7046 [52:24<185:41:04, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 34/7046 [54:00<185:38:02, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   0%|          | 35/7046 [55:35<185:47:15, 95.40s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 36/7046 [57:11<185:44:23, 95.39s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 37/7046 [58:46<185:40:00, 95.36s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 38/7046 [1:00:21<185:37:56, 95.36s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 39/7046 [1:01:57<185:34:51, 95.35s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 40/7046 [1:03:32<185:31:58, 95.34s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 41/7046 [1:05:07<185:29:42, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 42/7046 [1:06:43<185:36:00, 95.40s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 43/7046 [1:08:18<185:31:39, 95.37s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 44/7046 [1:09:53<185:29:53, 95.37s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 45/7046 [1:11:29<185:23:51, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 46/7046 [1:13:04<185:21:22, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 47/7046 [1:14:39<185:17:43, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 48/7046 [1:16:15<185:14:48, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 49/7046 [1:17:50<185:12:49, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 50/7046 [1:19:25<185:12:20, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 51/7046 [1:21:00<185:10:42, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 52/7046 [1:22:36<185:08:19, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 53/7046 [1:24:11<185:15:22, 95.37s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 54/7046 [1:25:47<185:11:51, 95.35s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 55/7046 [1:27:22<185:07:10, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 56/7046 [1:28:57<185:05:38, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 57/7046 [1:30:33<185:03:38, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 58/7046 [1:32:08<184:59:37, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 59/7046 [1:33:43<184:58:48, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 60/7046 [1:35:18<184:58:31, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 61/7046 [1:36:54<184:55:13, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 62/7046 [1:38:29<184:53:21, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 63/7046 [1:40:04<184:53:16, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 64/7046 [1:41:40<184:53:48, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 65/7046 [1:43:15<184:50:07, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 66/7046 [1:44:50<184:47:58, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 67/7046 [1:46:26<184:45:16, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 68/7046 [1:48:01<184:43:41, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 69/7046 [1:49:36<184:43:05, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 70/7046 [1:51:12<184:41:45, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 71/7046 [1:52:47<184:38:56, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 72/7046 [1:54:22<184:35:35, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 73/7046 [1:55:57<184:34:08, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 74/7046 [1:57:33<184:31:51, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 75/7046 [1:59:08<184:29:44, 95.28s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 76/7046 [2:00:43<184:30:23, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 77/7046 [2:02:19<184:29:51, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 78/7046 [2:03:54<184:28:11, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 79/7046 [2:05:29<184:27:20, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 80/7046 [2:07:05<184:28:52, 95.34s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 81/7046 [2:08:40<184:25:43, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 82/7046 [2:10:15<184:22:33, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 83/7046 [2:11:50<184:20:29, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 84/7046 [2:13:26<184:18:52, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 85/7046 [2:15:01<184:15:54, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 86/7046 [2:16:36<184:16:15, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 87/7046 [2:18:12<184:13:20, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|          | 88/7046 [2:19:47<184:12:08, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 89/7046 [2:21:22<184:09:32, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 90/7046 [2:22:58<184:09:02, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 91/7046 [2:24:33<184:05:56, 95.29s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 92/7046 [2:26:08<184:07:04, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 93/7046 [2:27:43<184:03:51, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 94/7046 [2:29:19<184:01:44, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 95/7046 [2:30:54<184:01:35, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 96/7046 [2:32:29<183:59:22, 95.30s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 97/7046 [2:34:05<183:58:23, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 98/7046 [2:35:40<183:56:44, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 99/7046 [2:37:15<183:56:08, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 100/7046 [2:38:51<183:54:33, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 101/7046 [2:40:26<183:51:52, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 102/7046 [2:42:01<183:50:42, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 103/7046 [2:43:37<183:49:42, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 104/7046 [2:45:12<183:48:48, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   1%|▏         | 105/7046 [2:46:47<183:45:56, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 106/7046 [2:48:23<183:47:01, 95.33s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 107/7046 [2:49:58<183:43:17, 95.32s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 108/7046 [2:51:33<183:41:24, 95.31s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 109/7046 [2:53:09<183:50:17, 95.40s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 110/7046 [2:54:44<183:51:57, 95.43s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 111/7046 [2:56:20<183:56:26, 95.48s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 112/7046 [2:57:55<183:57:33, 95.51s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 113/7046 [2:59:31<184:00:08, 95.54s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 114/7046 [3:01:07<184:03:41, 95.59s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 115/7046 [3:02:42<184:03:36, 95.60s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 116/7046 [3:04:18<184:08:59, 95.66s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...
Rate limited. Waiting 30s before retry (attempt 3/3)...

Processing batches:   2%|▏         | 117/7046 [3:05:54<184:06:30, 95.65s/it]

Rate limited. Waiting 30s before retry (attempt 1/3)...
Rate limited. Waiting 30s before retry (attempt 2/3)...

In [ ]:
valid_matches = df_hf_matches[~df_hf_matches['LLMMatch'].isin(['NO_MATCH', 'ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]
no_matches = df_hf_matches[df_hf_matches['LLMMatch'] == 'NO_MATCH']
errors = df_hf_matches[df_hf_matches['LLMMatch'].isin(['ERROR', 'PARSE_ERROR', 'RATE_LIMITED'])]

print(f"Total processed: {len(df_hf_matches)}")
print(f"LLM found matches: {len(valid_matches)} ({len(valid_matches)/max(len(df_hf_matches),1)*100:.1f}%)")
print(f"No match found: {len(no_matches)}")
print(f"Errors: {len(errors)}")